// =========================================================================
//  BERICHT-INFO — „Schaufenster" für jeden Bericht: Was sagt er aus? Für wen
//  ist er gedacht? Welchen Mehrwert bringt er? So sieht jeder, was es gibt –
//  auch ohne Berechtigung (dann ausgegraut, nur Info, kein Aufruf).
//  Schlüssel = ansicht-/view-Key (wie in navMeta/Navigation).
// =========================================================================
export const BERICHT_INFO = {
  // ---- Einstieg ----
  startseite: { zweck: 'Persönlicher Einstieg: die wichtigsten Kennzahlen, Auffälligkeiten und Schnellzugriffe gebündelt auf einer Seite.', zielgruppe: 'Alle Rollen.', mehrwert: 'Sofort den richtigen Bericht und die dringendsten Themen finden, ohne zu suchen.',
    inhalt: 'Rollenabhängige Übersicht mit Lage-Ampel, kritischsten Kennzahlen, zuletzt geöffneten/favorisierten Berichten und Sprungpunkten in die Fachbereiche.',
    fragen: ['Wo stehe ich gerade?', 'Was ist heute wichtig?', 'Wo muss ich zuerst hin?'],
    lesehilfe: 'Kacheln führen direkt in den jeweiligen Bericht; die Ampel zeigt den Gesamtstatus.', quelle: 'KPI-Engine + Navigation.' },
  // ---- Cockpit & Berichte ----
  baum: { zweck: 'Zentraler Einstieg: alle Berichte hierarchisch von der Geschäftsführung bis zum Detail.', zielgruppe: 'Alle Rollen.', mehrwert: 'Schneller Überblick und Drill-down bis zur Einzelkennzahl.',
    inhalt: 'Fünf Ebenen (E1 Geschäftsführung → E2 Fachbereich → E3 Themenbereich → E4 Details → E5 Historie). Je Knoten: automatische Lagebewertung, kritischste KPIs zuerst (Karten- oder Tabellensicht), Controller-Kommentar und Drill in die Detaillisten.',
    fragen: ['Wie steht das Unternehmen insgesamt da?', 'Welcher Bereich/Knoten ist auffällig?', 'Wo muss ich zuerst handeln?'],
    lesehilfe: 'Knoten links aufklappen oder Unterknoten wählen; die Ampel-Verteilung zeigt grün/amber/rot je Knoten. Über ⛓ an der KPI-Karte die Herkunft drillen.', quelle: 'KPI-Engine über alle Bereiche.' },
  kennzahlen: { zweck: 'Nachschlagewerk aller KPIs mit Definition, Ziel und Abhängigkeiten.', zielgruppe: 'Alle, v. a. Controlling.', mehrwert: 'Einheitliches Verständnis der Kennzahlen.',
    inhalt: 'Alle Kennzahlen mit Bedeutung, Formel, Ziel-/Ampel-Logik, Horizont (operativ/strategisch) und Art (monetär/nicht-monetär). Filter und Suche; Controlling/Admin können Definitionen bearbeiten und KPIs freigeben.',
    fragen: ['Was bedeutet diese Kennzahl und wie wird sie berechnet?', 'Welches Ziel/Budget gilt?', 'Welche KPIs sind noch nicht freigegeben?'],
    lesehilfe: 'Über das ⓘ (auch an jeder Karte im Bericht) öffnet sich der vollständige Steckbrief. Freigabe: ✓ freigegeben, ✎ Entwurf, ⊘ deaktiviert.', quelle: 'KPI-Registry + Overrides/Freigaben (lokal).' },
  tagesreporting: { zweck: 'Täglicher Blick: operative Kernkennzahlen heute vs. gestern mit „seit gestern"-Delta und dem Verlauf der letzten 14 Tage.', zielgruppe: 'Alle operativen Rollen / Vertrieb / Leitung.', mehrwert: 'Schneller Start in den Tag; Auffälligkeiten sofort sehen.',
    inhalt: 'Umsatz, Auftragseingang, Absatzmenge, Retouren und offener Auftragsbestand — je als Heute-Wert, Delta zum Vortag, Ø der letzten 14 Tage und Sparkline. „Was sticht heute heraus"-Chips.',
    fragen: ['Wie war der gestrige Tag im Vergleich zum Vortag?', 'Gibt es heute eine auffällige Bewegung (> 5 %)?', 'Liegen wir über oder unter dem 14-Tage-Schnitt?'],
    lesehilfe: 'Grün = in die gewünschte Richtung, rot = dagegen (bei Retouren ist weniger besser).', quelle: 'Tagesaktuelle operative Bewegungsdaten (Demo).' },
  katalog: { zweck: 'Durchsuchbarer Katalog aller verfügbaren Berichte.', zielgruppe: 'Alle.', mehrwert: 'Den passenden Bericht schnell finden.' },
  kpieditor: { zweck: 'Eigene, abgeleitete KPIs aus Formeln definieren.', zielgruppe: 'Controlling / Power-User.', mehrwert: 'Individuelle Kennzahlen ohne IT.' },
  designer: { zweck: 'Eigene Berichte aus KPIs zusammenstellen.', zielgruppe: 'Power-User / Controlling.', mehrwert: 'Flexible, wiederverwendbare Auswertungen.' },
  detailberichte: { zweck: 'Granulare Listen (Artikel, Aufträge …) für die Einzelfallprüfung mit Plausibilitätskontrolle.', zielgruppe: 'Controlling / Stammdaten / Fachbereiche.', mehrwert: 'Falscheingaben und unplausible Datenvorgänge gezielt finden und validieren.',
    inhalt: '17 Detaillisten (Artikel, Aufträge, Rechnungen mit Positionen, Konten, Chargen …) mit Plausi-Befunden (Fehler/Warnung/Hinweis), Spaltenwahl, Bookmarks, Daten-Balken, Dimensionsfilter und CSV-Export.',
    fragen: ['Welche Datensätze sind auffällig oder fehlerhaft?', 'Wo weicht ein Einzelwert vom Erwarteten ab?', 'Welche Belege hängen zusammen (Cross-Drill)?'],
    lesehilfe: 'Roter Zeilenrand = Fehler, gelb = Warnung, blau = Hinweis. Klick auf eine Zeile öffnet die Befund-Karte mit E5-Historie.', quelle: 'Mock/WaWi-Detaildaten (später SQL-Anbindung).' },
  // ---- Kosten & Ergebnis ----
  klr: {
    zweck: 'Grundlagen und Fluss der Kosten- & Leistungsrechnung (KLR): von der Kostenartenrechnung über die Kostenstellenrechnung bis zur Kostenträgerrechnung.',
    inhalt: 'Dreistufige KLR-Struktur als Flussdiagramm (Kostenartenrechnung → Kostenstellenrechnung → Kostenträgerrechnung), Abgrenzungsübersicht, Verbindung zu BAB und Kalkulation, interaktive Beschriftungen je Stufe.',
    zielgruppe: 'Controlling, Rechnungswesen, Auszubildende/Studierende.',
    mehrwert: 'Vermittelt das vollständige KLR-System auf einen Blick — ideal als Einstieg und Nachschlagewerk für alle, die Kosten richtig zuordnen und verstehen müssen.',
    fragen: ['Wie fließen Kosten von der Kostenartenrechnung in die Kostenstellen?', 'Was kommt in den BAB?', 'Wie wird aus dem BAB eine Kalkulation?', 'Was ist der Unterschied zwischen GuV und KLR-Ergebnis?'],
    lesehilfe: 'Den Pfeilen in der Fluss-Grafik folgen: Links oben starten (Kostenartenrechnung), über den BAB (Mitte) zur Kalkulation (rechts) und zum Betriebsergebnis.',
    quelle: 'KLR-Grundsätze nach VDMA/IKR; Bezug zu Finanzbuchhaltung und Planung; Demo-Daten (Mock).'
  },
  einzelgemein: {
    zweck: 'Systematische Trennung von Einzel- und Gemeinkosten als Grundlage der Zuschlagskalkulation — mit Gemeinkostenzuschlagssätzen je Kostenstelle.',
    inhalt: 'Kostenartentabelle (Einzel-/Gemeinkosten-Split), Gemeinkostenzuschlagssätze (Material-GK, Fertigungs-GK, Verwaltungs-GK, Vertriebs-GK), Beispielkalkulation, grafische Aufteilung.',
    zielgruppe: 'Kalkulation, Controlling, Kostenrechner:innen.',
    mehrwert: 'Saubere Gemeinkostenverrechnung verhindert Mischpreise und zeigt, welche Produkte zu günstigen/ungünstigen GK-Sätzen produziert werden.',
    fragen: ['Welche Kosten sind Einzel-, welche Gemeinkosten?', 'Wie hoch sind die Gemeinkostenzuschlagssätze je Stelle?', 'Welches Produkt treibt den Fertigungs-GK?', 'Wo kann der GK-Satz gesenkt werden?'],
    lesehilfe: 'Grün = direkt zurechenbar (Einzelkosten). Grau = über Kostenstellen zu verteilen (Gemeinkosten). GK-Satz = Gemeinkosten ÷ Bezugsgröße (z. B. Fertigungs-Lohn).',
    quelle: 'Finanzbuchhaltung, Kostenstellenrechnung; Demo-Daten (Mock).'
  },
  abgrenzung: {
    zweck: 'Überleitung von der handelsrechtlichen GuV zum KLR-Betriebsergebnis: neutrale Erträge/Aufwendungen herausrechnen, kalkulatorische Kosten ergänzen.',
    inhalt: 'Abgrenzungsbrücke (GuV-Ergebnis → neutrales Ergebnis → Betriebsergebnis), Tabelle neutrale Erträge/Aufwendungen, kalkulatorische Kostenarten (Abschr., Zinsen, Wagnis, Unternehmerlohn, Miete), Vergleich Plan/Ist.',
    zielgruppe: 'Rechnungswesen, Controlling, Wirtschaftsprüfung.',
    mehrwert: 'Das Betriebsergebnis spiegelt die echte Leistungsfähigkeit des Betriebs — ohne einmalige Sondereffekte und mit vollständigen Kapitalkosten.',
    fragen: ['Wie weit weicht das KLR-Ergebnis vom handelsrechtlichen ab?', 'Welche neutralen Posten verzerren das GuV-Ergebnis?', 'Sind kalkulatorische Zinsen und Abschreibungen vollständig erfasst?', 'Stimmt der Abgrenzungssaldo?'],
    lesehilfe: 'Neutrale Erträge (z. B. Anlageverkäufe) werden abgezogen, neutrale Aufwendungen (z. B. außerplanmäßige Abschr.) werden addiert. Kalkulatorische Kosten erhöhen das Betriebsergebnis.',
    quelle: 'GuV (HGB), Kostenrechnung; Anlagenspiegel für kalk. Abschreibungen; Demo-Daten (Mock).'
  },
  kalkulatorik: { zweck: 'Kalkulatorische Kosten (Abschreibung, Zinsen, Wagnisse, Miete, Unternehmerlohn) je Wirtschaftsjahr aufbauen — mit begründeten Vorschlägen, „Vorjahr kopieren" und Monatsverteilung.', zielgruppe: 'Controlling / Rechnungswesen.', mehrwert: 'Anders-/Zusatzkosten je Jahr pflegen und sauber ins Betriebsergebnis überleiten.' },
  kostenstellen: {
    zweck: 'Vollständige Kostenstellenrechnung: Primärkosten je Stelle, innerbetriebliche Leistungsverrechnung (Sekundärumlage), Endkosten und Zuschlagssätze.',
    inhalt: 'Kostenstellenübersicht (Primär-/Sekundärkosten, Endkosten, Plan/Ist/Abw.), Umlage-Matrix (ILV), Zuschlagssätze je Hilfskostenstelle, Abweichungsampel je Stelle, Drill bis Einzelkostenart.',
    zielgruppe: 'Controlling, Kostenstellenverantwortliche, Bereichsleitung.',
    mehrwert: 'Zeigt genau, wo Gemeinkosten entstehen und wie sie sich auf Fertigungs-/Dienstleistungsstellen verteilen — Grundlage für Kalkulation und Leistungsverrechnung.',
    fragen: ['Welche Kostenstellen überziehen den Plan?', 'Wie verteilt sich die innerbetriebliche Leistung (Umlage)?', 'Wie hoch ist der Fertigungs-GK-Satz je Stelle?', 'Wo ist das Verhältnis Fix-/Variabelkosten kritisch?'],
    lesehilfe: 'Rote Ampel = Kostenstelle über Plan. Klick auf Stelle → Aufschlüsselung nach Kostenart. Zuschlagssatz = Endkosten ÷ Bezugsgröße.',
    quelle: 'Finanzbuchhaltung, Personalabrechnung, innerbetriebliche Leistungsmengen; Demo-Daten (Mock).'
  },
  bab: {
    zweck: 'Betriebsabrechnungsbogen (BAB): vollständige Gemeinkostenverteilung von Vorkostenstellen auf Endkostenstellen — Bindeglied zwischen Kostenartenrechnung und Kalkulation.',
    inhalt: 'BAB-Tabelle (Kostenarten als Zeilen, Kostenstellen als Spalten), Umlagespalten (ILV), Endkostenstellen-Summen, Zuschlagssatz-Berechnung, Plan/Ist-Vergleich mit Abweichungsmarkierung.',
    zielgruppe: 'Controlling, Rechnungswesen, Prüfer:innen.',
    mehrwert: 'Stellt die vollständige Kostenverteilung transparent dar — unverzichtbar für eine verursachungsgerechte Kalkulation und belastbare Gemeinkostenzuschlagssätze.',
    fragen: ['Welche Kostenstellen erhalten wie viele Gemeinkosten?', 'Stimmt die innerbetriebliche Leistungsverrechnung?', 'Wie hoch ist der Fertigungslohn-GK-Satz?', 'Wo weichen Plan und Ist stark ab?'],
    lesehilfe: 'Von links nach rechts lesen: Kostenartenzeilen → Vorkostenstellen → Umlage → Endkostenstellen. Zuschlagssätze stehen ganz unten je Spalte.',
    quelle: 'Kostenartenrechnung, Kostenstellenrechnung, innerbetriebliche Leistungsmengen; Demo-Daten (Mock).'
  },
  kalkulation: {
    zweck: 'Kostenträgerrechnung: Selbstkosten, Preisuntergrenze und Produktergebnis je Artikel — mit fünf Kalkulationsverfahren (Divisions-, Äquivalenz-, Zuschlag-, Maschinen-, Kuppelkalkulation).',
    inhalt: 'Kalkulationsschema je Produkt (Material-EK → Herstellkosten → Selbstkosten → Deckungsbeitrag), Vergleich Kalkulationsverfahren, Preisuntergrenze (kurzfristig/langfristig), Ist- vs. Plankalkulation, Retrograder Ansatz.',
    zielgruppe: 'Kalkulation, Vertrieb (Angebote), Controlling, Produktmanagement.',
    mehrwert: 'Gibt für jedes Produkt die verlässliche Preisuntergrenze und den Produktergebnisbeitrag — Grundlage für Angebote, Rabattverhandlungen und Sortimentsentscheidungen.',
    fragen: ['Wie hoch sind die Selbstkosten je Fahrrad/Artikel?', 'Was ist die kurzfristige Preisuntergrenze?', 'Welches Produkt hat die höchste/niedrigste Marge?', 'Stimmt die Plankalkulation mit den Ist-Kosten überein?', 'Welches Kalkulationsverfahren passt zum Produkt?'],
    lesehilfe: 'Kurzfristige PUG = variable Kosten (kein Fixkostenanteil). Langfristige PUG = Selbstkosten gesamt. Deckungsbeitrag = Preis − variable Kosten; positiv = Fixkostenbeitrag.',
    quelle: 'Materialkosten (EK-Statistik), Lohnkosten (HR), BAB-Zuschlagssätze, Planung; Demo-Daten (Mock).'
  },
  ergebnis: {
    zweck: 'Ergebnisrechnung (Gewinn- und Verlustrechnung): Umsatzerlöse bis Jahresüberschuss in der Staffelform (UKV/GKV), ergänzt durch das klassische T-Konto-Format.',
    inhalt: 'GuV-Staffel (Umsatz → Rohertrag → EBITDA → EBIT → EBT → Jahresüberschuss), T-Konto (Aufwands-/Ertragskonten), Plan/Ist/VJ-Vergleich je Zeile, Abweichungsampel, Margenpyramide, Export.',
    zielgruppe: 'Geschäftsführung, Finanzen/Rechnungswesen, Banken, Investoren.',
    mehrwert: 'Transparente Ergebnisstruktur auf einen Blick — zeigt, wo Erträge entstehen und wo Kosten die Marge auffressen; direkt HGB-konform aufgebaut.',
    fragen: ['Wie hoch ist der Jahresüberschuss?', 'Wo weicht das Ist vom Plan ab?', 'Wie entwickelt sich die EBIT-Marge?', 'Welche Kostenblöcke wachsen überproportional?', 'Ist das Ergebnis mit Vorjahr vergleichbar?'],
    lesehilfe: 'Positive Zahlen = Erträge, negative = Aufwendungen. EBITDA schließt Abschreibungen aus (Vergleichbarkeit). EBIT = operatives Ergebnis. Rote Abweichung = unter Plan/VJ.',
    quelle: 'Finanzbuchhaltung (HGB/IFRS), Jahresabschluss; Demo-Daten (Mock).'
  },
  deckungsbeitrag: {
    zweck: 'Deckungsbeitragsrechnung ein- und mehrstufig: von DB I (nach variablen Kosten) über DB II (nach produktfixen Kosten) bis zum Betriebsergebnis — je Produkt, Warengruppe und Kanal.',
    inhalt: 'DB-Stufenrechnung (Erlöse → variable Kosten → DB I → produktfixe Kosten → DB II → Bereichsfixkosten → DB III → Unternehmensfixkosten → Betriebsergebnis), Produktranking nach DB I, Deckungspunkt-Analyse, Break-even-Menge, Engpassentscheidung.',
    zielgruppe: 'Vertrieb, Controlling, Produktmanagement, Geschäftsführung.',
    mehrwert: 'Zeigt, welche Produkte/Kanäle die Fixkosten decken — und welche im Sortiment zu überdenken sind. Ermöglicht kurzfristige Preis- und Volumenzentscheidungen auf Basis von Grenzkostenrechnung.',
    fragen: ['Welches Produkt hat den höchsten DB I/II?', 'Wo liegt der Break-even?', 'Welches Produkt sollte bei Engpass bevorzugt gefertigt werden?', 'Decken alle Kanäle ihre variablen Kosten?', 'Wo sind produktfixe Kosten unverhältnismäßig hoch?'],
    lesehilfe: 'DB I = Erlös − variable Kosten. Positiver DB I = Beitrag zur Fixkostendeckung. Negativer DB I = jede Einheit macht einen Verlust — sofortige Maßnahme. Break-even: Menge × DB I = Fixkosten.',
    quelle: 'Kostenrechnung, Finanzbuchhaltung, Absatzdaten; Demo-Daten (Mock).'
  },
  profitcenter: {
    zweck: 'Profitcenter-Ergebnisrechnung: Erlöse, Kosten und Ergebnis je Profit-Center — mit Kapitalrendite (ROCE), Dimension-Umschalter (Geschäftsbereich/Region/Kanal) und Drill bis zur Kostenstelle.',
    inhalt: 'PC-Übersicht (Erlöse/Kosten/EBIT/ROCE je PC), Ampel je PC, Benchmark-Vergleich (beste/schlechteste PC), Monatsverlauf, Dimension-Chips (Geschäftsbereich/Region/Kanal), Drill → Kostenstellen-Zuordnung.',
    zielgruppe: 'Bereichsleitung, Controlling, Geschäftsführung.',
    mehrwert: 'Dezentrale Ergebnisverantwortung auf einen Blick: Wer liefert — und wer nicht? ROCE setzt Ergebnis ins Verhältnis zum eingesetzten Kapital.',
    fragen: ['Welche Profit-Center sind profitabel?', 'Wie entwickelt sich das PC-Ergebnis über Monate?', 'Welcher Kanal/Region ist am stärksten?', 'Wie hoch ist die Kapitalrendite (ROCE) je PC?', 'Welche Kostenstellen machen ein PC defizitär?'],
    lesehilfe: 'ROCE = EBIT ÷ investiertes Kapital. Grüne Ampel = EBIT und ROCE über Ziel. Dimension-Chips wechseln die Gruppierungsebene. Klick auf PC → Kostenstellen-Drill.',
    quelle: 'Finanzbuchhaltung, Kostenstellenrechnung, Kapitalstruktur; Demo-Daten (Mock).'
  },
  segment: {
    zweck: 'Segment- und Konzernbericht: Ergebnisse je Segment (Fahrräder/Teile/Bekleidung), Intercompany-Eliminierungen und konsolidierte Gesamtsicht — nach IFRS 8 / HGB § 264.',
    inhalt: 'Segment-Kacheln (Umsatz/EBIT/EBIT-Marge/eingesetztes Kapital je Segment), Intercompany-Eliminierungsbrücke, konsolidierte GuV-Staffel, Segment-Zeitverlauf, Überleitung Segment-Ergebnis → Konzernergebnis.',
    zielgruppe: 'Geschäftsführung, Konzerncontrolling, Wirtschaftsprüfung, Investoren.',
    mehrwert: 'Pflichtbestandteil für segmentberichtspflichtige Unternehmen (IFRS 8 / § 264) und Steuerungsinstrument für Geschäftsbereichsverantwortliche — zeigt, welches Segment Wert schafft.',
    fragen: ['Welches Segment ist am profitabelsten (EBIT-Marge)?', 'Wie hoch sind die Intercompany-Transaktionen?', 'Wie entwickeln sich die Segmente im Jahresverlauf?', 'Welches Segment bindet das meiste Kapital?'],
    lesehilfe: 'Intercompany-Posten werden konsolidierend eliminiert (erscheinen in beiden Segmenten, kürzen sich im Konzern heraus). ROCE = EBIT ÷ eingesetztes Kapital je Segment.',
    quelle: 'Finanzbuchhaltung (je Gesellschaft/Segment), Konsolidierungstool; Demo-Daten (Mock).'
  },
  // ---- Operativ ----
  marketing: {
    zweck: 'Digital-Analytics-Dashboard: Funnel (Klicks → Leads → Aufträge), Conversion-Rates je Kanal, ROAS, Kampagnenvergleich und Retargeting-Effizienz.',
    inhalt: 'Funnel-Visualisierung (Impressionen → Klicks → Warenkörbe → Kaufabschlüsse), ROAS je Kampagne/Kanal, CPA (Cost per Acquisition), Lifetime-Value-Schätzung, Retargeting-Quote, Google/Meta/E-Mail-Vergleich, Zeitverlauf und Wochenmuster.',
    zielgruppe: 'Marketing, Vertrieb, E-Commerce-Management.',
    mehrwert: 'Zeigt genau, welcher Kanal und welche Kampagne Ergebnis bringt — und welche Budgets verbrannt werden. Basis für performancebasiertes Marketing-Budgeting.',
    fragen: ['Welcher Kanal hat den besten ROAS?', 'Wo bricht der Funnel ein (schlechteste Conversion-Rate)?', 'Welche Kampagne hat den niedrigsten CPA?', 'Wie entwickelt sich die Conversion-Rate über die Zeit?', 'Lohnt sich Retargeting?'],
    lesehilfe: 'ROAS > 3 = Kampagne profitabel. CPA = Gesamtkosten ÷ Käufer. Conversion-Rate = Kaufabschlüsse ÷ Klicks. Roter Kanal = unter Ziel-ROAS.',
    quelle: 'Google Analytics, Meta Ads Manager, E-Mail-Plattform, CRM (Aufträge); Demo-Daten (Mock).'
  },
  marketingkarte: { zweck: 'Geografische Verteilung mit Drilldown (Welt → Europa → Deutschland → Bundesland → PLZ-Gebiet) als Choropleth-Kachelkarte; wählbare Metrik (Umsatz, Marktanteil, DB %, Online-Anteil) und Warenbereichs-Split je Region.', zielgruppe: 'Marketing / Vertrieb / GF.', mehrwert: 'Stärkste/schwächste Regionen und Marktpotenziale auf einen Blick.',
    inhalt: 'Kachelkarte je Ebene; Farbintensität = gewählte Metrik; je Region Umsatzanteil, DB % und Warenbereichs-Split (Fahrräder/Zubehör/Bekleidung). Breadcrumb-Navigation über die Ebenen.',
    fragen: ['In welcher Region/PLZ ist unser Marktanteil am höchsten?', 'Wo ist der Online-Anteil besonders groß?', 'Wie verteilt sich der Umsatz nach Warenbereichen je Region?'],
    lesehilfe: 'Dunklere Kachel = höherer Metrikwert. Klick auf eine Kachel mit › geht eine Ebene tiefer.', quelle: 'Regionale Vertriebs-/Marktdaten (Demo).' },
  marktpotenzial: { zweck: 'Geomarketing je PLZ-Gebiet: aus Einwohnerzahl und Pro-Kopf-Marktvolumen das adressierbare Marktpotenzial schätzen und dem eigenen Ist-Umsatz gegenüberstellen — Ausschöpfung (lokaler Marktanteil), Kaufkraft-Dichte und „White Spots".', zielgruppe: 'Vertrieb / Marketing / GF.', mehrwert: 'Unerschlossene Gebiete (viel Potenzial, schwache Durchdringung) finden und Expansion priorisieren.',
    inhalt: 'PLZ-Tabelle mit Einwohnern, Dichte (Ew/km²), Kaufkraft-Index, geschätztem Potenzial, Ist-Umsatz, Ausschöpfung (Balken vs. Zielanteil) und Potenzialreserve. Parameter (Marktvolumen/Kopf, Zielanteil) einstellbar; KI-Empfehlungen je Chance, per Klick als Maßnahme.',
    fragen: ['Wo haben wir das größte unerschlossene Marktpotenzial?', 'Welche Gebiete sind White Spots (viel Potenzial, kaum Umsatz)?', 'Wie viel Umsatz wäre holbar, wenn jede Region den Zielanteil erreicht?'],
    lesehilfe: 'Balken = Ausschöpfung, die Markierung zeigt den Zielanteil. Rot/„White Spot" = überdurchschnittliches Potenzial bei schwacher Durchdringung. 🏠 = eigener Standort.', quelle: 'PLZ × Einwohner/Fläche (suche-postleitzahl.org · Destatis · BKG) + eigener Umsatz; Demo.' },
  verkaufsstatistik: { zweck: 'Schneller Verkaufsüberblick: Umsatz und Absatz nach Warengruppe, Top-Artikeln und Vertriebskanal, mit Vorjahresvergleich und Deckungsbeitrag.', zielgruppe: 'Vertrieb / Leitung / GF.', mehrwert: 'Auf einen Blick sehen, womit und wo Umsatz entsteht und wie er sich entwickelt.',
    inhalt: 'KPI-Band (Umsatz, Wachstum, Menge, Ø Auftragswert, DB-Marge, Online-Anteil), Monatsverlauf Ist vs. Vorjahr, Warengruppen-Tabelle (Umsatz/Anteil/Menge/Ø-Preis/VJ/DB), Top-Artikel und Kanal-Split.',
    fragen: ['Wie entwickelt sich der Umsatz gegenüber Vorjahr?', 'Welche Warengruppe/Artikel tragen am meisten?', 'Wie verteilt sich der Umsatz auf die Kanäle?'],
    lesehilfe: '▲ grün = Wachstum, ▼ rot = Rückgang. Balken zeigen den Umsatzanteil je Warengruppe.', quelle: 'Verkaufs-/Umsatzdaten (Demo).' },
  fahrradstatistik: { zweck: 'Fahrradspezifische Statistik: verkaufte Kompletträder nach Kategorie, Antriebsart (E-Bike vs. ohne Motor), Preisklasse und Ø-Verkaufspreis/Marge.', zielgruppe: 'Vertrieb / Einkauf / Produktmanagement.', mehrwert: 'Den Produktmix der Räder und den E-Bike-Trend genau verstehen.',
    inhalt: 'KPI-Band (verkaufte Räder, Wachstum, Umsatz, Ø-Preis, E-Bike-Anteil, Ø-Marge), Antriebsart-Split, Kategorien-Tabelle (E-MTB/E-Trekking/MTB/Gravel/…) und Preisklassen-Verteilung.',
    fragen: ['Wie hoch ist der E-Bike-Anteil und wie wächst er?', 'Welche Rad-Kategorie verkauft sich am besten?', 'In welcher Preisklasse liegt der Schwerpunkt?'],
    lesehilfe: '🔋 markiert E-Bike-Kategorien. Balken = Stückanteil je Kategorie.', quelle: 'Verkaufsdaten Kompletträder (Demo).' },
  einkaufsstatistik: { zweck: 'Beschaffungsüberblick: Einkaufsvolumen nach Lieferant und Warengruppe, ABC-Analyse, Liefertreue/Qualität, Bestellungen und Konditionen.', zielgruppe: 'Einkauf / Controlling / GF.', mehrwert: 'Klumpenrisiken, schwache Lieferanten und Skonto-Potenziale erkennen.',
    inhalt: 'KPI-Band (Volumen, VJ, Bestellungen, Ø-Bestellwert, Liefertreue, Skonto-Potenzial), Lieferanten-Tabelle mit Risiko-Ampel und Konditionen, Volumen je Warengruppe und ABC-Analyse (Pareto).',
    fragen: ['Welche Lieferanten binden das meiste Volumen (Klumpenrisiko)?', 'Wo ist Liefertreue/Qualität kritisch?', 'Welches Skonto-Potenzial bleibt ungenutzt?'],
    lesehilfe: 'Ampelpunkt = Lieferantenrisiko. Beim Einkauf ist ein Volumenanstieg (▲) kostenseitig rot. A/B/C nach kumuliertem Volumen.', quelle: 'Einkaufs-/Lieferantendaten (Demo).' },
  produktionsstatistik: { zweck: 'Output-Statistik der Fertigung: produzierte Mengen je Produkt und Werk, Monatsverlauf, Ausschuss/First-Pass-Yield und Stückkosten.', zielgruppe: 'Produktion / Controlling.', mehrwert: 'Produktionsleistung, Qualität und Kapazität kompakt im Blick.',
    inhalt: 'KPI-Band (Menge, Ø/Monat, Produktionswert, OEE, Ausschuss, FPY), Monats-Output-Balken, Produkt-Tabelle (Menge/Trend/Ausschuss/FPY/Wert) und Output je Werk.',
    fragen: ['Wie viel produzieren wir je Produkt und Werk?', 'Wie entwickeln sich Ausschuss und First-Pass-Yield?', 'Welches Werk trägt welchen Output?'],
    lesehilfe: 'Ausschuss grün ≤ 2 %, gelb ≤ 3,5 %, sonst rot. Trend ▲/▼ vergleicht ersten und letzten Monat.', quelle: 'Produktionscontrolling (Demo).' },
  events: {
    zweck: 'Events & Aktionen: Messen, Probefahrten, Händleraktionen und Rabattkampagnen — mit Zeitraum, Kosten, erreichtem Umsatz und ROI.',
    inhalt: 'Aktionskalender (Kacheln nach Event-Typ), je Event: Kosten, Teilnehmer/Leads, Mehrumsatz im Aktionszeitraum, attributierter Umsatz (last-touch), ROI/ROAS, Nachverfolgung Folgekäufe bis 90 Tage, Vergleich Aktionszeitraum vs. Vorperiode.',
    zielgruppe: 'Marketing, Vertrieb, Händlernetzwerk, Eventmanagement.',
    mehrwert: 'Macht Marketingaktionen messbar: Welches Event bringt die meisten Leads? Welche Aktion hat den besten ROI? Basis für Event-Budget-Planung im nächsten Jahr.',
    fragen: ['Welches Event hatte den höchsten Mehrumsatz?', 'Wie hoch ist der ROI der letzten Probefahrt-Aktion?', 'Welche Events führen zu langfristigen Folgekäufen?', 'Lohnt sich die Messeteilnahme?'],
    lesehilfe: 'ROI > 0 = Event hat sich gerechnet. Folgekauf-Tracking bis 90 Tage nach Event (Cookie/CRM-Verknüpfung). Mehrumsatz = Ist-Umsatz Aktionszeitraum − Basis-Trend.',
    quelle: 'CRM/Eventmanagement-System, Kassendaten/WaWi, Marketing-Tracking; Demo-Daten (Mock).'
  },
  bestand: {
    zweck: 'Bestands-Gängigkeit: ABC/XYZ-Analyse nach Umsatz und Verbrauchsregelmäßigkeit — Renner und Ladenhüter identifizieren, Kapitalbindung und Lagerdauer steuern.',
    inhalt: 'ABC-Klassenverteilung (A=80 %, B=15 %, C=5 % Umsatzanteil), XYZ-Einteilung (X=stetig, Y=schwankend, Z=unregelmäßig), Kombinations-Matrix (AX bis CZ), Renner/Ladenhüter-Liste, Reichweiten-Ampel, Lagerumschlag.',
    zielgruppe: 'Logistik, Einkauf, Controlling, Lagerleitung.',
    mehrwert: 'Zeigt auf einen Blick, wo Kapital unnötig gebunden ist (CZ-Artikel) und wo Fehlmengenrisiko besteht (AX-Artikel mit geringer Reichweite) — Basis für differenzierte Bestellstrategie.',
    fragen: ['Welche Artikel binden das meiste Kapital?', 'Wo sind die Ladenhüter?', 'Welche Artikel haben kritische Reichweiten?', 'Wie verteilt sich unser Sortiment auf ABC-Klassen?', 'Wo ist der Lagerumschlag zu gering?'],
    lesehilfe: 'AX = Bestseller mit stetigem Verbrauch → hohe Priorität, just-in-time. CZ = seltene Artikel, unregelmäßig → auf Losgröße prüfen oder auslisten. Reichweite < Wiederbeschaffungszeit = Fehlmengenrisiko.',
    quelle: 'Lagerbewegungen, Absatzdaten, Stammdaten (Lieferzeit, Mindestbestand); Demo-Daten (Mock).'
  },
  lager: { zweck: 'Lagerverwaltung aus Controlling-Sicht: Kapitalbindung, Lagerhaltungskosten, Standortkosten, Bestandsoptimierung (EOQ).', zielgruppe: 'Logistik / Controlling.', mehrwert: 'Lagerkosten transparent machen und Bestände/Bestellmengen optimieren.',
    inhalt: 'Kostenstruktur (Lagerhaltungskostensatz), Standorte, Bestandsoptimierung (EOQ, Melde-/Sicherheits-/Höchstbestand, Status, Einsparpotenzial je Artikel), anklickbare Artikel mit KI-Empfehlungen und Lieferanten-Trend, Signale & KI mit Eskalation an die Einkaufsleitung.',
    fragen: ['Was kostet uns das Lager wirklich?', 'Welche Bestellmenge ist optimal?', 'Welcher Artikel ist Über-/Unterbestand?', 'Verschlechtert sich ein Lieferant schleichend?'],
    lesehilfe: 'Artikel anklicken öffnet Details + KI-Empfehlungen. Wichtige, unkommentierte Signale ploppen bei der Abteilungsleitung Einkauf auf — kommentieren = geklärt.', quelle: 'Bestands-/Lieferantendaten (Demo).' },
  wms: {
    zweck: 'Operatives Warehouse-Management: Lagerplätze, Wareneingänge, Kommissionieraufträge, Umlagerungen und vollständiges Bewegungsprotokoll — für den täglichen Lagerbetrieb.',
    inhalt: 'Lagerplatz-Übersicht (Platz-Auslastung, Artikel je Stellplatz), Wareneingangsmaske (WE-Prüfung, Einlagerungsvorschlag), Kommissionieraufträge (offen/in Bearbeitung/abgeschlossen), Umlagerungs-Log, Bewegungsprotokoll (FIFO/LIFO-Sicht), Inventur-Unterstützung.',
    zielgruppe: 'Lager, Logistik, Lagerleitstand.',
    mehrwert: 'Ersetzt papierbasierte Lagerhaltung: vollständige Rückverfolgbarkeit jeder Warenbewegung, optimale Einlagerungsvorschläge und direkter Status von Kommissionieraufträgen.',
    fragen: ['Welcher Artikel liegt auf welchem Lagerplatz?', 'Welche Kommissionieraufträge sind noch offen?', 'Wo gibt es Inventurdifferenzen?', 'Welche Einlagerungszone hat noch Kapazität?', 'Wie lief der Wareneingang heute?'],
    lesehilfe: 'Rote Lagerplätze = überbelegt oder gesperrt. Grün = frei/normal. Klick auf Platz → alle Artikel und Bewegungen dort. Bewegungsprotokoll: FIFO = älteste Charge zuerst entnehmen.',
    quelle: 'WMS/ERP (Lagerbewegungen, Lagerplatzverwaltung); Demo-Daten (Mock).'
  },
  produktion: { zweck: 'Produktionscontrolling strategisch & operativ: Werke/Linien (Live-Status, OEE), optimale Losgrößen (EPQ), Fehlteile, Qualität (FPY/Ausschuss) und Abgleich Produktion ↔ Lager ↔ Auftragsbestand.', zielgruppe: 'Produktion / Supply Chain / Controlling.', mehrwert: 'Engpässe, Fehlteile und Qualitätsprobleme früh erkennen, Losgrößen und Output optimal steuern.',
    inhalt: 'Cockpit (OEE, FPY, Auslastung, Termintreue), Werke & Linien live (welches Produkt läuft wo), Produktionsprogramm (EPQ-Losgrößen), Fehlteile mit blockierten Aufträgen, Qualität je Linie, Output & Markt-Abgleich (Produktion ↔ Lager ↔ Auftragsbestand).',
    fragen: ['Welche Linie ist der Engpass?', 'Welche Aufträge stehen wegen fehlender Teile?', 'Welche Losgröße ist am wirtschaftlichsten?', 'Sollen wir aufstocken oder drosseln?'],
    lesehilfe: 'OEE = Verfügbarkeit · Leistung · Qualität (Weltklasse ≥ 85 % ⭐). ⛰️ markiert den Engpass.', quelle: 'Produktions-/MES-Daten (Demo).' },
  szenario: { zweck: 'What-if-Simulator: Treiber-Kennzahlen prozentual oder absolut verändern und die Wirkung auf abgeleitete KPIs (DB, Margen, Ergebnis) live über den Abhängigkeitsgraph sehen.', zielgruppe: 'Controlling / GF.', mehrwert: 'Annahmen schnell durchspielen, ohne gespeicherte Werte zu ändern.',
    inhalt: 'Stellhebel (Nettoumsatz, Erlösschmälerung, Wareneinsatz, Personalkosten, Einkaufsvolumen, Online-Anteil) mit ±%-Slider oder absolutem Wert; rechts die Wirkungstabelle (Basis → Szenario, Delta) aller betroffenen abgeleiteten KPIs.',
    fragen: ['Was passiert mit dem DB, wenn der Umsatz +10 % macht?', 'Wie stark schlägt ein höherer Wareneinsatz durch?', 'Welche KPIs hängen an diesem Treiber?'],
    lesehilfe: 'Grün = Verbesserung, rot = Verschlechterung. Rein explorativ — gespeicherte Werte bleiben unverändert.', quelle: 'KPI-Abhängigkeitsgraph (berechneAlle).' },
  planung: { zweck: 'Budget-, Forecast- und Szenarienplanung: Mengen je Produkt bottom-up planen oder ein Ziel top-down herunterbrechen (Menge ↔ Betrag), inkl. Schwund-Aufschlag, Produktion ohne Umsatz und Liquiditätsvorschau.', zielgruppe: 'Controlling / Vertrieb / Einkauf / Produktion.', mehrwert: 'Alle haben dieselbe Vorstellung von den Plan-Werten; Wirkung von Annahmen sofort sichtbar.',
    inhalt: 'Pläne anlegen/kopieren; Ergebnis (Umsatz/Wareneinsatz/DB/AE/Liquidität); Top-Down-Verteilung; Monatsverteilung (Splash, inkl. Saison); Artikelverteilung über die Produkthierarchie; Termin-/Beschaffungssicht; Szenarienvergleich.',
    fragen: ['Welcher Umsatz/DB ergibt sich aus den Plan-Mengen?', 'Wann muss spätestens bestellt/produziert werden?', 'Wie unterscheiden sich Budget, Best und Worst Case?', 'Bleibt die Liquidität übers Jahr positiv?'],
    lesehilfe: 'Menge ODER Betrag eingeben — das andere wird über den VK-Preis berechnet. Im Szenarienvergleich ist die erste Spalte die Basis.', quelle: 'Lokale Plan-Daten (localStorage); Preise aus den Produktstammdaten.' },
  gutschriften: { zweck: 'Gutschriften & Retouren je Kunde, alle Belege über mehrere Versendungen verknüpft. Trennt Retourengutschriften (mit Absatzänderung) und Wertgutschriften (ohne), je in EUR und % zum tatsächlichen Auftrag.', zielgruppe: 'Vertriebscontrolling / Vertrieb / Buchhaltung.', mehrwert: 'Erkennen, ob man beim Kunden „sauber" ist; auffällige Retouren-/Wertgutschriftquoten früh sehen.',
    inhalt: 'Je Kunde: tatsächlicher Auftrag (AET), Retourengutschriften und Wertgutschriften in EUR und % zum AET, Status (sauber/beobachten/auffällig); aufklappbar alle verknüpften Belege mit Art, Grund, Menge und Wert.',
    fragen: ['Sind wir beim Kunden „sauber"?', 'Wie hoch ist die Retourengutschriftquote (> 55 %?)', 'Wie viel Wertgutschrift gab es ohne Absatzänderung?'],
    lesehilfe: 'Rote Retourenquote > 55 % = genauer prüfen. Zeile aufklappen zeigt alle Belege über mehrere Versendungen.', quelle: 'Gutschrift-/Retourenbelege + Auftragsdaten (Demo).' },
  prozesskette: { zweck: 'Vertriebs-Funnel Angebot -> Umsatz als Flussgrafik: ANGE -> AE -> AEB -> AET -> Umsatzerloese mit Abgaengen je Stufe (verlorene/offene Angebote, Stornos, nicht fakturiert).', zielgruppe: 'Vertrieb / Vertriebscontrolling / GF.', mehrwert: 'Sieht sofort, wo im Funnel Potenzial verloren geht.' },
  vertriebkpi: { zweck: 'Vertriebskennzahlen-Taxonomie in sechs Phasen (Angebot, Auftragseingang, Verwertung, Bearbeitung, Qualitaet, Umsatz) mit Fach-Codes und Symbol-Legende. AEW entfaellt, OAU = Auftragsbestand.', zielgruppe: 'Vertrieb / Vertriebscontrolling.', mehrwert: 'Einheitliches Verstaendnis der Vertriebskennzahlen entlang des Funnels.',
    inhalt: 'Je Phase die Fach-Codes mit Wert: ANGE/OANG/VANGE; AE/AEB/AEOA/STORAE/SAEOA; AET/NFA; OAU/RET; Storno-/Angebotsverlust-/Auftragsstorno-%; UMS/ARTUMS/VUMS/KG/ABS/VKM und Ø-Kennzahlen. Abgeleitete Werte mit Formel-Hinweis.',
    fragen: ['Was bedeutet welcher Vertriebs-Code genau?', 'Wie hängen AE, AEB und AET zusammen?', 'Welche Phase verliert am meisten?'],
    lesehilfe: 'Symbole: Σ wertbasiert (€), ◊ mengenbezogen, % Verhältnis, Ø Schnitt. Hover über eine Zeile zeigt die Formel.', quelle: 'Vertriebs-Kennzahlenmodell (Demo).' },
  abgleichabsatz: {
    zweck: 'Abgleich Absatzmenge vs. Auftragseingang tatsächlich (AET): fakturierte Absatzmenge (aus Rechnungspositionen) gegen AET aus dem WaWi je Produkt — mit Differenz abs/% und wahrscheinlicher Ursache.',
    inhalt: 'Abgleich-Tabelle (Produkt, AET-Menge, Absatz-Menge, Differenz abs/%, Ursachen-Chip), Ursachen-Kategorien (Teillieferung, Storno, Periodenverschiebung, Nachfakturierung), Zeitverlauf je Produkt, Drill auf Einzelauftrag.',
    zielgruppe: 'Vertriebscontrolling, Controlling, Auftragsmanagement.',
    mehrwert: 'Erkennt früh, wenn Absatz und Auftragseingang auseinanderlaufen — wichtig für Umsatzsteuerung, Planungsqualität und Lagerkoordination. Ersetzt manuelle Excel-Abgleiche.',
    fragen: ['Wo gibt es große Abweichungen zwischen AET und fakturiertem Absatz?', 'Sind die Abweichungen durch Teillieferungen erklärbar?', 'Gibt es systematische Periodenverschiebungen bei bestimmten Produkten?', 'Wie hoch ist die Stornoquote je Produkt?'],
    lesehilfe: 'Differenz > 5 % = prüfenswert. Ursachen-Chip zeigt häufigste Erklärung (algorithmisch). Drill → Einzelaufträge mit Status und Lieferdaten.',
    quelle: 'WaWi (AET, Auftragsstatus), Finanzbuchhaltung (Rechnungspositionen/Absatz); Demo-Daten (Mock).'
  },
  lieferant: {
    zweck: 'Lieferanten-Lebenszyklus und Risiko-Cockpit: Einkaufsvolumen, Liefertreue, Qualität (Reklamationsquote) und Abhängigkeitsrisiko je Lieferant — mit Lifecycle-Phasen (Neuzugang/Kernlieferant/Problemlieferant/Auslaufend).',
    inhalt: 'Lieferanten-Rangliste (Volumen/Liefertreue/Qualität), Lifecycle-Matrix (Treue × Qualität), ABC-Lieferanten, Klumpenrisiko-Analyse (Anteil > 20 % = kritisch), Reklamations-Trend, Preisindex je Lieferant, Eskalations-Log.',
    zielgruppe: 'Einkauf, Einkaufsleitung, Supply-Chain-Management.',
    mehrwert: 'Macht die Qualität der Lieferantenbasis messbar und priorisiert Verhandlungs- und Entwicklungsmaßnahmen: Kernlieferanten halten, Problemlieferanten reduzieren, Klumpenrisiken abbauen.',
    fragen: ['Welcher Lieferant hat die schlechteste Liefertreue?', 'Wo liegt ein Klumpenrisiko (> 20 % Anteil)?', 'Wie entwickelt sich die Reklamationsquote bei Lieferant X?', 'Welche Lieferanten sind im Lifecycle "Auslaufend"?', 'Wie hat sich der Preisindex verändert?'],
    lesehilfe: 'Klumpenrisiko-Grenze: kein Lieferant > 30 % Einkaufsvolumen (Richtwert). Rote Liefertreue < 85 %. Lifecycle-Ampel: Neu/Kern = grün, Problem = rot, Auslaufend = grau.',
    quelle: 'Wareneingänge, Reklamationserfassung, WaWi/ERP (Lieferantenkonditionen); Demo-Daten (Mock).'
  },
  auftrag: {
    zweck: 'Order-to-Cash-Lebenszyklus: vom Auftragseingang über Produktion, Lieferung und Rechnungsstellung bis zum Zahlungseingang — mit Engpassanalyse und Durchlaufzeit-Drill.',
    inhalt: 'Phasenverlauf (AE → Bestätigung → Produktion → Versand → RE → Zahlung), Durchlaufzeiten je Phase (Ist/Plan/Abweichung), Engpassanalyse (häufigste Verzögerungsphase), Offene Aufträge (Backlog), Storno-Rate, Zahlungsverzug, Top-Kunden nach Durchlaufzeit.',
    zielgruppe: 'Vertrieb, Auftragsmanagement, Finanzen / Debitoren.',
    mehrwert: 'Zeigt, wo im Order-to-Cash-Prozess Zeit und Geld verloren geht — Basis für gezielte Prozessverbesserung und Cashflow-Beschleunigung.',
    fragen: ['Wo dauert der O2C-Prozess am längsten?', 'In welcher Phase liegen die meisten offenen Aufträge?', 'Wie hoch ist die Storno-Rate und warum?', 'Welche Kunden zahlen am langsamsten?', 'Wie entwickelt sich der Auftrags-Backlog?'],
    lesehilfe: 'Durchlaufzeit-Balken: grün = unter Plan, rot = über Plan. Klick auf Phase → Einzelauftrags-Drill. DSO = Days Sales Outstanding (Ø Tage bis Zahlungseingang).',
    quelle: 'WaWi (Auftragsstatus), Finanzbuchhaltung (Rechnungs-/Zahlungsdate), Produktionsplanung; Demo-Daten (Mock).'
  },
  forderungen: {
    zweck: 'Forderungs-Aging: überfällige Rechnungen nach Fälligkeitsklassen (< 30 / 30–60 / 60–90 / > 90 Tage), DSO-Kennzahl und Ausfallrisiko-Scoring je Debitor.',
    inhalt: 'Aging-Tabelle (alle offenen Forderungen nach Fälligkeitsklasse und Schuldner), DSO (Days Sales Outstanding) im Zeitverlauf, Risikoklassen-Ampel je Kunde, Zahlungsverhalten-Trend, Mahnstufen-Status, Drill auf Einzelrechnung.',
    zielgruppe: 'Finanzen, Debitorenmanagement, Risikomanagement, Controlling.',
    mehrwert: 'Verhindert Liquiditätsengpässe durch frühzeitiges Erkennen von Zahlungsverzug und schützt vor Forderungsausfällen durch rechtzeitige Eskalation — mit priorisierten Handlungsempfehlungen.',
    fragen: ['Welche Rechnungen sind mehr als 60 Tage überfällig?', 'Wie hoch ist unser DSO im Vergleich zum Zahlungsziel?', 'Welche Kunden haben ein hohes Ausfallrisiko?', 'Wie hoch sind die Forderungen insgesamt in jeder Klasse?', 'Wo läuft ein Mahnverfahren?'],
    lesehilfe: 'Rot = > 90 Tage überfällig, sofort Mahnstufe 3/Inkasso prüfen. Orange = 60–90 Tage, Mahnschreiben senden. DSO > Zahlungsziel = struktureller Zahlungsverzug.',
    quelle: 'Debitorenbuchhaltung (offene Posten), CRM (Kundenkontakte), Scoring-Modell (Demo); Demo-Daten (Mock).'
  },
  // ---- Analyse & Steuerung ----
  bi: {
    zweck: 'Self-Service-BI: freie Ad-hoc-Auswertungen ohne IT-Anfrage — Dimensionen, Maße und Zeiträume frei kombinierbar, Ergebnis sofort als Tabelle oder Visual.',
    inhalt: 'Dimension-/Maß-Auswahl (Drag & Drop oder Chips), Zeitraum-Picker, Pivot-Tabelle und Chart-Umschalter (Balken/Linie/Donut), Filter (mehrfach, stapelähnlich), Ergebnis-Export (CSV/Excel), gespeicherte Ansichten (Bookmarks), KI-Abfrage in Klartext.',
    zielgruppe: 'Controller:innen, Bereichsleitung, Vertrieb/Einkauf — alle, die Fragen haben, die kein vorbereiteter Bericht beantwortet.',
    mehrwert: 'Keine IT-Anfrage, kein Warten: Fragen direkt beantwortet. Stärkt die Datenkompetenz im Unternehmen und entlastet das Controlling von Routineanfragen.',
    fragen: ['Was war unser Umsatz je PLZ im Q2?', 'Welcher Vertriebsmitarbeiter hat welche Warengruppen verkauft?', 'Wie entwickeln sich die Einkaufspreise bei Lieferant X je Monat?', 'Welche Kunden haben mehrfach storniert?'],
    lesehilfe: 'Links Dimensionen, oben Maße ziehen. Zeitraum-Chip unten setzt den Filter. „Speichern" legt eine wiederverwendbare Ansicht an. KI-Abfrage: einfach die Frage eintippen.',
    quelle: 'Alle verfügbaren Datentöpfe der Anwendung (je nach freigegebenen Bereichsrechten); Demo-Daten (Mock).'
  },
  abweichung: {
    zweck: 'Plan/Ist-Abweichungsanalyse: Gesamtabweichung in Preis-, Mengen- und Struktureffekt zerlegen — für Umsatz, Kosten und Ergebnis.',
    inhalt: 'Abweichungsübersicht (Umsatz/Kosten/DB/EBIT je Bereich), Preiseffekt (Preisänderung × Ist-Menge), Mengeneffekt (Plan-Preis × Mengenänderung), Struktureffekt (Mix-Shift), Drill bis auf Artikel/Kostenstelle, Monatsverlauf, Kommentar-Feld.',
    zielgruppe: 'Controlling, Bereichsleitung, Geschäftsführung.',
    mehrwert: 'Beantwortet die entscheidende Controllingfrage: Liegt die Abweichung am Preis, am Volumen oder am Mix? — und zeigt damit den richtigen Hebel für Gegenmaßnahmen.',
    fragen: ['Warum weicht das Ergebnis vom Plan ab?', 'Ist die Abweichung preis- oder volumengetrieben?', 'Welcher Bereich/Artikel verursacht die Abweichung?', 'Hat sich der Produkt-Mix verschoben?', 'In welchem Monat begann die Abweichung?'],
    lesehilfe: 'Preiseffekt = Preis gesunken/gestiegen. Mengeneffekt = Volumen unter/über Plan. Struktureffekt = Anteil margenschwacher Produkte gestiegen. Alle drei addieren zur Gesamtabweichung.',
    quelle: 'Planung (Budget), Finanzbuchhaltung (Ist), Kostenrechnung; Demo-Daten (Mock).'
  },
  vergleich: { zweck: 'Versionsvergleich (Plan/Forecast/Ist).', zielgruppe: 'Controlling.', mehrwert: 'Stände sauber gegenüberstellen.' },
  qc: {
    zweck: 'Datenqualitäts-Dashboard und Querchecks: automatische Plausibilitätsprüfungen, Abstimmkontrollen und Vollständigkeitsprüfungen über alle Datentöpfe.',
    inhalt: 'Prüfregeln-Übersicht (aktiv/deaktiviert), Prüfergebnis-Tabelle (Regel, Bereich, Status, Fundstellen), Zeitverlauf Fehleranzahl, Drill bis auf Einzelsatz, Manuelle Ausnahmen dokumentieren, Export Fehlerliste.',
    zielgruppe: 'Controlling, Rechnungswesen, IT-Datenmanagement.',
    mehrwert: 'Erkennt Datenfehler bevor sie ins Reporting einfließen: Doppelbuchungen, Lücken, Plausi-Verstöße, unabgestimmte Summen — mit direktem Drill auf den Fehlerdatensatz.',
    fragen: ['Welche Prüfregeln schlagen derzeit an?', 'Wie viele Fehler wurden in letzter Zeit gefunden?', 'Gibt es wiederkehrende Fehler bei bestimmten Quellen?', 'Sind alle Abstimmkontrollen grün?'],
    lesehilfe: 'Rote Prüfregel = Fehler gefunden, sofort ansehen. Gelb = Warnung (Wert außerhalb Toleranz). Grün = Prüfung bestanden. Anzahl offener Fehler oben rechts.',
    quelle: 'Alle angebundenen Datentöpfe (FiBu, WaWi, HR, ERP); Demo-Daten (Mock).'
  },
  abstimmung: {
    zweck: 'Abstimmbrücken zwischen Finanzbuchhaltung (FiBu) und Controlling: Überleitung von Buchhaltungsergebnis zum Betriebsergebnis — mit Differenzanalyse je Abstimmposten.',
    inhalt: 'Abstimmtabelle (FiBu-Ergebnis → Neutrale/Kalk. Posten → Betriebsergebnis), Differenz je Abstimmposten (Plan/Ist), Warnmeldungen bei unerwarteten Differenzen, monatlicher Abstimmstatus (freigegeben/offen), Kommentarfeld.',
    zielgruppe: 'Rechnungswesen, Controlling, Wirtschaftsprüfung.',
    mehrwert: 'Stellt die Datenqualität sicher: Jede Differenz zwischen FiBu und Controlling ist dokumentiert und begründet — kein Rätselraten beim Jahresabschluss.',
    fragen: ['Wo gibt es ungeklärte Differenzen zwischen FiBu und Controlling?', 'Sind alle Abstimmposten freigegeben?', 'Wie hoch ist der neutrale Ergebnisanteil?', 'Welche Monate sind noch nicht abgestimmt?'],
    lesehilfe: 'Grün = Abstimmung freigegeben. Gelb = Differenz vorhanden, Erklärung ausstehend. Rot = kritische Differenz, sofort klären. Differenz > Toleranzgrenze triggert Warnung.',
    quelle: 'Finanzbuchhaltung (DATEV/SAP), Kostenrechnung; Demo-Daten (Mock).'
  },
  lebenszyklus: {
    zweck: 'Produkt- und Kunden-Lebenszyklus: klassische Phasenkurve (Einführung/Wachstum/Reife/Sättigung/Rückgang) mit BCG-Blasen und Kundenbindungs-Phasen — inklusive Nachfolger-Verkettung.',
    inhalt: 'Produkte: Lebenszyklus-Kurve (Phasenbänder + Umsatzkurve), BCG-Blasen je Phase (Größe = Umsatz), Matrix/Kurve-Umschalter, Nachfolger-Verkettung (Vorgänger→Nachfolger kombinieren). Kunden: Beziehungskurve (5 Phasen: Neukundenphase → Stammkunde → Churn-Risiko → inaktiv → reaktiviert), Drill auf Einzelkunde.',
    zielgruppe: 'Vertrieb, Marketing, Produktmanagement, Controlling.',
    mehrwert: 'Zeigt, wo Produkte und Kunden im Lifecycle stehen — und welche Maßnahmen phasenbezogen greifen: Neueinführung, Umsatzmaximierung, Lifecycle-Verlängerung oder geordneter Auslauf.',
    fragen: ['In welcher Phase ist unser umsatzstärkstes Produkt?', 'Wie viele Produkte sind im Rückgang?', 'Welche Kunden sind Churn-Risiko?', 'Gibt es einen Nachfolger für das auslaufende Modell?', 'Wie entwickelt sich die Phasenverteilung über Quartale?'],
    lesehilfe: 'Blasengröße = Umsatz. Farbe = Phase. Klick auf Blase → Artikel- oder Kundenkarte. Toggle „Nachfolger kombinieren" zeigt durchgängige Produktlinien trotz Artikelnummerwechsel.',
    quelle: 'Absatzdaten, Stammdaten (Vorgänger-Feld), Kundendaten (WaWi/CRM); Demo-Daten (Mock).'
  },
  pckostenstellen: { zweck: 'Bricht jedes Profit-Center bis auf die Einzelkostenstelle herunter und erlaubt das manuelle Verschieben einzelner Kostenstellen in ein anderes Profit-Center.', inhalt: 'PC-Karten mit Erlös/Kosten/Ergebnis, aufklappbar bis zur Kostenstelle; je Kostenstelle ein Auswahlfeld zum Umhängen. Live-Neuberechnung, Markierung verschobener Stellen, Zurücksetzen.', zielgruppe: 'Controlling, Bereichs-/Profit-Center-Leitung.', mehrwert: 'Schafft die bisher fehlende Ebene PC → Kostenstelle und macht Verantwortungs-/Ergebniszuordnung transparent und korrigierbar — ohne dass das Unternehmensergebnis kippt.', fragen: ['Aus welchen Kostenstellen besteht ein Profit-Center?', 'Welche Stelle macht ein PC defizitär?', 'Wie ändert sich das PC-Ergebnis, wenn eine Stelle umgehängt wird?'], lesehilfe: 'Σ Erlöse/Kosten bleiben beim Verschieben konstant — nur die Verteilung auf die PC ändert sich. Rote Ergebnisse = Verlust.', quelle: 'Kostenstellenrechnung (BAB); Demo-Daten (Mock).' },
  kontenstrukturen: { zweck: 'Mehrere parallele Sachkonto-Hierarchien über denselben Kontenstamm: GuV-Struktur, ROI-/DuPont-Baum und Kostenarten (variabel/fix mit DB-Schema).', inhalt: 'Umschaltbare Bäume, die aus dem Kontenstamm hochrollen; Konten können in mehreren Bäumen vorkommen („auch in …"). Aufklappbar bis zum Einzelkonto mit Kontonummer.', zielgruppe: 'Controlling, Bilanzbuchhaltung, Geschäftsführung.', mehrwert: 'Ein Konto, je nach Fragestellung anders gegliedert — z. B. Umsatz im GuV-, ROI- und DB-Baum — ohne die Kontierung zu ändern.', fragen: ['Wie setzt sich das Ergebnis nach Gesamtkostenverfahren zusammen?', 'Wie zerlegt sich der ROI (Umsatzrendite × Kapitalumschlag)?', 'Wie hoch ist der Deckungsbeitrag (variabel/fix)?'], lesehilfe: 'Summenknoten rollen ihre Kinder hoch (− = Aufwand); Formelknoten (ROI/Umsatzrendite/Kapitalumschlag) zeigen Kennzahlen in % bzw. ×.', quelle: 'Sachkontenstamm (SKR-nah); Demo-Daten (Mock).' },
  berichtlog: { zweck: 'Zugriffs-Log je Bericht: wie viele Personen zugegriffen haben, Aufrufe (pro Tag/User einmal), Ersteller und Bearbeiter mit Datum, Direkt-Link. Admin-Aufrufe zählen nicht.', zielgruppe: 'Administratoren.', mehrwert: 'Nutzung der Berichte transparent machen — was wird genutzt, von wie vielen, seit wann; mit Direkt-Link.' },
  kisteuerung: { zweck: 'Zentraler Schalter, ob KI im Reporting genutzt wird, plus Betriebsmodus (lokal/On-Premise, Private Cloud, extern) und Datenfreigabe-Stufe.', zielgruppe: 'Administratoren.', mehrwert: 'Volle Kontrolle über KI und Datensouveränität — Firmendaten bleiben im Haus; KI lässt sich jederzeit abschalten.' },
  kibuilder: { zweck: 'KI-gestützter Report-Builder: vorhandene Kennzahlen auswählen, die KI schlägt passende Darstellungen vor, per Knopfdruck entsteht ein Berichtsentwurf.', inhalt: 'Datenkatalog-Auswahl, KI-Visualisierungsvorschläge mit Kurz-Insight, Duplikat-Check (ähnliche vorhandene Berichte), persönlicher Ordner mit Teilen (Bericht/Ordner), Entdecken-Bereich und globale Berichte.', zielgruppe: 'Alle Berichtsersteller.', mehrwert: 'Schnell zu einem Bericht — ohne Doppelarbeit, mit Teilen und kuratierten globalen Vorlagen.' },
  datenschutz: { zweck: 'Datenschutz & Sicherheit: Datenklassifizierung, Maskierung personenbezogener Daten in dev/test, Object-/Row-Level-Security und DSGVO-Checkliste.', zielgruppe: 'Administratoren / Datenschutz / Compliance.', mehrwert: 'Sensible & personenbezogene Daten rechtssicher absichern (DSGVO), Zugriffe je Rolle/Zeile steuern und außerhalb der Produktion keine echten Personendaten zeigen.' },
  datenmodell: { zweck: 'Feld-Mapping: Spalten der SQL-Quelltabellen (Dim*/Fact*) per Drag & Drop den von den Berichten erwarteten Feldern zuweisen.', inhalt: 'Quelltabellen mit ziehbaren Spalten, Report-Felder als Drop-Ziele, Validierung (Pflicht grün/rot, Fortschritt %), Liste einsatzbereiter Berichte mit Test/Aktivieren-Buttons.', zielgruppe: 'Administratoren / Data Engineering.', mehrwert: 'Berichte schrittweise an echte Quellen anbinden; Pflichtfelder absichern, optionale leer lassen (Kennzahl ausgeblendet), und grüne Berichte direkt ausrollen.' },
  berichtfreigabe: { zweck: 'Admin-Steuerung der Berichts-Sichtbarkeit: je Bericht Status setzen (Aktiv / Test / Deaktiviert) und für „Test" einzelne Testuser freigeben.', zielgruppe: 'Administratoren.', mehrwert: 'Berichte gezielt ausrollen: erst im Test mit ausgewählten Usern, dann aktiv — oder vorübergehend deaktivieren, ohne Code-Änderung.' },
  bestandsentwicklung: { zweck: 'Lagerbestandsentwicklung je Warenbereich: Verlauf, Reichweite (DIO), Zielbestand & Frist und ob das aktuelle Abverkaufstempo reicht — sonst KI-Maßnahmen zur Gegensteuerung.', inhalt: 'Übersichts-KPIs (Gesamtbestand, Überbestand, Ø Reichweite, kritische Bereiche), je Warenbereich Verlauf-Sparkline, Reichweiten-Ampel, Prognose und KI-Maßnahmen (per Klick als Maßnahme übernehmbar).', zielgruppe: 'Disposition, Einkauf, Vertrieb, Controlling.', mehrwert: 'Überbestände/Ladenhüter früh erkennen und mit konkreten Maßnahmen den Zielbestand fristgerecht erreichen; Kapital freisetzen.', fragen: ['Wo bauen sich Überbestände auf?', 'Reicht das Abverkaufstempo, um das Ziel in der Frist zu erreichen?', 'Welche Gegenmaßnahmen schlägt die KI vor?'], lesehilfe: 'Reichweite-Ampel: grün ~30–60 Tg, gelb erhöht, rot Unter-/Überbestand. „Frist verfehlt" = nötiger Mehr-Abverkauf in %.', quelle: 'Lager-/WaWi-Bestände + Abgänge; Demo-Daten (Mock).' },
  datenquellen: { zweck: 'Kuratierte, erweiterbare Linksammlung externer Datenquellen: Marktanteile/Branchenstatistik (Bike), Geo-/PLZ-/Einwohner-/Flächendaten, Wettbewerbs-Benchmark, E-Commerce und Mobilität/Trends.', inhalt: 'Quellen-Karten mit Link, Beschreibung, Kosten-Badge und Tags; Filter nach Kategorie, Suche, Hinzufügen/Bearbeiten/Löschen.', zielgruppe: 'Controlling, Marketing, Vertrieb, Markt-/Datenanalyse.', mehrwert: 'Schneller Zugang zu echten Markt-/Geodaten (ZIV, CONEBI, Destatis, BKG, suche-postleitzahl.org …) für Marktanteils- und Potenzialanalysen — an einem Ort, pflegbar.' },
  google: { zweck: 'Google Ads & Analytics als Reporting, abgeglichen mit den Echtdaten: Marketing-Performance (Kosten/ROAS/CPA), GA4-Conversion-Funnel, Cross-Selling und der Attributions-Abgleich Google ↔ WaWi.', inhalt: 'Kampagnen-Tabelle (Impr./Klicks/CTR/CPC/Conv./ROAS), Funnel mit Conversion-Raten und Kanal-Split, Differenz Google-Conversion-Wert vs. Echtumsatz, Cross-Selling-Empfehlungen.', zielgruppe: 'Marketing, Vertrieb, Controlling.', mehrwert: 'Online-Marketing nach echtem Umsatz steuern (nicht nach überzeichneten Google-Zahlen) und Cross-Selling-Potenzial heben.', fragen: ['Welche Kampagne bringt echten ROAS?', 'Wo bricht der Funnel ab?', 'Wie stark überzeichnet Google ggü. den Echtdaten?', 'Welche Produkte zusammen bewerben?'], lesehilfe: 'ROAS = Umsatz je € Werbung (grün ≥ 10, gelb ≥ 4). Maßgeblich ist der Echtumsatz, nicht der Google-Conversion-Wert.', quelle: 'Google Ads & GA4 (Drittland USA, SCC nach Art. 44 ff. DSGVO); Abgleich mit WaWi/Vertrieb. Demo-Daten (Mock).' },
  versand: { zweck: 'Versanderlöse (vom Kunden berechnet) gegen die tatsächlichen Versandkosten (Carrier): Über-/Unterdeckung gesamt und je Gewichtsklasse, Carrier und Region, plus Retouren-Versandkosten.', inhalt: 'KPIs (Erlöse, Kosten, Deckung, Quote, Retouren-Versand, Netto), Erlös-Kosten-Balken je Gewichtsklasse, Carrier- und Regionsvergleich, Retouren-Auswertung. Kernbefund-Box mit Hebeln.', zielgruppe: 'Controlling, Logistik, E-Commerce-Leitung.', mehrwert: 'Macht die oft versteckte Unterdeckung im Versand sichtbar (Gratis-Bike-Versand, Gratis-Retouren) und zeigt, wo Freigrenze, Zuschläge oder Carrier-Nachverhandlung ansetzen.', fragen: ['Decken die berechneten Versanderlöse die echten Kosten?', 'Welche Gewichtsklasse/Carrier/Region ist unterdeckt?', 'Was kosten uns Gratis-Versand und Retouren?'], lesehilfe: 'Deckungsquote = Erlöse ÷ Kosten: grün ≥ 100 %, gelb ≥ 80 %, rot darunter. Bike/Sperrgut und Retouren sind die Verlusttreiber.', quelle: 'Carrier-Abrechnungen vs. berechnete Versandkosten (Shop/WaWi); Demo-Daten (Mock).' },
  leasing: { zweck: 'Leasing-Cockpit mit vier Sichten: gezahlte Leasinggebühren (Leasingnehmer), Leasing-vs-Kauf-Vergleich, IFRS-16-Bilanzsicht und Dienstrad-Leasing als eigener Anbieter.', inhalt: 'Verträge je Objekt (Rate, Restlaufzeit, Restwert, Fälligkeiten), Vorteilhaftigkeitsvergleich mit Empfehlung, Right-of-Use-Asset & Leasingverbindlichkeit (HGB↔IFRS-Effekt), Dienstrad-Portfolio (Erlöse, Restwerte, Ausfallrisiko, Segmente).', zielgruppe: 'Controlling, Finanzen, Einkauf/Fuhrparkleitung.', mehrwert: 'Transparenz über die gesamten Leasingkosten, fundierte Make-or-Buy-Entscheidung, korrekte Bilanzierung und Steuerung des eigenen Dienstrad-Geschäfts.', fragen: ['Was zahlen wir insgesamt für Leasing (p. a. / Restlaufzeit)?', 'Lohnt sich Leasing oder Kauf je Objekt?', 'Wie wirkt IFRS 16 auf Bilanz und EBITDA?', 'Wie entwickelt sich unser Dienstrad-Portfolio?'], lesehilfe: 'Gelb hinterlegte Verträge laufen < 12 Monate aus (Anschlussbeschaffung). Vorteil Leasing > 0 = Leasing günstiger.', quelle: 'Leasingverträge/Fuhrparkverwaltung, WaWi (Dienstrad); Demo-Daten (Mock).' },
  finanzcockpit: { zweck: 'Finanz- & Risiko-Cockpit: Bilanz-, Liquiditäts-, Rentabilitäts- und Risikokennzahlen, konsistent aus einer Datenbasis (Bilanz/GuV/Cashflow) abgeleitet.', inhalt: 'Risikobild (Ampelverteilung), Bilanzstruktur (Aktiva/Passiva), je Kennzahl Wert, Ampel, Zielband, Formel, Standard-Bezug und Deutung. Druck-/PDF-fähig.', zielgruppe: 'Geschäftsführung, Leitung Controlling/Finanzen, Banken.', mehrwert: 'Standardkonforme Finanzanalyse auf einen Blick — zeigt Stabilität, Liquiditätslage, Ertragskraft und Risiken mit klaren Zielbändern.', fragen: ['Wie solide ist die Kapitalstruktur (EK-Quote, Anlagendeckung)?', 'Sind wir jederzeit zahlungsfähig (Liquiditätsgrade, CCC)?', 'Verdienen wir genug (Marge, ROCE, ROE)?', 'Wo sind die Risiken (Zinsdeckung, Verschuldung)?'], lesehilfe: 'Ampel je Kennzahl nach Zielband: grün = im Zielkorridor, gelb = Beobachtung, rot = Handlungsbedarf. Richtung „hoch/tief" je Kennzahl beachtet.', quelle: 'HGB-Bilanzanalyse, IFRS-KPIs (ROCE, EBITDA, IAS 7), Working-Capital-Mgmt, Risiko-Frühaufklärung (KonTraG). Demo-Daten (Mock).' },
  quartalsbericht: { zweck: 'Management-/Quartalsbericht: Umsatz Ist/Plan/Vorjahr (gesamt, Fahrräder, Teile/Bekleidung/Zubehör) mit kumulierten Verläufen, Online↔Offline, Internationalisierung, Benchmark/Marktanteil, Durchschnittspreisen und Auftragseingang — je Abschnitt mit Kernaussage und editierbarer Bemerkung.', inhalt: 'Kernaussage + Management-Summary, KPI-Kacheln, Ist/Plan/VJ-Tabelle je Monat + YTD, Linien-/Balkencharts, Preis- und Auftragseingangs-Sektion. Filter nach Zeitraum/Quartal und Profit-Center/Kanal. Druck-/PDF-fähig.', zielgruppe: 'Geschäftsführung, Controlling, Vertriebsleitung.', mehrwert: 'Ein konsolidierter, präsentationsreifer Bericht statt vieler Einzelfolien — mit klarer Kernaussage und dokumentierten Bemerkungen je Thema.', fragen: ['Wo stehen wir gegen Plan und Vorjahr (YTD/Quartal)?', 'Wie entwickeln sich Online vs. stationär und die Auslandsmärkte?', 'Wie ist unsere Marktposition (Benchmark/Marktanteil)?', 'Was sind Ursachen und Gegenmaßnahmen?'], lesehilfe: 'Ampel je Abschnitt: grün = im/über Plan, gelb = leicht darunter (≥ −5 %), rot = deutlich darunter. Zahlen in der Tabelle in TEUR.', quelle: 'Demo (Mock); später aus FiBu/Vertrieb (Ist/Plan), ZIV/Marktdaten (Benchmark), WaWi (Auftragseingang).' },
  portfoliobcg: { zweck: 'Boston-Consulting-Portfolios (Stars / Cash Cows / Question Marks / Poor Dogs) über Produkte, Kunden, Vertriebskanäle, Regionen und Lieferanten — Achsen Wachstum/Dynamik × Deckungsbeitrag/Performance, Blasengröße = Volumen.', inhalt: 'Je Sicht eine Matrix mit vier Feldern, Quadranten-Karten mit fachlicher Handlungsempfehlung, anklickbarem Quadranten-Filter und Detailtabelle.', zielgruppe: 'Geschäftsführung, Controlling, Vertriebs-/Einkaufsleitung.', mehrwert: 'Macht aus „viel Umsatz" eine klare Investitions-/Steuerungsentscheidung je Objekt: investieren, halten/melken, entwickeln oder bereinigen — statt Gießkanne.', fragen: ['Wo investieren wir in Wachstum (Stars)?', 'Was trägt heute den Gewinn (Cash Cows)?', 'Welche Wetten fördern, welche einstellen (Question Marks)?', 'Was bindet Kapital ohne Ertrag (Poor Dogs)?'], lesehilfe: 'Rechts oben = Stars, links oben = Cash Cows, rechts unten = Question Marks, links unten = Poor Dogs. Schwellen je Achse = Median.', quelle: 'Demo: Umsatz/DB/Wachstum je Objekt; später aus Vertriebs-, Kunden- und Einkaufsdaten.' },
  lzempfehlung: {
    zweck: 'Automatische Lifecycle-Empfehlungen: KI-gestützte Handlungsempfehlungen je Produkt und Kunde basierend auf der aktuellen Lebenszyklusphase.',
    inhalt: 'Empfehlungskarten je Artikel/Kunde (Phase, Risikobewertung, 2–3 konkrete Maßnahmenvorschläge, Priorität), Filter nach Phasen/Dringlichkeit/Bereich, direkter Sprung in Artikelkarte oder Kundenprofil, Maßnahmen-Export, KI-Konfidenzniveau.',
    zielgruppe: 'Vertrieb, Produktmanagement, Controlling.',
    mehrwert: 'Übersetzt Lifecycle-Daten direkt in Handlungsoptionen — kein manuelles Interpretieren nötig. Priorisiert nach Umsatz-Impact, damit das Team mit dem Wichtigsten anfängt.',
    fragen: ['Welche Produkte brauchen sofort Maßnahmen?', 'Welche Kunden sind churn-gefährdet?', 'Welche Empfehlungen haben den höchsten Umsatz-Impact?', 'Wurden Empfehlungen bereits umgesetzt?'],
    lesehilfe: 'Rot = hohes Risiko (Churn/Auslauf), Gelb = Beobachtung, Grün = Wachstumspotenzial. KI-Konfidenz gibt an, wie verlässlich die Empfehlung ist (> 75 % = verlässlich).',
    quelle: 'Lebenszyklus-Analyse, Absatzdaten, Kundenkontakte; KI: regelbasiert + statistisch; Demo-Daten (Mock).'
  },
  anlagen: {
    zweck: 'Anlagen-Lebenszyklus und kalkulatorische Abschreibung: Anschaffungskosten, Nutzungsdauer, Buchwert, AfA-Plan und der Unterschied zur kalkulatorischen Abschreibung (Wiederbeschaffungswert).',
    inhalt: 'Anlagespiegel (Zugänge/Abgänge/Umbuchungen), HGB-AfA vs. kalk. Abschreibung je Anlage, Buchwert-Entwicklung (Zeitverlauf), fällige Ersatzbeschaffungen (Ampel), Leasing vs. Kauf je Objekt, IFRS-16-Pflicht.',
    zielgruppe: 'Finanzen, Controlling, Einkauf/Fuhrpark.',
    mehrwert: 'Zeigt den echten Werteverzehr der Anlagen (kalk. Abschr.) im Vergleich zum steuerlichen (HGB) — Grundlage für Investitionsplanung, Ersatzbeschaffung und Kostenträgerrechnung.',
    fragen: ['Welche Anlagen laufen bald aus und müssen ersetzt werden?', 'Wie hoch ist die kalk. Abschreibung vs. HGB-Abschreibung?', 'Welche Anlagen sind schon vollständig abgeschrieben aber noch in Betrieb?', 'Wie hoch ist der Buchwert der Produktionsanlagen?'],
    lesehilfe: 'Gelb = Nutzungsdauer < 1 Jahr. Rot = überschritten. kalk. Abschr. > HGB = höhere Rückstellungsnotwendigkeit für Ersatz.',
    quelle: 'Anlagenbuchhaltung (HGB), Versicherungswerte/Wiederbeschaffungspreise (für kalk.); Demo-Daten (Mock).'
  },
  technologie: {
    zweck: 'Technologie-Reifegrad (TRL) und F&E-Portfolio: Innovationspipeline, Entwicklungsbudgets, Time-to-Market und Patente — nach Produktkategorie und Reifegradstufe.',
    inhalt: 'TRL-Matrix (Technology Readiness Level 1–9 nach NASA/EU-Standard), F&E-Budget-Kacheln (Plan/Ist/VJ), Innovationspipeline (Idee → Konzept → Prototyp → Markt), Patentübersicht, Time-to-Market-Benchmark, F&E-Quote (% des Umsatzes).',
    zielgruppe: 'Geschäftsführung, F&E-Leitung, Produktmanagement.',
    mehrwert: 'Schafft Transparenz über den Innovationsstatus: Welche Technologien sind marktreif? Wo werden F&E-Budgets eingesetzt? Was kommt als Nächstes?',
    fragen: ['Welche Technologien stehen kurz vor Marktreife (TRL 7–9)?', 'Wie hoch ist unsere F&E-Quote im Branchenvergleich?', 'Wo werden Entwicklungsbudgets überschritten?', 'Wie lang ist unsere Time-to-Market im Schnitt?'],
    lesehilfe: 'TRL 1–3 = Forschung (kein Umsatz in Sicht). TRL 4–6 = Entwicklung. TRL 7–9 = Serienreife/Markteinführung. F&E-Quote < 2 % = Innovationsrisiko.',
    quelle: 'F&E-Controlling, Patentdatenbank, Projektmanagement-Tool; Demo-Daten (Mock).'
  },
  mitarbeiter: {
    zweck: 'Mitarbeiter-Lebenszyklus (HR-Kennzahlen): Eintritt, Entwicklung, Bindung und Fluktuation — mit Dimension-Umschalter (Abteilung/Region/Altersgruppe) und Frühwarn-Indikatoren.',
    inhalt: 'HR-KPI-Band (Headcount, Fluktuation, Durchschnittsalter, Betriebszugehörigkeit, Krankenquote), Lifecycle-Phasen (Onboarding/Kernphase/Risikophase/Austritt), Alters-/Abteilungsverteilung, Dimension-Chips (Abt./Region/Alter), Trend-Monatsverlauf.',
    zielgruppe: 'HR, Personalcontrolling, Geschäftsführung.',
    mehrwert: 'Macht Personalstrategie messbar: Wo ist die Fluktuation zu hoch? Welche Abteilung blutet aus? Frühwarnsystem für Wissensverlust durch Rentenabgänge.',
    fragen: ['Wie hoch ist die Fluktuation je Abteilung?', 'Wo gibt es einen Altersberg (> 55 Jahre)?', 'Wie entwickelt sich der Krankenstand?', 'Wie lange dauert das Onboarding im Schnitt?', 'Welche Abteilung hat das größte Renteneintrittsrisiko in 5 Jahren?'],
    lesehilfe: 'Fluktuation > 15 % p.a. = Warnsignal (Branchenmittel ca. 8 %). Krankenquote > 5 % = Handlungsbedarf. Lifecycle-Phase „Risiko" = Bindungsmaßnahme prüfen.',
    quelle: 'HR-/Personalabrechnungssystem, Fehlzeitenerfassung; Demo-Daten (Mock).'
  },
  massnahmen: { zweck: 'Maßnahmen-Nachverfolgung (SMART, mit Owner/Frist).', zielgruppe: 'Alle Führungskräfte.', mehrwert: 'Vom Bericht zur umgesetzten Maßnahme.' },
  instrumente: { zweck: 'Übersicht der Controlling-Instrumente.', zielgruppe: 'Controlling.', mehrwert: 'Das passende Instrument je Fragestellung.' },
  alerts: { zweck: 'Frühwarnungen bei kritischen Kennzahlen.', zielgruppe: 'Alle.', mehrwert: 'Rechtzeitig gegensteuern.' },
  zeit: { zweck: 'Zeit & Datenart umschalten (Ist/Plan/Forecast/Tagesreporting).', zielgruppe: 'Alle.', mehrwert: 'Berichte aus verschiedenen Datensichten lesen.' },
  // ---- Lernen & Wissen ----
  lernpfad: { zweck: 'Geführter Lernweg durch Controlling & Kostenrechnung.', zielgruppe: 'Neue Anwender, alle.', mehrwert: 'Wissen aufbauen, mit Quiz & Zertifikat.' },
  doku: { zweck: 'Durchsuchbares Wissens-/Doku-Nachschlagewerk.', zielgruppe: 'Alle.', mehrwert: 'Themen schnell nachlesen.' },
  controlling: { zweck: 'Controlling-Struktur & Teilgebiete.', zielgruppe: 'Alle / Einarbeitung.', mehrwert: 'Das Big Picture verstehen.' },
  klrablauf: { zweck: 'KLR-Ablauf als roter Faden mit echten Werten.', zielgruppe: 'Einarbeitung / Controlling.', mehrwert: 'Zusammenhänge der Kostenrechnung nachvollziehen.' },
  ablaufdiagramm: { zweck: 'Interaktives Prozess-/Ablaufdiagramm.', zielgruppe: 'Alle.', mehrwert: 'Prozesse klickbar verstehen.' },
  datenarchitektur: { zweck: 'Daten- & Performance-Architektur des Reportings: Schichten von der Quelle bis zum Browser, Sternschema, Profit-Center-Baum als Dimension, RLS/OLS-Sicherheit und ELT externer Daten.', zielgruppe: 'IT / Controlling-Leitung / Architektur.', mehrwert: 'Verstehen, wie das System über Millionen Datensätze schnell, konsistent und sicher bleibt — Begleitseite zu PERFORMANCE.md.',
    inhalt: 'Pipeline (Quellen → ELT → Sternschema → Pre-Aggregate → Sicherheit → Auslieferung → Browser), Sternschema-Visual mit conformten Dimensionen, tragende Prinzipien (Anzeige ≠ Datenmenge, eine Dimension/ein Filter, additiv vs. nicht-additiv, RLS-Pushdown, granulare Rohdaten) und Richtwerte.',
    fragen: ['Wie skaliert das auf Millionen Datensätze?', 'Wie wird über alle Berichte konsistent gefiltert und abgesichert?', 'Wie kommen Google-/Geo-/Marktdaten sauber hinein?'],
    lesehilfe: 'Von links nach rechts = Datenfluss; die zentrale Faktentabelle ist von ihren Dimensionen umgeben. DimProfitCenter ist derselbe Baum wie im PC-Filter.', quelle: 'Architektur-Leitlinie (Konzept), ausführlich in PERFORMANCE.md.' },
  // ---- Verwaltung ----
  abschluss: { zweck: 'Abschluss & Versionierung der Berichte.', zielgruppe: 'Rechnungswesen.', mehrwert: 'Sauberer, nachvollziehbarer Periodenabschluss.' },
  verteiler: { zweck: 'Geplanter, automatischer Versand von Berichten.', zielgruppe: 'Controlling / Assistenz.', mehrwert: 'Die richtigen Berichte automatisch verteilen.' },
  transport: { zweck: 'Transport von Berichten zwischen dev/test/prod.', zielgruppe: 'Admin / Power-User.', mehrwert: 'Berichte kontrolliert ausrollen.' },
  wizard: { zweck: 'Ersteinrichtung der Anwendung.', zielgruppe: 'Admin.', mehrwert: 'System sauber konfigurieren.' },
  admin: { zweck: 'Admin-Bereich: Logo, Themes, Branding.', zielgruppe: 'Admin.', mehrwert: 'Die App an Anlässe/Marke anpassen.' },
  nutzung: { zweck: 'Nutzungs-Statistik: Aufrufe, eindeutige & aktive User.', zielgruppe: 'Admin.', mehrwert: 'Das Reporting datenbasiert verbessern.' },
  rechte: { zweck: 'Rollen & Rechte verwalten (Bereiche, geschützte KPIs, Mitglieder).', zielgruppe: 'Admin.', mehrwert: 'Sichtbarkeit & Schutz zentral steuern.' },
  artikelkarte: {
    zweck: 'Vollständige Artikelkarte (Mini-ERP): alle relevanten Daten zu einem Artikel — Stammdaten, KPIs, Preis- und Absatzentwicklung, Lager, Produktion, Marketing, Bewertungen und Journey-Timeline.',
    zielgruppe: 'Produktmanagement, Vertrieb, Controlling, Einkauf.',
    mehrwert: 'Durchgängige 360°-Sicht je Artikel: Lebenszyklus, Planerreichung, Deckungsbeitrag, Marketingwirkung und Folgeartikel-Verkettung in einer Ansicht.',
    inhalt: 'Artikelauswahl (Katalog-Chips), KPI-Kacheln, Tabs: Journey (Chronologie der Ereignisse), Verkauf (Ist/Plan-Vergleich mit Sparkline), Preisentwicklung, Lagerentwicklung, Produktionskennzahlen (OEE/Ausschuss), Marketing-Aktionen & Probefahrten/Shop-Conversion, Kundenbewertungen (Stern-Verteilung), Folgeartikel & Geschäftsarten.',
    fragen: ['Wie entwickeln sich Umsatz und DB dieses Artikels?', 'Ist der Absatzplan erfüllt?', 'Wie wirkt die Marketingkampagne (ROAS)?', 'Welcher Artikel folgt als Nachfolger?', 'Wie hat sich der Lagerbestand entwickelt?', 'Wie beurteilen Kunden diesen Artikel?'],
    lesehilfe: 'Artikel über die Chip-Leiste oben auswählen. Tabs wechseln die Ansicht. Ampel-Farben zeigen Abweichungen vom Zielkorridor.',
    quelle: 'Artikelstammdaten, Absatz-/Planwerte, Lagerbewegungen, Produktionsdaten, Marketing-Tracking, Kundenbewertungen (Demo: artikelkarte.js).'
  },
  detailanalyse: {
    zweck: 'Operative Granularansicht für Erfasser:innen: tägliche Artikelbewegungen mit Mini-Zeitreihen und Deltas, Änderungslog, statistische Anomalien, Erfassungsqualität je Person und Pivot-Kreuztabelle.',
    zielgruppe: 'Operative Sachbearbeiter:innen (Lager, Einkauf, Vertrieb), Teamleiter:innen, Controlling.',
    mehrwert: 'Alles, was heute passiert ist — auf einen Blick: Was hat sich geändert? Wo laufen Bestände leer? Wer macht Fehler? Schneller Wechsel Tabelle ↔ Trend ↔ Anomalien ohne Detailbericht-Suche.',
    inhalt: 'KPI-Band (Artikel/Umsatz/Absatz/Spikes/Bestandsalarme), Tab „Trend": 14-Tage-Sparklines + „Seit-gestern"-Delta, Tab „Änderungen": Chronolog. Log (Neueingang/Korrektur/Storno/Preis/Bestand), Tab „Anomalien": algorithmisch erkannte Ausreißer (Spike/Alarm/Einbruch), Tab „Qualität": Erfassungsqualität je Person (Korrektur-/Fehlerquote, Vollständigkeit), Tab „Pivot": frei wählbare Dimension × Maß (Kategorie/Erfasser × Umsatz/Menge/Bestand).',
    fragen: ['Was hat sich heute gegenüber gestern verändert?', 'Welche Artikel haben einen Bestandsalarm?', 'Gibt es auffällige Absatz-Spikes?', 'Welche Änderungen wurden in den letzten 72 h gemacht?', 'Wie hoch ist die Fehlerquote je Erfasser:in?', 'Wie verteilt sich der Absatz nach Kategorie?'],
    lesehilfe: 'Rot hinterlegt = Bestandsalarm (Bestand < Minimum). Orange = Umsatz-Spike (> Schnitt + 2σ). Korrektur-Quote > 10 % in Rot.',
    quelle: 'Auftragseingang, Lagerbewegungen, Änderungslog, Erfassungsprotokoll (Demo: detailAnalyse.js).'
  }
}

export const infoVon = (view) => BERICHT_INFO[view] || null
