// =========================================================================
//  BERICHT-INFO — „Schaufenster" für jeden Bericht: Was sagt er aus? Für wen
//  ist er gedacht? Welchen Mehrwert bringt er? So sieht jeder, was es gibt –
//  auch ohne Berechtigung (dann ausgegraut, nur Info, kein Aufruf).
//  Schlüssel = ansicht-/view-Key (wie in navMeta/Navigation).
// =========================================================================
export const BERICHT_INFO = {
  // ---- Cockpit & Berichte ----
  baum: { zweck: 'Zentraler Einstieg: alle Berichte hierarchisch von der Geschäftsführung bis zum Detail.', zielgruppe: 'Alle Rollen.', mehrwert: 'Schneller Überblick und Drill-down bis zur Einzelkennzahl.' },
  kennzahlen: { zweck: 'Nachschlagewerk aller KPIs mit Definition, Ziel und Abhängigkeiten.', zielgruppe: 'Alle, v. a. Controlling.', mehrwert: 'Einheitliches Verständnis der Kennzahlen.' },
  tagesreporting: { zweck: 'Täglicher Blick: operative Kernkennzahlen heute vs. gestern mit „seit gestern"-Delta und dem Verlauf der letzten 14 Tage.', zielgruppe: 'Alle operativen Rollen / Vertrieb / Leitung.', mehrwert: 'Schneller Start in den Tag; Auffälligkeiten sofort sehen.',
    inhalt: 'Umsatz, Auftragseingang, Absatzmenge, Retouren und offener Auftragsbestand — je als Heute-Wert, Delta zum Vortag, Ø der letzten 14 Tage und Sparkline. „Was sticht heute heraus"-Chips.',
    fragen: ['Wie war der gestrige Tag im Vergleich zum Vortag?', 'Gibt es heute eine auffällige Bewegung (> 5 %)?', 'Liegen wir über oder unter dem 14-Tage-Schnitt?'],
    lesehilfe: 'Grün = in die gewünschte Richtung, rot = dagegen (bei Retouren ist weniger besser).', quelle: 'Tagesaktuelle operative Bewegungsdaten (Demo).' },
  katalog: { zweck: 'Durchsuchbarer Katalog aller verfügbaren Berichte.', zielgruppe: 'Alle.', mehrwert: 'Den passenden Bericht schnell finden.' },
  kpieditor: { zweck: 'Eigene, abgeleitete KPIs aus Formeln definieren.', zielgruppe: 'Controlling / Power-User.', mehrwert: 'Individuelle Kennzahlen ohne IT.' },
  designer: { zweck: 'Eigene Berichte aus KPIs zusammenstellen.', zielgruppe: 'Power-User / Controlling.', mehrwert: 'Flexible, wiederverwendbare Auswertungen.' },
  detailberichte: { zweck: 'Granulare Listen (Artikel, Aufträge …) für die Einzelfallprüfung mit Plausibilitätskontrolle.', zielgruppe: 'Controlling / Stammdaten / Fachbereiche.', mehrwert: 'Falscheingaben und unplausible Datenvorgänge gezielt finden und validieren.',
    inhalt: '17 Detaillisten (Artikel, Aufträge, Rechnungen mit Positionen, Konten, Chargen …) mit Plausi-Befunden (Fehler/Warnung/Hinweis), Spaltenwahl, Bookmarks, Daten-Balken, Dimensionsfilter und CSV-Export.',
    fragen: ['Welche Datensätze sind auffällig oder fehlerhaft?', 'Wo weicht ein Einzelwert vom Erwarteten ab?', 'Welche Belege hängen zusammen (Cross-Drill)?'],
    lesehilfe: 'Roter Zeilenrand = Fehler, gelb = Warnung, blau = Hinweis. Klick auf eine Zeile öffnet die Befund-Karte mit E5-Historie.', quelle: 'Mock/WaWi-Detaildaten (später SQL-Anbindung).' },
  // ---- Kosten & Ergebnis ----
  klr: { zweck: 'Grundlagen und Fluss der Kosten- & Leistungsrechnung.', zielgruppe: 'Controlling, Rechnungswesen.', mehrwert: 'Verstehen, welche Kosten wofür entstehen.' },
  einzelgemein: { zweck: 'Einzel- vs. Gemeinkosten und Zuschlagskalkulation.', zielgruppe: 'Kalkulation / Controlling.', mehrwert: 'Saubere Gemeinkostenverrechnung.' },
  abgrenzung: { zweck: 'Überleitung GuV → KLR inkl. neutraler Abgrenzung und kalkulatorischer Kosten.', zielgruppe: 'Rechnungswesen / Controlling.', mehrwert: 'Betriebsergebnis korrekt abgegrenzt.' },
  kalkulatorik: { zweck: 'Kalkulatorische Kosten (Abschreibung, Zinsen, Wagnisse, Miete, Unternehmerlohn) je Wirtschaftsjahr aufbauen — mit begründeten Vorschlägen, „Vorjahr kopieren" und Monatsverteilung.', zielgruppe: 'Controlling / Rechnungswesen.', mehrwert: 'Anders-/Zusatzkosten je Jahr pflegen und sauber ins Betriebsergebnis überleiten.' },
  kostenstellen: { zweck: 'Kostenstellenrechnung mit Umlage und Zuschlagssätzen.', zielgruppe: 'Controlling.', mehrwert: 'Wo entstehen Gemeinkosten – und wie teuer ist jede Stelle.' },
  bab: { zweck: 'Betriebsabrechnungsbogen über die ganze Firma (Plan/Ist).', zielgruppe: 'Controlling.', mehrwert: 'Gemeinkostenverteilung & Wirtschaftlichkeit je Stelle.' },
  kalkulation: { zweck: 'Kostenträgerrechnung: Selbstkosten je Produkt (Division/Äquivalenz/Zuschlag/Maschine/Kuppel).', zielgruppe: 'Kalkulation / Vertrieb.', mehrwert: 'Preisuntergrenzen & Produktergebnis.' },
  ergebnis: { zweck: 'Ergebnisrechnung (GuV) als Staffel und T-Konto.', zielgruppe: 'Geschäftsführung / Finanzen.', mehrwert: 'Periodenergebnis transparent.' },
  deckungsbeitrag: { zweck: 'Deckungsbeitragsrechnung, ein- und mehrstufig.', zielgruppe: 'Vertrieb / Controlling.', mehrwert: 'Welche Produkte tragen die Fixkosten.' },
  profitcenter: { zweck: 'Ergebnis je Profitcenter inkl. Kapitalrendite (ROCE).', zielgruppe: 'Bereichsleitung / GF.', mehrwert: 'Wer verdient wie viel Geld.' },
  segment: { zweck: 'Segment-/Konzernbericht mit Intercompany-Konsolidierung.', zielgruppe: 'GF / Konzern.', mehrwert: 'Konzernsicht ohne Doppelzählung.' },
  // ---- Operativ ----
  marketing: { zweck: 'Digital-Analytics: Funnel, Conversion, Kanäle, ROAS.', zielgruppe: 'Marketing / Vertrieb.', mehrwert: 'Kanäle & Kampagnen datenbasiert steuern.' },
  marketingkarte: { zweck: 'Geografische Verteilung mit Drilldown (Welt → Europa → Deutschland → Bundesland → PLZ-Gebiet) als Choropleth-Kachelkarte; wählbare Metrik (Umsatz, Marktanteil, DB %, Online-Anteil) und Warenbereichs-Split je Region.', zielgruppe: 'Marketing / Vertrieb / GF.', mehrwert: 'Stärkste/schwächste Regionen und Marktpotenziale auf einen Blick.',
    inhalt: 'Kachelkarte je Ebene; Farbintensität = gewählte Metrik; je Region Umsatzanteil, DB % und Warenbereichs-Split (Fahrräder/Zubehör/Bekleidung). Breadcrumb-Navigation über die Ebenen.',
    fragen: ['In welcher Region/PLZ ist unser Marktanteil am höchsten?', 'Wo ist der Online-Anteil besonders groß?', 'Wie verteilt sich der Umsatz nach Warenbereichen je Region?'],
    lesehilfe: 'Dunklere Kachel = höherer Metrikwert. Klick auf eine Kachel mit › geht eine Ebene tiefer.', quelle: 'Regionale Vertriebs-/Marktdaten (Demo).' },
  events: { zweck: 'Aktionen mit Zeitraum/Kosten und ihre Wirksamkeit.', zielgruppe: 'Marketing / Vertrieb.', mehrwert: 'Werbe-ROI, Mehrumsatz und Ladenhüter-Abbau messen.' },
  bestand: { zweck: 'Bestands-Gängigkeit (ABC/XYZ, Renner/Ladenhüter).', zielgruppe: 'Logistik / Einkauf.', mehrwert: 'Kapitalbindung senken, Ladenhüter erkennen.' },
  lager: { zweck: 'Lagerverwaltung aus Controlling-Sicht: Kapitalbindung, Lagerhaltungskosten, Standortkosten, Bestandsoptimierung (EOQ).', zielgruppe: 'Logistik / Controlling.', mehrwert: 'Lagerkosten transparent machen und Bestände/Bestellmengen optimieren.' },
  wms: { zweck: 'Operatives Lager: Lagerplätze, Wareneingang, Kommissionierung, Umlagern und Bewegungsprotokoll.', zielgruppe: 'Lager / Logistik.', mehrwert: 'Bestände platzgenau führen und Buchungen nachvollziehen.' },
  produktion: { zweck: 'Produktionscontrolling strategisch & operativ: Werke/Linien (Live-Status, OEE), optimale Losgrößen (EPQ), Fehlteile, Qualität (FPY/Ausschuss) und Abgleich Produktion ↔ Lager ↔ Auftragsbestand.', zielgruppe: 'Produktion / Supply Chain / Controlling.', mehrwert: 'Engpässe, Fehlteile und Qualitätsprobleme früh erkennen, Losgrößen und Output optimal steuern.',
    inhalt: 'Cockpit (OEE, FPY, Auslastung, Termintreue), Werke & Linien live (welches Produkt läuft wo), Produktionsprogramm (EPQ-Losgrößen), Fehlteile mit blockierten Aufträgen, Qualität je Linie, Output & Markt-Abgleich (Produktion ↔ Lager ↔ Auftragsbestand).',
    fragen: ['Welche Linie ist der Engpass?', 'Welche Aufträge stehen wegen fehlender Teile?', 'Welche Losgröße ist am wirtschaftlichsten?', 'Sollen wir aufstocken oder drosseln?'],
    lesehilfe: 'OEE = Verfügbarkeit · Leistung · Qualität (Weltklasse ≥ 85 % ⭐). ⛰️ markiert den Engpass.', quelle: 'Produktions-/MES-Daten (Demo).' },
  szenario: { zweck: 'What-if-Simulator: Treiber-Kennzahlen prozentual oder absolut verändern und die Wirkung auf abgeleitete KPIs (DB, Margen, Ergebnis) live über den Abhängigkeitsgraph sehen.', zielgruppe: 'Controlling / GF.', mehrwert: 'Annahmen schnell durchspielen, ohne gespeicherte Werte zu ändern.' },
  planung: { zweck: 'Budget-, Forecast- und Szenarienplanung: Mengen je Produkt bottom-up planen oder ein Ziel top-down herunterbrechen (Menge ↔ Betrag), inkl. Schwund-Aufschlag, Produktion ohne Umsatz und Liquiditätsvorschau.', zielgruppe: 'Controlling / Vertrieb / Einkauf / Produktion.', mehrwert: 'Alle haben dieselbe Vorstellung von den Plan-Werten; Wirkung von Annahmen sofort sichtbar.',
    inhalt: 'Pläne anlegen/kopieren; Ergebnis (Umsatz/Wareneinsatz/DB/AE/Liquidität); Top-Down-Verteilung; Monatsverteilung (Splash, inkl. Saison); Artikelverteilung über die Produkthierarchie; Termin-/Beschaffungssicht; Szenarienvergleich.',
    fragen: ['Welcher Umsatz/DB ergibt sich aus den Plan-Mengen?', 'Wann muss spätestens bestellt/produziert werden?', 'Wie unterscheiden sich Budget, Best und Worst Case?', 'Bleibt die Liquidität übers Jahr positiv?'],
    lesehilfe: 'Menge ODER Betrag eingeben — das andere wird über den VK-Preis berechnet. Im Szenarienvergleich ist die erste Spalte die Basis.', quelle: 'Lokale Plan-Daten (localStorage); Preise aus den Produktstammdaten.' },
  gutschriften: { zweck: 'Gutschriften & Retouren je Kunde, alle Belege über mehrere Versendungen verknüpft. Trennt Retourengutschriften (mit Absatzänderung) und Wertgutschriften (ohne), je in EUR und % zum tatsächlichen Auftrag.', zielgruppe: 'Vertriebscontrolling / Vertrieb / Buchhaltung.', mehrwert: 'Erkennen, ob man beim Kunden „sauber" ist; auffällige Retouren-/Wertgutschriftquoten früh sehen.',
    inhalt: 'Je Kunde: tatsächlicher Auftrag (AET), Retourengutschriften und Wertgutschriften in EUR und % zum AET, Status (sauber/beobachten/auffällig); aufklappbar alle verknüpften Belege mit Art, Grund, Menge und Wert.',
    fragen: ['Sind wir beim Kunden „sauber"?', 'Wie hoch ist die Retourengutschriftquote (> 55 %?)', 'Wie viel Wertgutschrift gab es ohne Absatzänderung?'],
    lesehilfe: 'Rote Retourenquote > 55 % = genauer prüfen. Zeile aufklappen zeigt alle Belege über mehrere Versendungen.', quelle: 'Gutschrift-/Retourenbelege + Auftragsdaten (Demo).' },
  prozesskette: { zweck: 'Vertriebs-Funnel Angebot -> Umsatz als Flussgrafik: ANGE -> AE -> AEB -> AET -> Umsatzerloese mit Abgaengen je Stufe (verlorene/offene Angebote, Stornos, nicht fakturiert).', zielgruppe: 'Vertrieb / Vertriebscontrolling / GF.', mehrwert: 'Sieht sofort, wo im Funnel Potenzial verloren geht.' },
  vertriebkpi: { zweck: 'Vertriebskennzahlen-Taxonomie in sechs Phasen (Angebot, Auftragseingang, Verwertung, Bearbeitung, Qualitaet, Umsatz) mit Fach-Codes und Symbol-Legende. AEW entfaellt, OAU = Auftragsbestand.', zielgruppe: 'Vertrieb / Vertriebscontrolling.', mehrwert: 'Einheitliches Verstaendnis der Vertriebskennzahlen entlang des Funnels.' },
  abgleichabsatz: { zweck: 'Abgleich der fakturierten Absatzmenge (aus Rechnungspositionen) mit dem tatsächlichen Auftragseingang (AET, WaWi) je Produkt — Differenz abs/% und wahrscheinliche Ursache.', zielgruppe: 'Vertriebscontrolling / Controlling.', mehrwert: 'Auseinanderlaufen von Absatz und Auftragseingang früh erkennen (Teillieferung, Storno, Verschiebung, Nachfakturierung).' },
  lieferant: { zweck: 'Lieferanten-Lebenszyklus und -Risiken.', zielgruppe: 'Einkauf.', mehrwert: 'Lieferantenbasis aktiv steuern.' },
  auftrag: { zweck: 'Order-to-Cash-Prozess mit Engpassanalyse.', zielgruppe: 'Vertrieb / Finanzen.', mehrwert: 'Durchlaufzeiten verkürzen, Cash beschleunigen.' },
  forderungen: { zweck: 'Forderungs-Aging, DSO und Ausfallrisiko.', zielgruppe: 'Finanzen / Risiko.', mehrwert: 'Liquidität sichern, Ausfälle vermeiden.' },
  // ---- Analyse & Steuerung ----
  bi: { zweck: 'Self-Service-BI für freie Auswertungen.', zielgruppe: 'Alle.', mehrwert: 'Ad-hoc-Analysen ohne IT.' },
  abweichung: { zweck: 'Plan/Ist-Abweichung, aufgeteilt in Preis- und Mengeneffekt.', zielgruppe: 'Controlling.', mehrwert: 'Ursachen von Abweichungen erkennen.' },
  vergleich: { zweck: 'Versionsvergleich (Plan/Forecast/Ist).', zielgruppe: 'Controlling.', mehrwert: 'Stände sauber gegenüberstellen.' },
  qc: { zweck: 'Querchecks / Datenqualitätsprüfungen.', zielgruppe: 'Controlling / IT.', mehrwert: 'Fehler vor dem Reporting finden.' },
  abstimmung: { zweck: 'Abstimmbrücken zwischen FiBu und Controlling.', zielgruppe: 'Rechnungswesen.', mehrwert: 'Differenzen erklären und schließen.' },
  lebenszyklus: { zweck: 'Produkt- und Kunden-Lebenszyklus mit Phasen.', zielgruppe: 'Vertrieb / Marketing.', mehrwert: 'Phasengerechte Strategie je Produkt/Kunde.' },
  lzempfehlung: { zweck: 'Automatische Empfehlungen + Maßnahmen aus den Lebenszyklen.', zielgruppe: 'Vertrieb / Controlling.', mehrwert: 'Risiken/Chancen direkt in Maßnahmen überführen.' },
  anlagen: { zweck: 'Anlagen-Lebenszyklus inkl. kalkulatorischer Abschreibung.', zielgruppe: 'Finanzen / Controlling.', mehrwert: 'Investitions- und Ersatzsteuerung.' },
  technologie: { zweck: 'Technologie-Reifegrad & F&E-Portfolio.', zielgruppe: 'GF / F&E.', mehrwert: 'Innovationspipeline bewerten und priorisieren.' },
  mitarbeiter: { zweck: 'Mitarbeiter-Lebenszyklus (HR).', zielgruppe: 'HR / Personalcontrolling.', mehrwert: 'Bindung & Fluktuation steuern.' },
  massnahmen: { zweck: 'Maßnahmen-Nachverfolgung (SMART, mit Owner/Frist).', zielgruppe: 'Alle Führungskräfte.', mehrwert: 'Vom Bericht zur umgesetzten Maßnahme.' },
  instrumente: { zweck: 'Übersicht der Controlling-Instrumente.', zielgruppe: 'Controlling.', mehrwert: 'Das passende Instrument je Fragestellung.' },
  alerts: { zweck: 'Frühwarnungen bei kritischen Kennzahlen.', zielgruppe: 'Alle.', mehrwert: 'Rechtzeitig gegensteuern.' },
  zeit: { zweck: 'Zeit & Datenart umschalten (Ist/Plan/Forecast/Tagesreporting).', zielgruppe: 'Alle.', mehrwert: 'Berichte aus verschiedenen Datensichten lesen.' },
  // ---- Lernen & Wissen ----
  lernpfad: { zweck: 'Geführter Lernweg durch Controlling & Kostenrechnung.', zielgruppe: 'Neue Anwender, alle.', mehrwert: 'Wissen aufbauen, mit Quiz & Zertifikat.' },
  doku: { zweck: 'Durchsuchbares Wissens-/Doku-Nachschlagewerk.', zielgruppe: 'Alle.', mehrwert: 'Themen schnell nachlesen.' },
  controlling: { zweck: 'Controlling-Struktur & Teilgebiete.', zielgruppe: 'Alle / Einarbeitung.', mehrwert: 'Das Big Picture verstehen.' },
  klrablauf: { zweck: 'KLR-Ablauf als roter Faden mit echten Werten.', zielgruppe: 'Einarbeitung / Controlling.', mehrwert: 'Zusammenhänge der Kostenrechnung nachvollziehen.' },
  ablaufdiagramm: { zweck: 'Interaktives Prozess-/Ablaufdiagramm.', zielgruppe: 'Alle.', mehrwert: 'Prozesse klickbar verstehen.' },
  // ---- Verwaltung ----
  abschluss: { zweck: 'Abschluss & Versionierung der Berichte.', zielgruppe: 'Rechnungswesen.', mehrwert: 'Sauberer, nachvollziehbarer Periodenabschluss.' },
  verteiler: { zweck: 'Geplanter, automatischer Versand von Berichten.', zielgruppe: 'Controlling / Assistenz.', mehrwert: 'Die richtigen Berichte automatisch verteilen.' },
  transport: { zweck: 'Transport von Berichten zwischen dev/test/prod.', zielgruppe: 'Admin / Power-User.', mehrwert: 'Berichte kontrolliert ausrollen.' },
  wizard: { zweck: 'Ersteinrichtung der Anwendung.', zielgruppe: 'Admin.', mehrwert: 'System sauber konfigurieren.' },
  admin: { zweck: 'Admin-Bereich: Logo, Themes, Branding.', zielgruppe: 'Admin.', mehrwert: 'Die App an Anlässe/Marke anpassen.' },
  nutzung: { zweck: 'Nutzungs-Statistik: Aufrufe, eindeutige & aktive User.', zielgruppe: 'Admin.', mehrwert: 'Das Reporting datenbasiert verbessern.' },
  rechte: { zweck: 'Rollen & Rechte verwalten (Bereiche, geschützte KPIs, Mitglieder).', zielgruppe: 'Admin.', mehrwert: 'Sichtbarkeit & Schutz zentral steuern.' }
}

export const infoVon = (view) => BERICHT_INFO[view] || null
