import { chromium } from 'playwright-core'

const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await browser.newContext({ viewport: { width: 1200, height: 1000 } })
const page = await ctx.newPage()
const fail = (m) => { console.log('FAIL: ' + m); process.exitCode = 1 }
const ok = (m) => console.log('OK: ' + m)
const store = () => page.evaluate(() => JSON.parse(localStorage.getItem('eselsohr-v1')))

await page.goto('http://localhost:4173')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(400)

// 1. Onboarding hat Demo-Knopf
const demoBtn = page.locator('button', { hasText: 'Erst mal die Demo ansehen' })
await demoBtn.count() ? ok('Demo-Knopf im Onboarding') : fail('Demo-Knopf fehlt')
await demoBtn.click()
await page.waitForTimeout(500)

let body = await page.textContent('body')
body.includes('Hallo Jan') ? ok('Demo geladen, angemeldet als Jan') : fail('Demo lädt nicht')
body.includes('Demo-Modus') ? ok('Demo-Hinweis sichtbar') : fail('Demo-Hinweis fehlt')

// 2. Assistent: Geburtstag zuerst, dann Betreuung, Serie
body.includes('Assistent · schlägt vor') ? ok('Assistent-Karte da') : fail('Assistent-Karte fehlt')
body.includes('Oma Helga hat in 2 Tagen Geburtstag') ? ok('Vorschlag: Geburtstag (in 2 Tagen)') : fail('Geburtstags-Vorschlag fehlt')
body.includes('Wird 77') ? ok('Alter berechnet (77)') : fail('Alter fehlt')
body.includes('Betreuungszeiten für Ben anlegen') ? ok('Vorschlag: Betreuung Ben') : fail('Betreuungs-Vorschlag fehlt')
body.includes('„Klavierstunde“ wiederholt sich') ? ok('Vorschlag: Serie erkannt') : fail('Serien-Vorschlag fehlt')

// 3. WhatsApp-Glückwunsch aus dem Assistenten (URL abfangen statt echt öffnen)
await page.evaluate(() => { window.__wa = null; window.open = (u) => { window.__wa = u; return null } })
await page.locator('.row', { hasText: 'Oma Helga' }).locator('button', { hasText: 'Glückwunsch' }).click()
await page.waitForTimeout(200)
const wa = decodeURIComponent(await page.evaluate(() => window.__wa || ''))
wa.includes('wa.me/491712223344') ? ok('WhatsApp-Link mit Nummer (0171→49171)') : fail('WA-Link: ' + wa.slice(0, 90))
wa.includes('Alles Gute zum Geburtstag, Oma Helga!') && wa.includes('Familie Muster')
  ? ok('Vorlage ausgefüllt (Name + Familie)') : fail('Vorlage: ' + wa.slice(0, 160))

// 4. Serien-Wizard durchspielen
await page.locator('.row', { hasText: 'Klavierstunde' }).locator('button', { hasText: 'Wizard starten' }).click()
await page.waitForTimeout(300)
let sheet = await page.textContent('.sheet')
sheet.includes('gab es schon 3×') ? ok('Serien-Wizard zeigt Muster') : fail('Serien-Wizard: ' + sheet.slice(0, 120))
await page.locator('.sheet button', { hasText: 'Ab nächster Woche eintragen' }).click()
await page.waitForTimeout(300)
let db = await store()
db.events.filter((e) => e.title === 'Klavierstunde' && e.serie).length === 8 ? ok('8 Serientermine angelegt') : fail('Serientermine fehlen')
body = await page.textContent('body')
!body.includes('wiederholt sich') ? ok('Serien-Vorschlag danach weg') : fail('Serien-Vorschlag bleibt')

// 5. Sport-Vorschlag rückt nach (max. 3 gleichzeitig) → Wizard
body.includes('Dein Sport kommt diese Woche zu kurz') ? ok('Sport-Vorschlag rückt nach') : fail('Sport-Vorschlag fehlt')
await page.locator('.row', { hasText: 'Sport kommt diese Woche zu kurz' }).locator('button', { hasText: 'Einplanen' }).click()
await page.waitForTimeout(200)
await page.fill('.sheet input[aria-label="Sportart"]', 'Laufen')
await page.locator('.sheet button', { hasText: 'Einplanen' }).click()
await page.waitForTimeout(300)
db = await store()
db.events.filter((e) => e.sport && e.title === 'Laufen').length === 8 ? ok('Sport-Wizard plant 8 Einheiten') : fail('Sport-Wizard')

// 6. Blitzzettel ansehen & sortieren
await page.locator('.iconbtn[title="Blitzzettel"]').click()
await page.waitForTimeout(200)
await page.locator('.sheet button', { hasText: 'Deine Zettel ansehen & sortieren (3)' }).click()
await page.waitForTimeout(200)
sheet = await page.textContent('.sheet')
sheet.includes('Deine Blitzzettel (3)') ? ok('Blitz-Liste öffnet mit 3 Zetteln') : fail('Blitz-Liste fehlt')
await page.locator('.sheet button', { hasText: 'A–Z' }).click()
await page.waitForTimeout(150)
const titles = await page.locator('.sheet .row-title').allTextContents()
titles[0].startsWith('Geschenk') ? ok('Sortierung A–Z wirkt') : fail('Sortierung: ' + titles.join(' | '))
await page.locator('.sheet .row', { hasText: 'Reifenwechsel' }).locator('button', { hasText: '→ To-do' }).click()
await page.waitForTimeout(300)
db = await store()
db.items.some((i) => i.list === 'todo' && i.text.includes('Reifenwechsel')) ? ok('Zettel → To-do übernommen') : fail('To-do fehlt')
await page.locator('.sheet .x').click()
await page.waitForTimeout(200)

// 7. Geburtstagsliste unter Listen: anzeigen, anlegen, Vorlage bearbeiten
await page.locator('.navbtn', { hasText: 'Listen' }).click()
await page.waitForTimeout(300)
body = await page.textContent('body')
body.includes('Geburtstage · nie wieder vergessen') ? ok('Geburtstags-Karte da') : fail('Geburtstags-Karte fehlt')
body.includes('Tante Mia') && body.includes('wird 41') ? ok('Tante Mia mit Alter 41 gelistet') : fail('Tante Mia fehlt')
const first = await page.locator('.card:has-text("Oma Helga") .row-title').first().textContent()
first === 'Oma Helga' ? ok('Sortierung: nächster Geburtstag zuerst') : fail('Sortierung: ' + first)
await page.fill('input[aria-label="Name"]', 'Onkel Paul')
await page.fill('input[aria-label="Geburtstag"]', '01.01.1970')
await page.locator('button', { hasText: 'Merken' }).click()
await page.waitForTimeout(300)
db = await store()
db.geburtstage.some((g) => g.name === 'Onkel Paul') ? ok('Geburtstag angelegt') : fail('Anlegen fehlgeschlagen')
await page.locator('button', { hasText: 'WhatsApp-Vorlage bearbeiten' }).click()
await page.waitForTimeout(150)
await page.fill('textarea[aria-label="WhatsApp-Vorlage"]', 'Happy Birthday {name}, feier schön! Deine {familie}')
await page.locator('button', { hasText: 'Speichern' }).first().click()
await page.waitForTimeout(300)
db = await store()
db.waTemplate?.startsWith('Happy Birthday') ? ok('Eigene Vorlage gespeichert') : fail('Vorlage nicht gespeichert')

// 8. Auto-Vervollständigung im Termin-Formular
await page.locator('.navbtn', { hasText: 'Heute' }).click()
await page.waitForTimeout(200)
await page.locator('button', { hasText: '+ Termin' }).first().click()
await page.waitForTimeout(200)
await page.fill('#f-title', 'Klavierstunde')
await page.waitForTimeout(150)
const time = await page.inputValue('#f-time')
const who = await page.locator('#f-who option:checked').textContent()
time === '15:30' && who === 'Emma' ? ok('Vervollständigt: 15:30 + Emma') : fail(`Vervollständigung: ${time} / ${who}`)
await page.locator('.sheet .x').click()

// 9. Ist-Zeiten-Wizard als Anne
await page.locator('.userchip').click()
await page.locator('button', { hasText: '⇄ Profil wechseln' }).click()
await page.waitForTimeout(300)
await page.locator('.profile', { hasText: 'Anne' }).click()
await page.waitForTimeout(400)
body = await page.textContent('body')
body.includes('Praxis-Termin ohne Ist-Zeit') ? ok('Anne sieht Ist-Zeiten-Vorschlag') : fail('Ist-Vorschlag fehlt')
await page.locator('.row', { hasText: 'ohne Ist-Zeit' }).locator('button', { hasText: 'Wizard starten' }).click()
await page.waitForTimeout(200)
sheet = await page.textContent('.sheet')
sheet.includes('1 von 1') && sheet.includes('Julia Müller') ? ok('Ist-Wizard zeigt Klientin') : fail('Ist-Wizard: ' + sheet.slice(0, 120))
await page.fill('#w-ist', '45')
await page.locator('.sheet button', { hasText: 'Speichern & weiter' }).click()
await page.waitForTimeout(300)
db = await store()
db.events.some((e) => e.klid && e.ist === 45) ? ok('Ist-Zeit 45 Min. gespeichert') : fail('Ist-Zeit fehlt')

// 10. Demo beenden
await page.locator('.navbtn', { hasText: 'Familie' }).click()
await page.waitForTimeout(200)
await page.locator('button', { hasText: 'Demo beenden' }).click()
await page.waitForTimeout(600)
;(await page.textContent('body')).includes('Familie anlegen') ? ok('Demo beendet → Onboarding') : fail('Demo-Ende')

await browser.close()
console.log(process.exitCode ? 'TESTS FAILED' : 'ALL TESTS PASSED')
