import { chromium } from "playwright-core";
import http from "http"; import fs from "fs"; import path from "path";
const dist = path.resolve("dist");
const mime = {".html":"text/html",".js":"text/javascript",".css":"text/css"};
const srv = http.createServer((req,res)=>{
  let p = path.join(dist, req.url.split("?")[0]);
  if(!fs.existsSync(p)||fs.statSync(p).isDirectory()) p = path.join(dist,"index.html");
  res.setHeader("content-type", mime[path.extname(p)]||"application/octet-stream");
  res.end(fs.readFileSync(p));
}).listen(4174);
const browser = await chromium.launch({ executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--no-sandbox"] });
const page = await browser.newPage();
const errors=[];
page.on("pageerror", e=>errors.push(e.message));
await page.addInitScript(()=>{ localStorage.setItem("vereinsapp_lang","ar"); });
await page.goto("http://127.0.0.1:4174/", { waitUntil:"networkidle", timeout:30000 }).catch(e=>errors.push(e.message));
await page.waitForTimeout(3000);
const dir = await page.evaluate(()=>document.documentElement.dir);
const langAttr = await page.evaluate(()=>document.documentElement.lang);
const text = await page.evaluate(()=>document.body.innerText.slice(0,200));
const hasArabic = /[؀-ۿ]/.test(text);
console.log("dir:", dir, "| lang:", langAttr, "| Arabisch sichtbar:", hasArabic);
console.log("Text:", JSON.stringify(text.slice(0,140)));
if(errors.length) console.log("FEHLER:", errors.slice(0,5));
await browser.close(); srv.close();
process.exit(errors.length||dir!=="rtl"||!hasArabic ? 1 : 0);
