// ----------------------------------------------------------------
// Spielzug-Bibliothek: echte Spielvorgaenge, die der Trainer auswaehlen,
// den Kindern zeigen und mit einem kurzen Zuruf abrufen kann
// ("Hinterlaufen!", "Doppelpass!"). Jeder Spielzug bringt mit:
//   ruf      - das eine Wort, das auf dem Platz gerufen wird
//   kurz     - ein Satz, worum es geht
//   ablauf   - was nacheinander passiert (Laien-Sprache)
//   warum    - warum das den Gegner ueberrascht
//   beispiel - eine konkrete Situation aus dem Spiel
//   el       - die Zeichnung (gleiches Format wie die Uebungs-Diagramme,
//              dadurch laeuft die vorhandene Animation automatisch mit)
// Koordinaten: x = 0 links ... 100 rechts, y = 0 gegnerisches Tor (oben)
// ... 100 eigenes Tor (unten). Wir spielen also nach oben.
// ----------------------------------------------------------------
const P  = (x,y,n)   => ({type:"player",x,y,n});
const O  = (x,y)     => ({type:"opp",x,y});
const B  = (x,y)     => ({type:"ball",x,y});
const PA = (x1,y1,x2,y2) => ({type:"passArrow",x1,y1,x2,y2,ball:true});
const RU = (x1,y1,x2,y2) => ({type:"runArrow",x1,y1,x2,y2});
const DR = (x1,y1,x2,y2) => ({type:"dribbleArrow",x1,y1,x2,y2,ball:true});
const CO = (x,y)     => ({type:"cone",x,y});
// Seiten-Spiegelung: derselbe Spielzug ueber links oder rechts
const mir = (el,on) => on ? el.map(e=>({...e,
  ...(e.x!=null?{x:100-e.x}:{}), ...(e.x1!=null?{x1:100-e.x1}:{}), ...(e.x2!=null?{x2:100-e.x2}:{}) })) : el;

// ---- Bausteine: je ein sauber gezeichneter Grundvorgang --------------
export const ART = {
  // Aussen laeuft hinter dem Ballfuehrenden vorbei und wird angespielt
  hinterlaufen: ({r=false}={}) => mir([
    P(32,58,7), B(34,55), P(24,52,11), O(38,48), O(30,38),
    RU(22,50,16,28), PA(34,54,18,30),
  ],r),
  // Pass und sofortige Rueckgabe in den Lauf
  doppelpass: ({r=false}={}) => mir([
    P(38,60,8), B(40,57), P(56,44,9), O(47,50),
    PA(40,56,55,46), PA(57,42,52,32), RU(38,58,50,34),
  ],r),
  // Pass in die Tiefe hinter die Abwehrkette
  steilpass: ({r=false}={}) => mir([
    P(45,62,6), B(46,59), P(58,46,9), O(30,40), O(46,40), O(62,40),
    RU(59,44,64,24), PA(46,58,64,26),
  ],r),
  // Aussen zur Grundlinie, Flanke in die Mitte
  flanke: ({r=false}={}) => mir([
    P(16,36,7), B(17,33), P(46,30,9), P(60,34,10), O(24,30), O(48,20),
    DR(17,33,12,18), PA(12,17,46,18), RU(46,28,48,18),
  ],r),
  // Zwei Spieler kreuzen die Wege, einer nimmt den Ball mit
  kreuzen: ({r=false}={}) => mir([
    P(38,52,8), B(39,49), P(58,52,10), O(48,40),
    DR(39,49,56,44,true), RU(58,50,40,42),
  ],r),
  // Langer Querpass auf die freie Seite
  verlagern: ({r=false}={}) => mir([
    P(20,52,6), B(21,49), P(78,46,11), O(28,44), O(42,42), O(52,46),
    PA(21,49,76,46), RU(78,44,78,32),
  ],r),
  // Zielspieler legt mit dem Ruecken zum Tor ab
  ablage: ({r=false}={}) => mir([
    P(48,58,8), B(49,55), P(48,30,9), P(38,44,10), O(48,24),
    PA(49,54,48,32), PA(46,30,39,42), RU(38,46,42,26),
  ],r),
  // 1 gegen 1 mit Abschluss
  eins: ({r=false}={}) => mir([
    P(46,46,9), B(47,43), O(46,32),
    DR(47,43,54,24), PA(54,22,50,8),
  ],r),
  // Ueberzahl 2 gegen 1
  zwei1: ({r=false}={}) => mir([
    P(40,44,9), B(41,41), P(58,42,10), O(48,32),
    PA(41,41,57,40), RU(40,42,46,26), PA(58,38,52,12),
  ],r),
  // Dreieck: drei Stationen, zwei Paesse
  dreieck: ({r=false}={}) => mir([
    P(36,58,6), B(37,55), P(52,50,8), P(44,36,9), O(46,46),
    PA(37,55,51,51), PA(53,48,45,38), RU(36,56,40,44),
  ],r),
  // Diagonaler Lauf in die Schnittstelle
  diagonal: ({r=false}={}) => mir([
    P(46,58,6), B(47,55), P(74,44,11), O(38,38), O(56,38),
    RU(73,42,50,22), PA(47,55,50,24),
  ],r),
  // Aufdrehen nach Rueckpass
  aufdrehen: ({r=false}={}) => mir([
    P(50,46,9), P(50,66,6), B(51,63), O(50,36),
    PA(51,63,50,48), RU(50,46,44,40), PA(48,44,44,26),
  ],r),
  // Torwart eroeffnet flach auf aussen
  twaufbau: ({r=false}={}) => mir([
    P(50,92,1), B(51,89), P(18,74,2), P(82,74,5), O(50,74),
    PA(51,89,20,74), RU(18,72,18,58),
  ],r),
  // Anlaufen und auf eine Seite lenken
  lenken: ({r=false}={}) => mir([
    O(50,26), B(51,29), P(46,38,9), P(24,42,7), P(70,44,11),
    RU(46,38,54,30), RU(24,42,30,34),
  ],r),
  // Ballfuehrenden zu zweit stellen
  doppeln: ({r=false}={}) => mir([
    O(48,40), B(49,43), P(40,50,5), P(58,48,6), P(50,62,4),
    RU(40,50,45,44), RU(58,48,53,44),
  ],r),
  // Herausruecken und dahinter absichern
  absichern: ({r=false}={}) => mir([
    O(46,36), B(47,39), P(46,50,4), P(30,56,3), P(62,56,5),
    RU(46,50,46,42), RU(30,56,40,58), RU(62,56,54,58),
  ],r),
  // Kette rueckt gemeinsam heraus
  kette: ({r=false}={}) => mir([
    O(48,30), B(49,33), P(24,52,2), P(40,52,3), P(58,52,4), P(74,52,5),
    RU(24,52,24,44), RU(40,52,40,44), RU(58,52,58,44), RU(74,52,74,44),
  ],r),
  // Nach Ballgewinn sofort nach vorne
  konter: ({r=false}={}) => mir([
    P(46,68,6), B(47,65), P(30,46,7), P(64,46,11), O(46,58), O(40,34),
    PA(47,65,64,46), RU(30,46,36,24), RU(64,44,60,26),
  ],r),
  // Sofort nachsetzen nach Ballverlust
  gegenpressing: ({r=false}={}) => mir([
    O(48,46), B(49,49), P(40,38,9), P(56,40,10), P(48,58,8),
    RU(40,38,46,44), RU(56,40,52,44), RU(48,58,48,52),
  ],r),
  // Ecke kurz ausgespielt
  eckekurz: ({r=false}={}) => mir([
    P(4,12,7), B(5,15), P(16,22,8), P(46,16,9), P(58,20,10), O(44,10), O(56,14),
    PA(5,15,16,22), PA(18,22,46,16),
  ],r),
  // Ecke auf den ersten Pfosten
  eckepfosten: ({r=false}={}) => mir([
    P(4,12,7), B(5,15), P(38,14,9), P(58,24,10), O(46,12), O(54,16),
    PA(5,15,38,13), RU(58,22,42,14),
  ],r),
  // Freistoss: Mauer, Ablage, Schuss
  freistoss: ({r=false}={}) => mir([
    P(44,30,8), B(45,33), P(54,32,10), O(40,20), O(46,20), O(52,20),
    PA(45,32,54,32), PA(54,30,50,8),
  ],r),
  // Einwurf mit Hinterlaufen
  einwurf: ({r=false}={}) => mir([
    P(4,44,7), B(5,41), P(16,40,8), P(20,54,6), O(22,38),
    PA(5,41,16,40), RU(4,46,12,26), PA(16,38,12,28),
  ],r),
  // Sperre/Block: den Weg des Gegners zustellen
  block: ({r=false}={}) => mir([
    P(44,44,9), B(45,41), P(56,40,10), O(52,34),
    RU(56,40,52,38), DR(45,41,58,26),
  ],r),
  // Breite und Tiefe: das Feld gross machen
  breite: ({r=false}={}) => mir([
    P(50,58,6), B(51,55), P(14,46,7), P(86,46,11), P(50,28,9),
    RU(14,46,14,34), RU(86,46,86,34), RU(50,30,50,20),
  ],r),
  // Positionswechsel zweier Spieler
  rochade: ({r=false}={}) => mir([
    P(38,42,10), P(62,42,9), P(50,60,8), B(51,57), O(50,32),
    RU(38,42,60,36), RU(62,42,40,36), PA(51,57,50,44),
  ],r),
  // Torwart faengt/klaert und startet neu
  twaktion: ({r=false}={}) => mir([
    P(50,92,1), O(50,74), B(50,80), P(20,80,2), P(80,80,5),
    RU(50,92,50,84), PA(50,84,20,78),
  ],r),
  // Kurzer Antritt in den freien Raum (ohne Ball)
  freilaufen: ({r=false}={}) => mir([
    P(48,60,6), B(49,57), P(66,46,10), O(60,42), O(44,40),
    RU(66,46,74,36), PA(49,57,74,38),
  ],r),
};

// Kurzschreibweise fuer die Eintraege
const SZ = (id,cat,name,ruf,ages,kurz,ablauf,warum,beispiel,art,par) =>
  ({ id, cat, name, ruf, ages, kurz, ablauf, warum, beispiel, art, el: (ART[art]||ART.dreieck)(par||{}) });

export const SPIELZUG_CATS = [
  {id:"angriff",  label:"Angriff & Kombination", icon:"🚀", col:"#16a34a"},
  {id:"aussen",   label:"Außen & Flanke",        icon:"↗",  col:"#0891b2"},
  {id:"abschluss",label:"Abschluss",             icon:"🥅", col:"#dc2626"},
  {id:"aufbau",   label:"Spielaufbau",           icon:"🧱", col:"#7c3aed"},
  {id:"pressing", label:"Pressing & Erobern",    icon:"🔥", col:"#ea580c"},
  {id:"defensiv", label:"Verteidigen",           icon:"🛡", col:"#2563eb"},
  {id:"umschalt", label:"Umschalten & Konter",   icon:"⚡", col:"#be123c"},
  {id:"standard", label:"Standards",             icon:"🎯", col:"#d97706"},
  {id:"torwart",  label:"Torwart",               icon:"🧤", col:"#0f766e"},
];
export const SZ_AGES = [
  {id:"G", label:"G/Bambini"}, {id:"F", label:"F-Jugend"}, {id:"E", label:"E-Jugend"},
  {id:"D", label:"D-Jugend"},  {id:"C", label:"C-Jugend"}, {id:"B", label:"B/A-Jugend"},
];
export const catOfSpielzug = c => SPIELZUG_CATS.find(x=>x.id===c) || SPIELZUG_CATS[0];
export const SZ_CAT_FOR_TEAM = cat => {
  const s=String(cat||"").toLowerCase();
  if(s.includes("bambini")||s.includes("g-jugend")) return "G";
  if(s.includes("f-jugend")) return "F";
  if(s.includes("e-jugend")) return "E";
  if(s.includes("d-jugend")) return "D";
  if(s.includes("c-jugend")) return "C";
  return "B";
};

// =================== 1) ANGRIFF & KOMBINATION ===================
const SZ_ANGRIFF = [
SZ("sz001","angriff","Hinterlaufen","Hinterlaufen!",["F","E","D","C","B"],
 "Ein Mitspieler läuft außen hinter dem Ballführenden vorbei und ist plötzlich frei.",
 ["Der Ballführende dribbelt ruhig nach vorne und schaut den Verteidiger an.","Der Mitspieler läuft von hinten außen an ihm vorbei – nah dran, damit der Verteidiger ihn zu spät sieht.","Genau in dem Moment wird der Ball nach außen in den Lauf gelegt."],
 "Der Verteidiger klebt am Ball und dreht sich nicht weg – der Hinterlaufende ist ohne Gegner unterwegs.",
 "F-Jugend: Der Hinterlaufende braucht keine Flanke – er läuft einfach frei aufs Tor zu und schießt.",
 "hinterlaufen"),
SZ("sz002","angriff","Doppelpass","Doppelpass!",["F","E","D","C","B"],
 "Kurzer Pass, sofortige Rückgabe – am Verteidiger vorbei.",
 ["Pass zum Mitspieler.","Sofort losstarten, am Gegner vorbei.","Der Mitspieler legt den Ball mit einer Berührung in den Lauf zurück."],
 "Der Ball ist schneller als jeder Verteidiger – zwei kurze Pässe schlagen einen Zweikampf.",
 "F-Jugend: „Ich gebe dir den Ball und laufe – du gibst ihn mir sofort wieder.“",
 "doppelpass"),
SZ("sz003","angriff","Klatschen lassen","Klatsch!",["E","D","C","B"],
 "Pass auf den Mitspieler, der ihn direkt zurücklegt – dann geht es woanders weiter.",
 ["Pass in den Fuß des Mitspieler.","Er lässt direkt klatschen, ohne Ball zu stoppen.","Der Ball geht sofort in eine neue Richtung weiter."],
 "Die Verteidiger schieben zum ersten Pass – der zweite geht in den Raum, den sie gerade verlassen haben.",
 "E-Jugend: Sechser klatscht zurück, dann kommt der Steilpass auf den Flügel.",
 "dreieck"),
SZ("sz004","angriff","Steilpass in den Lauf","Steil!",["F","E","D","C","B"],
 "Der Pass geht nicht zum Spieler, sondern dorthin, wo er gleich sein wird.",
 ["Der Mitspieler startet hinter die Abwehr.","Der Ball wird flach vor ihn gespielt – in den freien Raum.","Er muss nicht stehen bleiben, sondern läuft einfach weiter."],
 "Verteidiger schauen auf den Ball. Wenn er in den Rücken gespielt wird, müssen sie drehen – das kostet sie zwei Schritte.",
 "F-Jugend: Der schnellste Spieler startet, Ball einfach in die Lücke rollen lassen.",
 "steilpass"),
SZ("sz005","angriff","Kreuzen","Kreuzen!",["E","D","C","B"],
 "Zwei Spieler laufen aneinander vorbei, einer nimmt den Ball mit.",
 ["Der Ballführende dribbelt quer.","Der Mitspieler läuft ihm entgegen.","Beim Kreuzen wird der Ball übergeben – oder eben nicht (Finte)."],
 "Der Verteidiger weiß eine Sekunde lang nicht, wer den Ball hat.",
 "E-Jugend: Kreuzen an der Mittellinie, danach geht es sofort steil.",
 "kreuzen"),
SZ("sz006","angriff","Verlagern","Rüber!",["E","D","C","B"],
 "Der Ball wechselt schnell auf die andere Seite, wo viel Platz ist.",
 ["Auf der Ballseite stehen viele Gegner.","Kopf hoch: Wer steht auf der anderen Seite allein?","Ein langer, flacher Pass oder zwei schnelle Pässe rüber."],
 "Die ganze gegnerische Mannschaft schiebt zum Ball – die andere Seite bleibt offen.",
 "D-Jugend: Links wird gedrängelt, rechts steht der Flügel ganz allein am Seitenrand.",
 "verlagern"),
SZ("sz007","angriff","Ablegen und drehen","Ableger!",["E","D","C","B"],
 "Der Angreifer mit dem Rücken zum Tor legt den Ball auf den nachrückenden Mitspieler ab.",
 ["Pass auf den Stürmer, der mit dem Rücken zum Tor steht.","Er lässt den Ball prallen – zurück auf den Mitspieler.","Der schaut nach vorne und spielt oder schießt sofort."],
 "Der Ableger schaut schon Richtung Tor, während der Verteidiger noch am Stürmer klebt.",
 "E-Jugend: Ball prallen lassen, der Sechser schiebt ihn direkt in die Spitze.",
 "ablage"),
SZ("sz008","angriff","Dritter Mann","Dritter Mann!",["D","C","B"],
 "Nicht der Passempfänger geht weiter – ein dritter Spieler startet in den Raum.",
 ["A passt zu B.","B klatscht zurück oder legt quer.","C ist schon losgelaufen und bekommt den Ball in die Tiefe."],
 "Alle schauen auf die ersten beiden – der dritte startet unbeobachtet.",
 "D-Jugend: Innenverteidiger auf den Sechser, der klatscht, der Flügel ist längst durchgestartet.",
 "dreieck"),
SZ("sz009","angriff","Diagonaler Lauf","Diagonal!",["E","D","C","B"],
 "Der Flügel läuft schräg in die Mitte, in die Lücke zwischen zwei Verteidigern.",
 ["Der Ballführende hebt den Kopf.","Der Flügel startet schräg nach innen, zwischen die Gegner.","Der Pass kommt flach in die Schnittstelle."],
 "Ein schräger Lauf ist für Verteidiger am schwersten zu verteidigen – sie müssten sich gleichzeitig um Ball und Läufer kümmern.",
 "E-Jugend: „Lauf schräg zur Mitte, nicht gerade nach vorn.“",
 "diagonal"),
SZ("sz010","angriff","Aufdrehen","Dreh auf!",["E","D","C","B"],
 "Ball annehmen, sofort in Richtung Tor drehen statt zurückzuspielen.",
 ["Vor der Annahme schon über die Schulter schauen: Ist jemand hinter mir?","Ist Platz, den Ball mit der ersten Berührung zur Seite mitnehmen.","Kopf hoch – und nach vorne spielen."],
 "Wer sich dreht, spielt nach vorn statt zurück – daraus entstehen die meisten Torchancen.",
 "E-Jugend: „Schau dich um, bevor der Ball kommt.“",
 "aufdrehen"),
SZ("sz011","angriff","Überzahl ausspielen","Zwei gegen einen!",["F","E","D","C","B"],
 "Zwei Angreifer, ein Verteidiger – der Ball entscheidet.",
 ["Der Ballführende läuft den Verteidiger an.","Erst wenn der Verteidiger sich für ihn entscheidet, kommt der Pass.","Der Mitspieler schließt frei ab."],
 "Ein Verteidiger kann nicht zwei Spieler decken. Wichtig ist nur: nicht zu früh abspielen.",
 "F-Jugend: „Lauf ihn an, bis er zu dir kommt – dann gib ab.“",
 "zwei1"),
SZ("sz012","angriff","Breite machen","Macht das Feld groß!",["F","E","D","C","B"],
 "Die Außenspieler stellen sich ganz an die Seitenlinie.",
 ["Außen laufen bis an die Linie.","Der Ballführende bekommt dadurch mehr Platz in der Mitte.","Ein Verlagerungspass wird plötzlich möglich."],
 "Je breiter ihr steht, desto weiter müssen die Gegner laufen – und desto größer werden die Lücken.",
 "F-Jugend: „Ihr klebt alle am Ball wie Bienen – geht auseinander!“",
 "breite"),
SZ("sz013","angriff","Tiefe geben","Einer geht tief!",["E","D","C","B"],
 "Immer soll ein Spieler hinter die Abwehr starten – auch ohne Ball.",
 ["Ein Angreifer bewegt sich kurz entgegen.","Dann dreht er ab und startet in die Tiefe.","Der Ballführende hat sofort eine Option nach vorn."],
 "Die Abwehr muss zurückweichen – dadurch entsteht Platz vor ihr für die anderen.",
 "E-Jugend: Ein Spieler startet immer, auch wenn der Ball nicht kommt.",
 "freilaufen"),
SZ("sz014","angriff","Anbieten und lösen","Löse dich!",["F","E","D","C","B"],
 "Kurz zum Gegner hin, dann schnell weg – so wird man frei.",
 ["Zwei, drei Schritte zum Verteidiger gehen.","Dann explosiv in die andere Richtung wegdrehen.","Sofort Hand oder Ruf: „Hier!“"],
 "Der Verteidiger folgt der ersten Bewegung – die zweite kommt zu schnell.",
 "F-Jugend: „Erst hin, dann weg – wie beim Fangenspielen.“",
 "freilaufen"),
SZ("sz015","angriff","Rochade","Tauschen!",["D","C","B"],
 "Zwei Spieler tauschen die Positionen und ziehen ihre Gegenspieler mit.",
 ["Zwei Spieler laufen gleichzeitig in die Rolle des anderen.","Die Verteidiger müssen entscheiden: mitgehen oder übergeben.","In dem Moment ist einer frei."],
 "Manndeckende Gegner laufen mit und geben ihre Ordnung auf.",
 "D-Jugend: Zehner und Flügel tauschen – die Übergabe klappt beim Gegner selten.",
 "rochade"),
SZ("sz016","angriff","Prallen lassen","Prallen!",["E","D","C","B"],
 "Der Ball wird mit einer Berührung direkt weitergeleitet.",
 ["Pass in den Fuß.","Kein Stoppen – Ball direkt weiterschieben.","Der nächste ist schon in Bewegung."],
 "Ein Ball, der nie stehen bleibt, ist nicht zu verteidigen.",
 "E-Jugend: Zwei Kontakte sind erlaubt, einer ist besser.",
 "dreieck"),
SZ("sz017","angriff","Ball halten","Halt ihn!",["E","D","C","B"],
 "Den Ball mit dem Körper abschirmen, bis Hilfe kommt.",
 ["Körper zwischen Ball und Gegner.","Breit stehen, Arm zur Seite, Blick über die Schulter.","Warten, bis ein Mitspieler anbietet – dann ablegen."],
 "Ballbesitz halten ist oft mehr wert als ein Risikopass.",
 "E-Jugend: „Mach dich breit wie ein Schrank.“",
 "ablage"),
SZ("sz018","angriff","Andribbeln","Dribbel an!",["F","E","D","C","B"],
 "Mit Ball auf den Gegner zulaufen, um ihn zu binden.",
 ["Ball am Fuß Richtung Verteidiger führen.","Warten, bis er wirklich zum Ball geht.","Dann erst passen – jetzt fehlt er woanders."],
 "Ein Verteidiger, der zum Ball geht, deckt seinen Mitspieler nicht mehr ab.",
 "F-Jugend: „Erst hinlaufen, dann abgeben – nicht schon von weitem.“",
 "eins"),
SZ("sz019","angriff","In die Schnittstelle","Schnittstelle!",["D","C","B"],
 "Der Pass geht genau zwischen zwei Verteidiger hindurch.",
 ["Die Lücke zwischen zwei Gegnern suchen.","Mitspieler startet in genau diese Lücke.","Flacher, fester Pass hindurch."],
 "Zwischen zwei Verteidigern fühlt sich keiner zuständig.",
 "D-Jugend: Zwischen Innen- und Außenverteidiger ist fast immer Platz.",
 "steilpass"),
SZ("sz020","angriff","Überlappen","Überlappen!",["E","D","C","B"],
 "Der Außenverteidiger läuft außen am Flügel vorbei nach vorne.",
 ["Der Flügel zieht mit Ball nach innen.","Der Außenverteidiger schiebt außen an ihm vorbei.","Pass nach außen – oder der Flügel zieht selbst durch."],
 "Der Gegner muss sich zwischen zwei Spielern entscheiden.",
 "E-Jugend: Zwei Angreifer auf einer Seite sind fast immer einer zu viel.",
 "hinterlaufen"),
SZ("sz021","angriff","Unterlaufen","Innen durch!",["D","C","B"],
 "Der Mitspieler läuft innen statt außen vorbei.",
 ["Der Ballführende zieht nach außen.","Der Mitspieler startet innen in die Lücke.","Kurzer Pass nach innen."],
 "Alle rechnen mit dem Weg außen herum – innen ist die Tür offen.",
 "D-Jugend: Wenn der Gegner die Außenbahn zustellt, geht es innen.",
 "diagonal"),
SZ("sz022","angriff","Ballführung mit Blick","Kopf hoch!",["F","E","D","C","B"],
 "Beim Dribbling immer wieder aufschauen.",
 ["Ball nah am Fuß führen.","Alle zwei, drei Kontakte kurz hochschauen.","Erst sehen, dann entscheiden."],
 "Wer nur auf den Ball schaut, sieht den freien Mitspieler nicht.",
 "F-Jugend: „Schau mal kurz hoch – wie viele Finger zeige ich?“",
 "eins"),
SZ("sz023","angriff","Tempowechsel","Zack!",["E","D","C","B"],
 "Langsam antäuschen, dann plötzlich beschleunigen.",
 ["Ruhig andribbeln, fast bummeln.","Wenn der Verteidiger stehen bleibt: sofort Vollgas.","Erster Schritt lang, Ball weit vorlegen."],
 "Der Gegner stellt sich auf langsam ein – der Antritt kommt überraschend.",
 "E-Jugend: „Bremsen, dann Rakete.“",
 "eins"),
SZ("sz024","angriff","Ballmitnahme in den Raum","Nimm ihn mit!",["E","D","C","B"],
 "Die erste Berührung geht schon dorthin, wo Platz ist.",
 ["Vor der Annahme schauen, wo frei ist.","Ball mit der ersten Berührung dorthin schieben.","Danach sofort weiterspielen."],
 "Wer den Ball erst stoppt, verliert die halbe Sekunde, die den Unterschied macht.",
 "E-Jugend: „Nimm ihn in die Richtung mit, in die du willst.“",
 "aufdrehen"),
SZ("sz025","angriff","Kurz-Kurz-Lang","Kurz, kurz, lang!",["D","C","B"],
 "Zwei kurze Pässe locken den Gegner an, der dritte geht lang.",
 ["Zwei kurze Pässe auf engem Raum.","Die Gegner schieben heran.","Dann der lange Ball in den freien Raum."],
 "Der Gegner rückt nach den kurzen Pässen auf – dahinter wird es leer.",
 "D-Jugend: Zwei Pässe hinten, dann der Ball in den Lauf des Stürmers.",
 "verlagern"),
SZ("sz026","angriff","Rückpass zum Neuaufbau","Zurück und neu!",["D","C","B"],
 "Geht nach vorne nichts, wird zurückgespielt und neu angesetzt.",
 ["Kein Weg nach vorn? Nicht wegschlagen.","Ruhig zurück zum freien Mitspieler.","Von dort auf die andere Seite verlagern."],
 "Ein Rückpass ist kein Fehler – ein verlorener Ball schon.",
 "D-Jugend: Lieber zweimal aufbauen als einmal verlieren.",
 "verlagern"),
SZ("sz027","angriff","Zweikampf suchen","Geh in den Zweikampf!",["F","E","D"],
 "Im 1 gegen 1 mutig sein und den Gegner ausspielen.",
 ["Mit Tempo auf den Verteidiger zu.","Eine Finte – Körpertäuschung reicht.","Am Gegner vorbei und weiter Richtung Tor."],
 "In der F- und E-Jugend gewinnt Mut mehr Spiele als Taktik.",
 "F-Jugend: „Trau dich – dribbeln ist erlaubt und erwünscht!“",
 "eins"),
SZ("sz028","angriff","Doppelpass über die Spitze","Über die Spitze!",["D","C","B"],
 "Der Stürmer dient als Wand für den nachrückenden Mitspieler.",
 ["Pass auf den Stürmer.","Der legt mit einem Kontakt in den Lauf zurück.","Der Mitspieler läuft mit Tempo durch."],
 "Die Innenverteidiger sind am Stürmer gebunden und sehen den Nachrückenden zu spät.",
 "D-Jugend: Sechser spielt an, Zehner läuft durch.",
 "ablage"),
SZ("sz029","angriff","Freilaufen im Rücken","Geh in den Rücken!",["D","C","B"],
 "Sich hinter dem Gegenspieler positionieren, wo er nicht hinsieht.",
 ["In den Rücken des Gegenspielers gehen.","Kurz warten, bis er zum Ball schaut.","Genau dann in den freien Raum starten."],
 "Verteidiger können Ball und Gegner nicht gleichzeitig sehen.",
 "D-Jugend: Immer im Toten Winkel bleiben.",
 "freilaufen"),
SZ("sz030","angriff","Kombination im Dreieck","Dreieck!",["E","D","C","B"],
 "Drei Spieler stehen im Dreieck – so gibt es immer zwei Anspielstationen.",
 ["Nie in einer Reihe stehen.","Immer versetzt: einer vor, einer neben, einer hinter dem Ball.","Zwei schnelle Pässe, dann weiter."],
 "Im Dreieck ist der Weg des Balles kurz und der Gegner kommt nie hinterher.",
 "E-Jugend: „Bildet Dreiecke – niemals eine Linie.“",
 "dreieck"),
SZ("sz031","angriff","Anspiel und Nachrücken","Pass und nachrücken!",["F","E","D","C","B"],
 "Nach dem Pass nicht stehen bleiben, sondern weiterlaufen.",
 ["Pass spielen.","Sofort weiterlaufen – nie zuschauen.","Neue Anspielstation anbieten."],
 "Ein Spieler, der nach dem Pass stehen bleibt, ist für den Angriff verloren.",
 "F-Jugend: „Pass und lauf – nicht Pass und Pause.“",
 "doppelpass"),
SZ("sz032","angriff","Kurzer Pfosten – langer Pfosten","Langer Pfosten!",["D","C","B"],
 "Ein Spieler zieht zum kurzen Pfosten, der Ball geht an den langen.",
 ["Ein Angreifer läuft zum kurzen Pfosten.","Die Verteidiger folgen ihm.","Der Ball wird an den langen Pfosten gespielt, wo der zweite frei einläuft."],
 "Die Abwehr rückt zum ersten Läufer – hinten wird es leer.",
 "D-Jugend: Der zweite Angreifer kommt fast immer frei zum Abschluss.",
 "flanke"),
SZ("sz033","angriff","Ball und Gegner trennen","Weg vom Gegner!",["E","D","C","B"],
 "Den Ball dorthin mitnehmen, wo der Gegner nicht ist.",
 ["Erste Berührung weg vom Gegenspieler.","Zwischen Ball und Gegner bleibt der eigene Körper.","Dann in Ruhe weiterspielen."],
 "So gewinnt man Zeit, ohne überhaupt in den Zweikampf zu müssen.",
 "E-Jugend: „Nimm ihn zur freien Seite mit.“",
 "aufdrehen"),
SZ("sz034","angriff","Der lange Ball über die Kette","Lang!",["E","D","C","B"],
 "Wenn die Abwehr sehr hoch steht, geht der Ball einfach darüber.",
 ["Die gegnerische Abwehr steht weit vorne.","Ein schneller Spieler startet.","Der Ball wird hinter die Abwehr gespielt."],
 "Eine hoch stehende Abwehr hat immer viel Platz im Rücken.",
 "E-Jugend: Ein Ball, ein Lauf, ein Tor – manchmal ist einfach am besten.",
 "steilpass"),
SZ("sz035","angriff","Über den Torwart aufbauen","Zurück zum Keeper!",["D","C","B"],
 "Der Torwart spielt mit und schafft dadurch einen Spieler mehr.",
 ["Kein Weg nach vorn: Rückpass zum Torwart.","Der Torwart schaut, wo der Gegner nicht ist.","Von dort geht es auf der anderen Seite weiter."],
 "Mit dem Torwart hat man immer einen Spieler mehr als der Gegner.",
 "D-Jugend: Nur bei sicherem Untergrund und ruhiger Situation.",
 "twaufbau"),
SZ("sz036","angriff","Ball fordern","Ruf ihn!",["G","F","E","D","C","B"],
 "Wer den Ball will, muss sich melden – laut und deutlich.",
 ["Hand hoch oder Namen rufen.","Zeigen, auf welchen Fuß der Ball soll.","Blickkontakt suchen."],
 "Der Ballführende schaut dorthin, wo er etwas hört.",
 "G-Jugend: „Wer nicht ruft, kriegt keinen Ball.“",
 "freilaufen"),
SZ("sz037","angriff","Zurücklegen","Leg zurück!",["D","C","B"],
 "Von der Grundlinie den Ball nach hinten an den Sechzehner legen.",
 ["Bis zur Grundlinie durchgehen.","Nicht hoch flanken, sondern flach zurücklegen.","Der Nachrückende schießt aus dem Lauf."],
 "Die ganze Abwehr schaut nach vorne zum Tor – hinter ihr steht keiner.",
 "D-Jugend: Der Ball an den Fünfmeterrand zurück ist die sicherste Flanke.",
 "flanke"),
SZ("sz038","angriff","Anspiel auf den Sechser","Über den Sechser!",["D","C","B"],
 "Der zentrale Mittelfeldspieler wird gesucht, weil er in alle Richtungen spielen kann.",
 ["Der Sechser bietet sich zwischen den Gegnern an.","Pass in seinen Fuß.","Er dreht auf und verteilt."],
 "Aus der Mitte gibt es Anspielstationen nach beiden Seiten.",
 "D-Jugend: Der Sechser ist der Verteiler – ihn immer suchen.",
 "aufdrehen"),
SZ("sz039","angriff","Aus der Tiefe kommen","Komm aus der Tiefe!",["C","B"],
 "Ein Spieler startet aus dem Mittelfeld heraus in den Strafraum.",
 ["Der Stürmer bindet die Innenverteidiger.","Aus der zweiten Reihe kommt ein Spieler mit Anlauf.","Der Ball wird in seinen Lauf gelegt."],
 "Verteidiger orientieren sich an ihrem Gegenspieler – der Läufer aus der Tiefe hat keinen.",
 "C-Jugend: Der Achter ist der gefährlichste Torschütze, wenn er spät kommt.",
 "diagonal"),
SZ("sz040","angriff","Sperre stellen","Stell dich rein!",["C","B"],
 "Ein Mitspieler stellt sich in den Laufweg des Verteidigers.",
 ["Der Ballführende zieht in eine Richtung.","Ein Mitspieler stellt sich – ohne Foul – in den Weg des Verfolgers.","Der Ballführende ist frei."],
 "Der Verteidiger muss einen Umweg laufen und verliert Anschluss.",
 "C-Jugend: Legal ist es nur, wenn man einfach stehen bleibt.",
 "block"),
];

// =================== 2) AUSSEN & FLANKE ===================
const SZ_AUSSEN = [
SZ("sz041","aussen","Flanke von der Grundlinie","Bis zur Linie!",["E","D","C","B"],
 "Erst bis zur Grundlinie durchgehen, dann hereingeben.",
 ["Außen mit Tempo an der Linie entlang.","Erst an der Grundlinie hereingeben.","Zwei Mitspieler laufen ein: kurzer und langer Pfosten."],
 "Von der Grundlinie schaut die Abwehr zum eigenen Tor – jeder Ball ist gefährlich.",
 "E-Jugend: Flach und scharf in den Fünfmeterraum reicht völlig.",
 "flanke"),
SZ("sz042","aussen","Flanke von halbrechts","Rein damit!",["D","C","B"],
 "Früh hereingeben, bevor der Verteidiger den Weg zumacht.",
 ["Der Flügel hat Platz vor sich.","Kurz aufschauen: Wer läuft ein?","Ball scharf und flach in den Rückraum."],
 "Die frühe Hereingabe kommt, bevor die Abwehr sortiert ist.",
 "D-Jugend: Lieber flach und scharf als hoch und langsam.",
 "flanke",{r:true}),
SZ("sz043","aussen","Nach innen ziehen","Zieh nach innen!",["E","D","C","B"],
 "Der Flügel dribbelt nach innen und sucht den Abschluss oder den Pass.",
 ["Ball auf den ballfernen Fuß nehmen.","Diagonal in die Mitte ziehen.","Schuss oder Pass in die Schnittstelle."],
 "Der Verteidiger stellt meist die Linie zu – nach innen ist mehr Platz.",
 "E-Jugend: Linksfuß rechts außen zieht nach innen und schießt.",
 "diagonal"),
SZ("sz044","aussen","Außen hinterlaufen lassen","Er kommt außen!",["E","D","C","B"],
 "Der Flügel zieht nach innen, der Außenverteidiger überholt außen.",
 ["Flügel zieht mit Ball nach innen.","Der Außenverteidiger startet außen vorbei.","Pass nach außen in den freien Raum."],
 "Zwei Angreifer auf einer Seite gegen einen Verteidiger – das geht fast immer auf.",
 "E-Jugend: Der Hintermann ruft laut „Außen!“",
 "hinterlaufen"),
SZ("sz045","aussen","Doppelpass auf dem Flügel","Doppelpass außen!",["E","D","C","B"],
 "Kurzer Doppelpass an der Seitenlinie.",
 ["Pass nach innen zum Mitspieler.","Sofort außen an der Linie durchstarten.","Rückpass in den Lauf."],
 "An der Linie hat der Verteidiger wenig Platz zum Reagieren.",
 "E-Jugend: Auf engem Raum ist der Doppelpass der beste Trick.",
 "doppelpass"),
SZ("sz046","aussen","Verlagern und flanken","Rüber und rein!",["D","C","B"],
 "Erst die Seite wechseln, dann sofort hereingeben.",
 ["Ball schnell auf die freie Seite.","Der Flügel nimmt ihn im Lauf mit.","Direkt hereingeben, bevor die Abwehr steht."],
 "Nach einer Verlagerung braucht die Abwehr drei Sekunden – die reichen für die Flanke.",
 "D-Jugend: Ein Kontakt annehmen, der zweite ist die Flanke.",
 "verlagern"),
SZ("sz047","aussen","Doppeln auf dem Flügel vermeiden","Nicht zu zweit außen!",["D","C","B"],
 "Nicht beide Angreifer in dieselbe Ecke laufen.",
 ["Einer geht außen in die Tiefe.","Der zweite bleibt in der Mitte anspielbar.","So gibt es zwei Wege statt einer Sackgasse."],
 "Zwei Spieler in derselben Ecke machen dem Gegner das Verteidigen leicht.",
 "D-Jugend: „Einer außen reicht – der andere in die Mitte.“",
 "breite"),
SZ("sz048","aussen","Einwurf nach vorne","Einwurf hoch!",["E","D","C","B"],
 "Der Einwurf geht nach vorne auf den startenden Mitspieler.",
 ["Der vordere Spieler startet an der Linie entlang.","Einwurf flach vor ihn.","Er nimmt ihn im Lauf mit."],
 "Die meisten Einwürfe gehen zurück – ein Einwurf nach vorn überrascht.",
 "E-Jugend: Vorher abklären, wer startet.",
 "einwurf"),
SZ("sz049","aussen","Einwurf klatschen lassen","Klatsch beim Einwurf!",["E","D","C","B"],
 "Ball auf den Mitspieler, der ihn direkt zurücklegt.",
 ["Einwurf in den Fuß des nächsten Mitspielers.","Der klatscht direkt zurück.","Der Einwerfer läuft ins Feld und spielt weiter."],
 "Der Einwerfer ist immer frei – ihn deckt fast nie jemand.",
 "E-Jugend: Nach dem Wurf sofort ins Feld laufen.",
 "einwurf"),
SZ("sz050","aussen","Flanke auf den Rückraum","In den Rückraum!",["D","C","B"],
 "Der Ball geht nicht in die Mitte, sondern zurück an den Sechzehner.",
 ["Von der Grundlinie zurücklegen.","Der Nachrückende kommt mit Anlauf.","Direktschuss aus dem Rückraum."],
 "Im Rückraum steht selten ein Verteidiger.",
 "D-Jugend: Der zweite Ball nach der Flanke ist oft der gefährlichste.",
 "flanke"),
SZ("sz051","aussen","Frühe Hereingabe","Früh rein!",["D","C","B"],
 "Schon vor dem Strafraum hereingeben, wenn die Abwehr offen steht.",
 ["Kopf hoch: Ist die Abwehr unsortiert?","Früh und flach in den Lauf des Stürmers.","Nicht auf die Grundlinie warten."],
 "Wenn die Abwehr noch läuft, muss man nicht bis zur Linie durch.",
 "D-Jugend: Beim Umschalten ist die frühe Hereingabe Gold wert.",
 "flanke",{r:true}),
SZ("sz052","aussen","Außen binden, innen spielen","Bind ihn außen!",["C","B"],
 "Der Flügel bindet zwei Gegner, der Pass geht nach innen.",
 ["Flügel dribbelt Richtung Linie.","Zwei Verteidiger gehen hin.","Pass in die entstandene Lücke in der Mitte."],
 "Jeder Gegner am Flügel fehlt in der Mitte.",
 "C-Jugend: Erst binden, dann verlagern.",
 "diagonal"),
SZ("sz053","aussen","Grundlinie – Ball halten","Halt ihn an der Linie!",["D","C","B"],
 "In der Ecke abschirmen und auf Unterstützung warten.",
 ["Körper zwischen Ball und Gegner.","In die Ecke drehen, Zeit gewinnen.","Zurück legen, wenn Hilfe kommt."],
 "Ballbesitz in der Ecke hält den Gegner beschäftigt und beruhigt das Spiel.",
 "D-Jugend: Sinnvoll bei knapper Führung.",
 "ablage"),
SZ("sz054","aussen","Übersteiger außen","Übersteiger!",["E","D","C","B"],
 "Mit einer Körpertäuschung am Außenverteidiger vorbei.",
 ["Ball vor dem Verteidiger kurz stoppen.","Fuß über den Ball, Körper zur einen Seite.","Mit dem anderen Fuß in die andere Richtung antreten."],
 "Die Körpertäuschung zieht den Verteidiger auf den falschen Fuß.",
 "E-Jugend: Nur eine Finte reicht – dafür schnell.",
 "eins"),
SZ("sz055","aussen","Flügelwechsel im Lauf","Seitenwechsel!",["C","B"],
 "Die Außenspieler tauschen im Spiel die Seiten.",
 ["Beide Flügel starten zur gegenüberliegenden Seite.","Die Verteidiger müssen übergeben.","Dabei entsteht immer eine Lücke."],
 "Positionswechsel bringen manndeckende Gegner aus der Ordnung.",
 "C-Jugend: Einmal pro Halbzeit reicht als Überraschung.",
 "rochade"),
];

// =================== 3) ABSCHLUSS ===================
const SZ_ABSCHLUSS = [
SZ("sz056","abschluss","Torschuss nach Zuspiel","Und Schuss!",["F","E","D","C","B"],
 "Ball annehmen und sofort aufs Tor schießen.",
 ["Der Ball kommt flach aus der Mitte.","Erste Berührung nach vorne in Schussrichtung.","Zweite Berührung ist der Schuss."],
 "Je weniger Kontakte, desto weniger Zeit hat der Torwart.",
 "F-Jugend: Auf die großen F-Jugend-Tore schießen macht besonders Spaß – Innenseite reicht.",
 "eins"),
SZ("sz057","abschluss","Innenseite ins lange Eck","Langes Eck!",["F","E","D","C","B"],
 "Mit der Innenseite platziert schießen statt fest.",
 ["Standbein neben den Ball.","Innenseite fest, Ball flach halten.","Ziel: das lange Eck, flach am Torwart vorbei."],
 "Flach ins lange Eck ist der Schuss, den Torhüter am schwersten halten.",
 "F-Jugend: „Schieß, wie du passt – nur fester.“",
 "eins"),
SZ("sz058","abschluss","Schuss nach Dribbling","Zieh ab!",["F","E","D","C","B"],
 "Nach dem Dribbling sofort abschließen, statt weiter zu dribbeln.",
 ["Am Verteidiger vorbei.","Ball einmal richtig vorlegen.","Schuss aus der Bewegung."],
 "Nach dem Vorbeigehen ist der Weg zum Tor kurz – jetzt zählt Mut.",
 "F-Jugend: „Wenn du das Tor siehst: schieß!“",
 "eins"),
SZ("sz059","abschluss","1 gegen Torwart","Allein vorm Tor!",["F","E","D","C","B"],
 "Ruhig bleiben, den Torwart aussteigen lassen.",
 ["Mit Tempo aufs Tor zu.","Warten, bis der Torwart sich bewegt.","Am ihm vorbeischieben statt draufhauen."],
 "Der Torwart macht den ersten Fehler, wenn man ruhig bleibt.",
 "F-Jugend: „Schieb ihn einfach am Torwart vorbei.“",
 "eins"),
SZ("sz060","abschluss","Direktabnahme","Direkt!",["E","D","C","B"],
 "Der Querpass wird ohne Annahme verwandelt.",
 ["Der Ball kommt flach quer.","Nicht stoppen – direkt schießen.","Fuß fest, Ball flach halten."],
 "Der Torwart kann sich nicht neu ausrichten.",
 "E-Jugend: Zielen reicht, feste Schüsse gehen meist drüber.",
 "zwei1"),
SZ("sz061","abschluss","Abschluss auf das große F-Jugend-Tor","Aufs große Tor!",["F","E"],
 "Im Training auf die großen Tore schießen, wie im Spiel.",
 ["Ball aus 8–10 Metern.","Anlauf leicht schräg.","Fest und platziert in die Ecken."],
 "Im Spiel wird auf die großen Tore geschossen – also muss man sie auch im Training treffen.",
 "F-Jugend: Ecken mit Hütchen markieren – Treffer geben Punkte.",
 "eins"),
SZ("sz062","abschluss","Schuss aus dem Rückraum","Aus der zweiten Reihe!",["D","C","B"],
 "Der nachrückende Spieler schießt vom Sechzehner.",
 ["Der Ball wird von der Grundlinie zurückgelegt.","Der Nachrückende kommt mit Anlauf.","Voller Spann, Ball flach halten."],
 "Die Abwehr schaut nach vorn und stellt den Rückraum nicht zu.",
 "D-Jugend: Auf den Nachschuss immer jemanden mitlaufen lassen.",
 "flanke"),
SZ("sz063","abschluss","Abstauben","Geh auf den Abpraller!",["F","E","D","C","B"],
 "Immer nachlaufen – der Abpraller kommt öfter als man denkt.",
 ["Ein Mitspieler schießt.","Sofort Richtung Tor nachlaufen.","Abpraller vom Torwart einschieben."],
 "Fast jedes zweite Tor im Kinderfußball fällt nach einem Abpraller.",
 "F-Jugend: „Nach jedem Schuss hinterher!“",
 "eins"),
SZ("sz064","abschluss","Kopfball nach Flanke","Kopf!",["D","C","B"],
 "Mit Anlauf zum Ball springen und ihn nach unten köpfen.",
 ["Anlauf nehmen, nicht stehen bleiben.","Mit der Stirn treffen, Augen auf.","Nach unten köpfen – schwerer zu halten."],
 "Kopfbälle nach unten springen vor dem Torwart auf.",
 "D-Jugend: Erst mit weichen Bällen üben.",
 "flanke"),
SZ("sz065","abschluss","Volleyschuss","Volley!",["D","C","B"],
 "Den Ball aus der Luft nehmen.",
 ["Ball genau beobachten.","Standbein fest, Knie über dem Ball.","Spann treffen, Ball nach unten drücken."],
 "Ein Volleyschuss kommt schnell und unerwartet.",
 "D-Jugend: Technik geht vor Härte.",
 "eins"),
SZ("sz066","abschluss","Schuss ins kurze Eck","Kurzes Eck!",["E","D","C","B"],
 "Wenn der Torwart zu weit in der Mitte steht, ist das kurze Eck offen.",
 ["Kurz hochschauen: Wo steht der Torwart?","Ist er zu weit weg vom Pfosten: kurzes Eck.","Fest und flach."],
 "Junge Torhüter stehen oft zu zentral.",
 "E-Jugend: Einmal hinschauen entscheidet.",
 "eins",{r:true}),
SZ("sz067","abschluss","Torschuss nach Ablage","Ableger und Schuss!",["E","D","C","B"],
 "Der Stürmer legt ab, der Nachrückende schießt.",
 ["Pass auf den Stürmer mit dem Rücken zum Tor.","Ablage in den Lauf.","Direktschuss."],
 "Der Schütze läuft an, die Abwehr steht.",
 "E-Jugend: Immer laut „Ableger!“ rufen.",
 "ablage"),
SZ("sz068","abschluss","Elfmeter sicher verwandeln","Ruhig bleiben!",["E","D","C","B"],
 "Vorher entscheiden, wohin – und dabei bleiben.",
 ["Ecke vor dem Anlauf festlegen.","Nicht zum Torwart schauen.","Fest und platziert, halbhoch reicht."],
 "Wer während des Anlaufs die Meinung ändert, verschießt.",
 "E-Jugend: Ecke aussuchen und durchziehen.",
 "freistoss"),
SZ("sz069","abschluss","Nachsetzen beim Torwart","Bleib dran!",["F","E","D"],
 "Nach dem Abschluss den Torwart unter Druck setzen.",
 ["Nach dem Schuss weiterlaufen.","Beim Torwart in der Nähe bleiben.","Auf den zweiten Ball reagieren."],
 "Torhüter fangen im Kinderfußball selten sicher.",
 "F-Jugend: Immer bis zum Ende laufen.",
 "gegenpressing"),
SZ("sz070","abschluss","Abschluss mit dem schwachen Fuß","Beide Füße!",["E","D","C","B"],
 "Auch der schwache Fuß muss schießen dürfen.",
 ["Ball auf die schwache Seite vorlegen.","Nicht umständlich zurückdrehen.","Innenseite, platziert."],
 "Wer umdreht, verliert die Chance – der schwache Fuß ist besser als kein Schuss.",
 "E-Jugend: Jede Woche fünf Minuten schwacher Fuß.",
 "eins",{r:true}),
];

// =================== 4) SPIELAUFBAU ===================
const SZ_AUFBAU = [
SZ("sz071","aufbau","Auffächern","Fächert auf!",["E","D","C","B"],
 "Die Innenverteidiger gehen beim Aufbau weit auseinander.",
 ["Torwart hat den Ball.","Die Verteidiger gehen breit in die Ecken des Strafraums.","Der Sechser bietet sich in der Mitte an."],
 "Je breiter der Aufbau, desto weiter müssen die Angreifer laufen.",
 "E-Jugend: „Geht auseinander, wenn der Torwart den Ball hat.“",
 "twaufbau"),
SZ("sz072","aufbau","Sechser fällt ab","Sechser rein!",["D","C","B"],
 "Der Sechser lässt sich zwischen die Verteidiger fallen.",
 ["Die Gegner stellen die Mitte zu.","Der Sechser geht zwischen die Innenverteidiger.","Jetzt sind es drei gegen zwei im Aufbau."],
 "Ein Spieler mehr im Aufbau bedeutet immer einen freien Spieler.",
 "D-Jugend: Der Sechser muss laut rufen, wenn er kommt.",
 "twaufbau"),
SZ("sz073","aufbau","Flach herausspielen","Flach raus!",["D","C","B"],
 "Statt weit zu schlagen wird der Ball flach herausgespielt.",
 ["Torwart rollt auf den freien Verteidiger.","Der nimmt den Ball in die freie Richtung mit.","Erster Pass nach vorn, sobald jemand frei ist."],
 "Flach herausgespielte Bälle bleiben in den eigenen Reihen – lange Bälle selten.",
 "D-Jugend: Nur, wenn wirklich jemand frei steht.",
 "twaufbau"),
SZ("sz074","aufbau","Sicherer langer Ball","Lang und sicher!",["F","E","D","C","B"],
 "Wenn der Gegner hoch presst: einfach lang, aber zielgerichtet.",
 ["Kein freier Mitspieler in der Nähe.","Auf die Seite spielen, auf der wir mehr Spieler haben.","Alle rücken sofort nach, um den zweiten Ball zu holen."],
 "Ein langer Ball ist kein Fehler – ein Ballverlust im eigenen Strafraum schon.",
 "F-Jugend: Sicherheit geht immer vor.",
 "verlagern"),
SZ("sz075","aufbau","Zwischen die Linien","Zwischen die Reihen!",["D","C","B"],
 "Ein Spieler stellt sich zwischen die gegnerischen Reihen.",
 ["Zwischen Abwehr und Mittelfeld des Gegners stellen.","Ball fordern.","Aufdrehen und nach vorne spielen."],
 "Zwischen den Reihen fühlt sich kein Gegner zuständig.",
 "D-Jugend: Der Zehner lebt in diesem Raum.",
 "aufdrehen"),
SZ("sz076","aufbau","Anspielstationen bilden","Bietet euch an!",["F","E","D","C","B"],
 "Immer mindestens zwei Mitspieler in Ballnähe anbieten.",
 ["Einer bietet sich seitlich an.","Einer hinter dem Ball zur Absicherung.","Einer in die Tiefe."],
 "Wer keine Anspielstation hat, verliert den Ball – das ist selten die Schuld des Ballführenden.",
 "F-Jugend: „Der Ballführende soll immer drei sehen.“",
 "dreieck"),
SZ("sz077","aufbau","Torwart als Anspielstation","Zurück ist erlaubt!",["E","D","C","B"],
 "Der Torwart wird bewusst mit einbezogen.",
 ["Rückpass zum Torwart, wenn es vorne dicht ist.","Der Torwart nimmt an und schaut hoch.","Verlagerung auf die freie Seite."],
 "Ein Rückpass entlastet und öffnet das Spiel neu.",
 "E-Jugend: Nur mit dem Fuß spielen, nicht in die Hand.",
 "twaufbau"),
SZ("sz078","aufbau","Außenverteidiger hoch","Außen schiebt hoch!",["D","C","B"],
 "Der Außenverteidiger schiebt weit nach vorne und gibt Breite.",
 ["Innenverteidiger haben den Ball.","Der Außenverteidiger schiebt an die Linie nach vorn.","Diagonaler Pass nach außen."],
 "Der Gegner muss ausschieben und öffnet die Mitte.",
 "D-Jugend: Immer nur ein Außenverteidiger gleichzeitig.",
 "breite"),
SZ("sz079","aufbau","Pressingfalle überspielen","Über die Kette!",["C","B"],
 "Bewusst das Pressing anlocken und dann darüber spielen.",
 ["Kurze Pässe hinten, damit der Gegner aufrückt.","Ein Spieler startet in den Rücken der Kette.","Ball hoch oder flach darüber."],
 "Wer hoch presst, hat hinten wenig Absicherung.",
 "C-Jugend: Vorher absprechen, wer startet.",
 "steilpass"),
SZ("sz080","aufbau","Ruhe im Aufbau","Ganz ruhig!",["E","D","C","B"],
 "Das Tempo herausnehmen und den Ball sicher laufen lassen.",
 ["Kein Gegner in der Nähe? Ball ruhig halten.","Quer und zurück ist erlaubt.","Warten, bis vorne ein Weg aufgeht."],
 "Hektik führt zu Fehlpässen – Ruhe schafft Lösungen.",
 "E-Jugend: „Ihr habt Zeit – schaut euch um.“",
 "verlagern"),
SZ("sz081","aufbau","Gegenbewegung","Erst hin, dann weg!",["E","D","C","B"],
 "Kurz entgegenkommen, dann in die Tiefe starten.",
 ["Zwei Schritte zum Ball hin.","Der Verteidiger folgt.","Dann Richtungswechsel und tief starten."],
 "Der Gegner ist im falschen Rhythmus und kann nicht sofort drehen.",
 "E-Jugend: Immer mit Tempowechsel.",
 "freilaufen"),
SZ("sz082","aufbau","Dritter Mann im Aufbau","Dritter im Aufbau!",["C","B"],
 "Zwei Pässe hinten locken – der dritte Spieler startet.",
 ["Innenverteidiger auf Sechser.","Sechser klatscht zurück.","Der Achter ist bereits in den Raum gestartet."],
 "Alle schauen auf den Klatschball – der dritte Spieler ist frei.",
 "C-Jugend: Braucht Übung, wirkt aber immer.",
 "dreieck"),
SZ("sz083","aufbau","Absicherung beim Aufbau","Einer bleibt hinten!",["D","C","B"],
 "Beim Aufbau bleibt immer ein Spieler zur Absicherung.",
 ["Wenn zwei nach vorne schieben, bleibt einer zurück.","Er steht hinter dem Ball, nicht daneben.","So ist bei Ballverlust jemand da."],
 "Ein abgesicherter Aufbau kostet nichts, verhindert aber Konter.",
 "D-Jugend: „Wer bleibt hinten? Immer klären.“",
 "absichern"),
SZ("sz084","aufbau","Abstoß kurz","Abstoß kurz!",["E","D","C","B"],
 "Der Abstoß geht kurz zum Verteidiger, nicht weit nach vorn.",
 ["Verteidiger stellen sich breit in die Ecken.","Kurzer, flacher Abstoß.","Sofort weiterspielen, bevor der Gegner da ist."],
 "Nach dem Regelwechsel darf der Ball im Strafraum angenommen werden – ein großer Vorteil.",
 "E-Jugend: Klare Ansage des Torwarts.",
 "twaufbau"),
SZ("sz085","aufbau","Erster Pass nach vorn","Erster Blick nach vorn!",["D","C","B"],
 "Nach dem Ballgewinn zuerst schauen, ob es nach vorne geht.",
 ["Ball erobert.","Sofort den Kopf heben.","Erst wenn vorne nichts geht, quer oder zurück."],
 "Direkt nach dem Ballgewinn ist der Gegner am unsortiertesten.",
 "D-Jugend: Der erste Blick geht immer nach vorn.",
 "konter"),
];

// =================== 5) PRESSING & EROBERN ===================
const SZ_PRESSING = [
SZ("sz086","pressing","Anlaufen und lenken","Lenk ihn!",["E","D","C","B"],
 "Der erste Spieler läuft so an, dass der Gegner nur nach außen kann.",
 ["Schräg anlaufen, nicht frontal.","Den Weg in die Mitte mit dem Körper zumachen.","Der Gegner spielt nach außen – dort wartet der Mitspieler."],
 "Wer den Gegner lenkt, weiß vorher, wohin der Ball geht.",
 "E-Jugend: „Lauf so, dass er nur nach außen kann.“",
 "lenken"),
SZ("sz087","pressing","Zu zweit stellen","Doppelt!",["E","D","C","B"],
 "Zwei Spieler stellen den Ballführenden gleichzeitig.",
 ["Der erste stellt den Weg nach vorne zu.","Der zweite kommt von der Seite.","Zusammen den Ball erobern."],
 "Zu zweit gewinnt man den Ball fast immer.",
 "E-Jugend: Nur an der Seitenlinie doppeln, dort hilft die Linie mit.",
 "doppeln"),
SZ("sz088","pressing","Pressingauslöser Rückpass","Jetzt drauf!",["D","C","B"],
 "Beim Rückpass des Gegners startet das Pressing.",
 ["Der Gegner spielt zurück.","Sofort alle gemeinsam nach vorne.","Anspielstationen zustellen."],
 "Ein Rückpass ist langsam – in dieser Zeit ist die Mannschaft schon da.",
 "D-Jugend: Ein klarer Auslöser reicht, alle müssen ihn kennen.",
 "gegenpressing"),
SZ("sz089","pressing","Pressingauslöser schlechte Annahme","Drauf!",["E","D","C","B"],
 "Springt der Ball weg, wird sofort attackiert.",
 ["Der Gegner nimmt den Ball schlecht an.","Der nächste Spieler geht sofort drauf.","Die anderen rücken nach."],
 "Ein Gegner, der dem Ball hinterherläuft, kann ihn nicht schützen.",
 "E-Jugend: „Wenn der Ball springt: los!“",
 "gegenpressing"),
SZ("sz090","pressing","Gegenpressing","Sofort zurück!",["D","C","B"],
 "Direkt nach Ballverlust den Ball zurückerobern.",
 ["Ball verloren.","Die drei nächsten Spieler gehen sofort drauf.","Kein Zurücklaufen, sondern Druck."],
 "In den ersten fünf Sekunden nach Ballverlust ist der Gegner am unsortiertesten.",
 "D-Jugend: Fünf Sekunden Vollgas, dann geordnet zurück.",
 "gegenpressing"),
SZ("sz091","pressing","Passweg zustellen","Schatten!",["D","C","B"],
 "Beim Anlaufen den Passweg mit dem eigenen Körper abdecken.",
 ["Gefährlichsten Mitspieler des Gegners im Rücken lassen.","Schräg anlaufen, sodass dieser Passweg zu ist.","Den Gegner in die ungefährliche Richtung drängen."],
 "So verteidigt ein Spieler zwei Gegner gleichzeitig.",
 "D-Jugend: „Stell dich in den Schatten des Passwegs.“",
 "lenken"),
SZ("sz092","pressing","Hoch anlaufen beim Abstoß","Ganz nach vorn!",["D","C","B"],
 "Beim kurzen Abstoß wird der Gegner sofort gestört.",
 ["Der Gegner will kurz herausspielen.","Die Angreifer stellen die Verteidiger zu.","Der Rest der Mannschaft schiebt nach."],
 "Ein Ballgewinn nahe am gegnerischen Tor ist die beste Torchance.",
 "D-Jugend: Nur, wenn wirklich alle mitschieben.",
 "lenken"),
SZ("sz093","pressing","Abwarten und kompakt stehen","Bleibt kompakt!",["E","D","C","B"],
 "Nicht wild anlaufen, sondern eng zusammen stehen.",
 ["Alle Reihen eng zusammen.","Erst attackieren, wenn der Ball in unsere Zone kommt.","Ruhig bleiben, nicht hinterherlaufen."],
 "Eine kompakte Mannschaft hat keine Lücken – der Gegner muss außen herum.",
 "E-Jugend: „Bleibt zusammen wie eine Traube.“",
 "kette"),
SZ("sz094","pressing","Seitenlinie als Helfer","Ab an die Linie!",["D","C","B"],
 "Den Gegner zur Linie lenken und dort stellen.",
 ["Anlaufen von innen nach außen.","Der Gegner hat nur noch die Linie.","Dort zu zweit stellen."],
 "Die Seitenlinie verteidigt mit – dahinter ist niemand.",
 "D-Jugend: Die Außenlinie ist der beste Mitspieler.",
 "doppeln"),
SZ("sz095","pressing","Nach dem Einwurf pressen","Beim Einwurf drauf!",["E","D","C","B"],
 "Beim gegnerischen Einwurf sofort Druck machen.",
 ["Alle Anspielstationen decken.","Der Einwerfer hat kaum Optionen.","Beim ersten Kontakt sofort attackieren."],
 "Ein Einwurf ist immer ein schlechter Ballbesitz – da kann man ihn holen.",
 "E-Jugend: Zählen hilft: „Wer hat wen?“",
 "gegenpressing"),
SZ("sz096","pressing","Rückwärtspressing","Hinterher!",["D","C","B"],
 "Auch nach hinten arbeiten und den Gegner von hinten stören.",
 ["Der Gegner läuft an uns vorbei.","Nicht aufgeben, sondern hinterherlaufen.","Von hinten den Ball stören, nicht foulen."],
 "Viele Angriffe sterben, weil jemand nachgesetzt hat.",
 "D-Jugend: Aufgeben ist nie eine Option.",
 "gegenpressing"),
SZ("sz097","pressing","Erste Reihe überspielen verhindern","Keiner zwischen uns!",["C","B"],
 "Den Raum hinter der ersten Pressinglinie zumachen.",
 ["Die Stürmer laufen an.","Das Mittelfeld schiebt gleich mit nach.","Kein Gegner darf frei zwischen den Reihen stehen."],
 "Pressing funktioniert nur, wenn alle Reihen zusammen schieben.",
 "C-Jugend: Abstand zwischen den Reihen maximal 10 Meter.",
 "kette"),
];

// =================== 6) VERTEIDIGEN ===================
const SZ_DEFENSIV = [
SZ("sz098","defensiv","Ball abschirmen lassen","Nicht hinlaufen!",["F","E","D","C","B"],
 "Nicht blind in den Zweikampf springen, sondern den Weg zustellen.",
 ["Zwischen Ball und eigenem Tor bleiben.","Kleine Schritte, nicht überhastet.","Erst zugreifen, wenn der Gegner den Ball nicht am Fuß hat."],
 "Wer hinspringt und verfehlt, ist raus aus dem Spiel.",
 "F-Jugend: „Bleib vor ihm, dann kann er nicht durch.“",
 "absichern"),
SZ("sz099","defensiv","Zweikampf gewinnen","Rein in den Zweikampf!",["E","D","C","B"],
 "Entschlossen und fair zum Ball gehen.",
 ["Abstand verkürzen.","Tief in die Knie, Körper stabil.","Mit der Schulter zum Ball, nicht mit dem Fuß hinterher."],
 "Halbherzige Zweikämpfe verliert man immer.",
 "E-Jugend: Fair heißt: zum Ball, nicht zum Gegner.",
 "doppeln"),
SZ("sz100","defensiv","Herausrücken und absichern","Ich geh raus – du sicherst!",["D","C","B"],
 "Einer attackiert, der Nachbar sichert dahinter ab.",
 ["Der ballnahe Verteidiger rückt heraus.","Die Nachbarn rutschen schräg dahinter.","So entsteht keine Lücke."],
 "Herausrücken ohne Absicherung ist der häufigste Fehler in der Abwehr.",
 "D-Jugend: Immer laut kommunizieren.",
 "absichern"),
SZ("sz101","defensiv","Abwehrkette verschieben","Verschieben!",["E","D","C","B"],
 "Die ganze Kette bewegt sich gemeinsam zum Ball.",
 ["Ball links: alle rutschen nach links.","Abstände zwischen den Verteidigern bleiben gleich.","Nie ein Loch in der Kette lassen."],
 "Eine Kette, die zusammen verschiebt, hat keine Lücken.",
 "E-Jugend: „Ihr seid an einem Seil festgebunden.“",
 "kette"),
SZ("sz102","defensiv","Abseitsfalle","Alle raus!",["C","B"],
 "Die Kette rückt gemeinsam heraus, sobald der Ball gespielt wird.",
 ["Ein klarer Ruf vom Abwehrchef.","Alle vier gleichzeitig raus.","Nach dem Herausrücken sofort Druck auf den Ball."],
 "Der Gegner steht im Abseits – ohne Zweikampf.",
 "C-Jugend: Nur mit gutem Timing und klarer Ansage.",
 "kette"),
SZ("sz103","defensiv","Zentrum zumachen","Mitte zu!",["E","D","C","B"],
 "Der Weg durch die Mitte wird zugestellt, außen wird zugelassen.",
 ["Alle stehen leicht nach innen versetzt.","Der Gegner darf außen spielen.","In der Mitte steht immer jemand."],
 "Tore fallen meist aus der Mitte – außen ist der Weg lang.",
 "E-Jugend: „Lieber außen als durch die Mitte.“",
 "kette"),
SZ("sz104","defensiv","Gegenspieler übergeben","Ich übernehme!",["D","C","B"],
 "Wechselt der Gegner die Zone, wird er übergeben.",
 ["Der Gegenspieler läuft in die Zone des Nachbarn.","Laut rufen: „Ich hab ihn!“","Nicht mitlaufen, sondern die eigene Position halten."],
 "Wer immer mitläuft, reißt die Ordnung auf.",
 "D-Jugend: Übergeben spart Kraft und hält die Ordnung.",
 "rochade"),
SZ("sz105","defensiv","Konter absichern","Wer sichert?",["D","C","B"],
 "Beim eigenen Angriff bleibt jemand für den Konter hinten.",
 ["Vor dem Angriff klären: wer bleibt?","Der Absichernde steht zentral hinter dem Ball.","Bei Ballverlust verzögert er, bis alle zurück sind."],
 "Die meisten Gegentore fallen nach eigenen Angriffen.",
 "D-Jugend: Immer einer mehr hinten als der Gegner vorne hat.",
 "absichern"),
SZ("sz106","defensiv","Verzögern","Verzögere!",["E","D","C","B"],
 "Nicht sofort attackieren, sondern Zeit gewinnen, bis Hilfe da ist.",
 ["Rückwärts laufen, Abstand halten.","Den Gegner nach außen lenken.","Erst zugreifen, wenn ein Mitspieler da ist."],
 "Zeit ist die beste Waffe gegen einen Konter.",
 "E-Jugend: „Nicht hinspringen – bremsen!“",
 "absichern"),
SZ("sz107","defensiv","Nach der Flanke klären","Weg damit!",["E","D","C","B"],
 "Den Ball hoch, weit und zur Seite klären.",
 ["Zum Ball gehen, nicht warten.","Hoch und weit – am besten zur Seite.","Nie quer durch den eigenen Strafraum."],
 "Ein Querpass im eigenen Strafraum ist das größte Risiko im Fußball.",
 "E-Jugend: „Hoch, weit, zur Seite.“",
 "kette"),
SZ("sz108","defensiv","Standard verteidigen","Jeder hat einen!",["E","D","C","B"],
 "Vor jeder Ecke ist klar, wer welchen Gegner deckt.",
 ["Vorher aufteilen: jeder nimmt einen.","Zwei stehen an den Pfosten.","Einer am Sechzehner für den zweiten Ball."],
 "Die meisten Standardtore fallen, weil jemand frei stand.",
 "E-Jugend: Vor der Ecke laut durchzählen.",
 "eckepfosten"),
SZ("sz109","defensiv","Zweiter Ball","Zweiter Ball!",["D","C","B"],
 "Nach langen Bällen und Kopfbällen den Abpraller holen.",
 ["Nach dem Kopfball nicht stehen bleiben.","Zum abprallenden Ball starten.","Wer den zweiten Ball hat, hat den Angriff."],
 "Zweite Bälle entscheiden Spiele – sie sind reine Willenssache.",
 "D-Jugend: Immer den Kopf heben und reagieren.",
 "gegenpressing"),
SZ("sz110","defensiv","Torwart-Kommando","Hört auf den Keeper!",["E","D","C","B"],
 "Der Torwart sieht alles und leitet die Abwehr an.",
 ["Der Torwart ruft laut: „Raus!“ oder „Ich hab ihn!“","Die Abwehr reagiert sofort.","Kein Diskutieren im Strafraum."],
 "Nur der Torwart sieht das ganze Feld vor sich.",
 "E-Jugend: Kommandos vorher üben.",
 "twaktion"),
SZ("sz111","defensiv","Eng am Gegner bei Flanken","Kleb dran!",["D","C","B"],
 "Bei Hereingaben immer zwischen Gegner und Ball stehen.",
 ["Gegenspieler suchen, bevor der Ball kommt.","Halb zum Ball, halb zum Gegner stehen.","Vor ihm zum Ball gehen."],
 "Wer nur auf den Ball schaut, verliert seinen Gegner.",
 "D-Jugend: Immer Blick zwischen Ball und Gegner pendeln.",
 "flanke"),
SZ("sz112","defensiv","Rückzug ins Zentrum","Alle zurück in die Mitte!",["E","D","C","B"],
 "Nach Ballverlust zuerst den direkten Weg zum Tor zulaufen.",
 ["Nicht dem Ball hinterherlaufen.","Den kürzesten Weg zum eigenen Tor nehmen.","Erst innen sortieren, dann nach außen arbeiten."],
 "Der Gegner braucht die Mitte, um gefährlich zu werden.",
 "E-Jugend: „Lauft nach Hause, nicht zum Ball.“",
 "absichern"),
SZ("sz113","defensiv","Innenverteidiger bleibt","Einer bleibt drin!",["D","C","B"],
 "Bei Kontern bleibt ein Innenverteidiger immer im Zentrum.",
 ["Der ballferne Innenverteidiger rückt nie ganz mit.","Er hält die Mitte.","So gibt es nie ein leeres Zentrum."],
 "Ein leeres Zentrum ist ein sicheres Gegentor.",
 "D-Jugend: Absprache vor dem Spiel.",
 "absichern"),
SZ("sz114","defensiv","Zeit schinden bei Führung","Ruhe rein!",["D","C","B"],
 "Bei knapper Führung das Tempo herausnehmen.",
 ["Ball in der Ecke abschirmen.","Keine unnötigen Risikopässe.","Ruhig bleiben, Ball laufen lassen."],
 "Wer den Ball hat, kann kein Gegentor bekommen.",
 "D-Jugend: Fair bleiben – Zeitspiel wird bestraft.",
 "ablage"),
SZ("sz115","defensiv","Kommunikation in der Abwehr","Redet!",["F","E","D","C","B"],
 "Ständig reden: „Rechts frei!“, „Hinter dir!“, „Ich hab ihn!“",
 ["Immer den Mitspieler informieren.","Kurze, klare Wörter.","Lieber einmal zu viel rufen."],
 "Die meisten Fehler entstehen aus Missverständnissen, nicht aus Technik.",
 "F-Jugend: Drei feste Rufe reichen.",
 "kette"),
];

// =================== 7) UMSCHALTEN & KONTER ===================
const SZ_UMSCHALT = [
SZ("sz116","umschalt","Schnell umschalten","Umschalten!",["E","D","C","B"],
 "Nach dem Ballgewinn sofort nach vorne denken.",
 ["Ball erobert.","Erster Blick und erster Pass nach vorne.","Zwei Spieler starten sofort mit."],
 "Direkt nach dem Ballgewinn ist die gegnerische Ordnung offen.",
 "E-Jugend: „Ball geholt? Sofort nach vorn schauen.“",
 "konter"),
SZ("sz117","umschalt","Konter über außen","Konter außen!",["E","D","C","B"],
 "Der Konter läuft über die freie Außenbahn.",
 ["Ballgewinn in der eigenen Hälfte.","Der Flügel startet sofort an der Linie.","Langer Pass in seinen Lauf."],
 "Beim Konter ist außen fast immer frei, weil der Gegner in der Mitte angreift.",
 "E-Jugend: Der schnellste Spieler startet immer.",
 "konter"),
SZ("sz118","umschalt","Drei Kontakte zum Tor","Drei Kontakte!",["D","C","B"],
 "Beim Konter mit möglichst wenigen Kontakten zum Abschluss.",
 ["Annehmen und sofort weiter.","Höchstens drei Pässe bis zum Abschluss.","Kein Querspiel, kein Zögern."],
 "Jede zusätzliche Sekunde bringt einen Verteidiger zurück.",
 "D-Jugend: Tempo vor Schönheit.",
 "konter"),
SZ("sz119","umschalt","Konter absichern","Zwei bleiben!",["D","C","B"],
 "Beim eigenen Konter bleiben zwei Spieler zur Absicherung.",
 ["Drei laufen an, zwei sichern.","Die Absichernden stehen zentral.","Bei Ballverlust verzögern sie sofort."],
 "Ein gescheiterter Konter darf nicht zum Gegenkonter werden.",
 "D-Jugend: Fest verabreden, wer sichert.",
 "absichern"),
SZ("sz120","umschalt","Zweite Welle","Nachrücken!",["D","C","B"],
 "Nach dem ersten Angreifer kommt sofort die zweite Welle.",
 ["Der erste zieht die Abwehr auf sich.","Zwei weitere laufen mit Abstand nach.","Ablage oder Rückpass auf sie."],
 "Die zweite Welle kommt in Räume, die der erste Angreifer geöffnet hat.",
 "D-Jugend: Nie allein kontern.",
 "konter"),
SZ("sz121","umschalt","Ballgewinn hoch nutzen","Sofort abschließen!",["D","C","B"],
 "Wird der Ball nahe am gegnerischen Tor erobert, sofort abschließen.",
 ["Ballgewinn im Angriffsdrittel.","Kein Querpass – direkt zum Tor.","Abschluss innerhalb von drei Sekunden."],
 "Der Gegner steht in dieser Situation komplett falsch.",
 "D-Jugend: Sofortigkeit schlägt Schönheit.",
 "gegenpressing"),
SZ("sz122","umschalt","Umschalten nach Standard","Nach der Ecke aufpassen!",["D","C","B"],
 "Nach eigener Ecke sofort in die Defensivordnung.",
 ["Ecke geht verloren.","Der Absichernde verzögert.","Alle anderen laufen den kürzesten Weg zurück."],
 "Konter nach eigener Ecke sind die gefährlichsten Gegenangriffe.",
 "D-Jugend: Immer zwei am Sechzehner absichern lassen.",
 "absichern"),
SZ("sz123","umschalt","Ruhe nach Ballgewinn","Erst sichern!",["E","D","C","B"],
 "Geht der Konter nicht, wird der Ball erst einmal gesichert.",
 ["Ballgewinn, aber alle Wege zu.","Kurzer Pass zum freien Mitspieler.","Ball laufen lassen und neu aufbauen."],
 "Nicht jeder Ballgewinn ist ein Konter – erzwungene Konter enden im Ballverlust.",
 "E-Jugend: Erst schauen, dann entscheiden.",
 "verlagern"),
SZ("sz124","umschalt","Der lange Ball auf den Startenden","Lauf!",["F","E","D"],
 "Ein einfacher, sofortiger Ball in den Lauf des schnellsten Spielers.",
 ["Ballgewinn.","Der schnelle Spieler startet ohne Aufforderung.","Ball einfach in den freien Raum."],
 "Im Kinderfußball ist das der wirksamste Konter überhaupt.",
 "F-Jugend: Ein Ruf, ein Lauf, ein Ball.",
 "steilpass"),
SZ("sz125","umschalt","Gegenkonter verhindern","Sofort stellen!",["D","C","B"],
 "Nach eigenem Ballverlust den Ballführenden sofort stellen.",
 ["Der nächste Spieler geht sofort hin.","Nicht grätschen, sondern verzögern.","Die anderen laufen zurück."],
 "Ein gestellter Gegner kann keinen schnellen Pass spielen.",
 "D-Jugend: Der Nächste geht, alle anderen sortieren sich.",
 "gegenpressing"),
];

// =================== 8) STANDARDS ===================
const SZ_STANDARD = [
SZ("sz126","standard","Ecke kurz ausspielen","Kurze Ecke!",["E","D","C","B"],
 "Statt in den Strafraum wird kurz gespielt.",
 ["Ein Mitspieler kommt zur Eckfahne.","Kurzer Pass zu ihm.","Zu zweit gegen einen: flanken oder durchgehen."],
 "Die Abwehr steht im Strafraum – draußen entsteht Überzahl.",
 "E-Jugend: Einfacher als eine gute Flanke.",
 "eckekurz"),
SZ("sz127","standard","Ecke auf den ersten Pfosten","Erster Pfosten!",["D","C","B"],
 "Der Ball wird scharf an den kurzen Pfosten gespielt.",
 ["Ein Läufer startet von hinten zum ersten Pfosten.","Scharfe, flache Hereingabe.","Verlängern reicht – nicht voll draufhauen."],
 "Ein scharfer Ball an den ersten Pfosten ist kaum zu verteidigen.",
 "D-Jugend: Verlängern üben, nicht dreschen.",
 "eckepfosten"),
SZ("sz128","standard","Ecke an den zweiten Pfosten","Langer Pfosten!",["D","C","B"],
 "Der Ball fliegt hinter die Abwehr an den langen Pfosten.",
 ["Zwei Läufer ziehen zum ersten Pfosten.","Der dritte bleibt hinten.","Ball an den langen Pfosten."],
 "Die Abwehr folgt den ersten Läufern und lässt hinten Platz.",
 "D-Jugend: Immer einen hinten stehen lassen.",
 "eckepfosten",{r:true}),
SZ("sz129","standard","Ecke auf den Rückraum","Rückraum!",["C","B"],
 "Die Ecke geht flach an den Sechzehner.",
 ["Alle Mitspieler ziehen in den Strafraum.","Der Ball kommt flach an den Sechzehner.","Direktschuss aus dem Rückraum."],
 "Vor dem Strafraum steht bei Ecken fast nie jemand.",
 "C-Jugend: Wirkt besonders gegen tief verteidigende Teams.",
 "eckekurz"),
SZ("sz130","standard","Freistoß als Flanke","Freistoß rein!",["E","D","C","B"],
 "Der Freistoß von der Seite wird wie eine Flanke gespielt.",
 ["Läufer stellen sich versetzt auf.","Ball in den Lauf, nicht auf den Kopf.","Beim Anlauf starten, nicht vorher."],
 "Bewegung schlägt Stehen – wer läuft, kommt zuerst an den Ball.",
 "E-Jugend: Erst loslaufen, wenn der Schütze anläuft.",
 "flanke"),
SZ("sz131","standard","Freistoß mit Ablage","Ablage und Schuss!",["D","C","B"],
 "Der Freistoß wird kurz abgelegt und aus dem Lauf geschossen.",
 ["Ein Spieler legt seitlich ab.","Der zweite kommt mit Anlauf.","Schuss neben der Mauer vorbei."],
 "Die Mauer springt beim direkten Schuss – beim Schuss aus dem Lauf ist sie zu spät.",
 "D-Jugend: Zwei Schritte Ablage reichen.",
 "freistoss"),
SZ("sz132","standard","Freistoß direkt","Direkt drauf!",["D","C","B"],
 "Aus guter Position direkt aufs Tor.",
 ["Ball ruhig hinlegen.","Ecke vorher festlegen.","Innenseite oder Spann – platziert statt fest."],
 "Torhüter in der Jugend stellen die Mauer oft falsch.",
 "D-Jugend: Um die Mauer herum statt drüber.",
 "freistoss"),
SZ("sz133","standard","Mauer stellen","Mauer!",["D","C","B"],
 "Der Torwart stellt die Mauer, die Feldspieler halten die Position.",
 ["Der Torwart sagt, wie viele in die Mauer gehen.","Ein Spieler richtet die Mauer aus.","Alle bleiben stehen, bis der Ball gespielt ist."],
 "Eine schlecht gestellte Mauer ist schlimmer als gar keine.",
 "D-Jugend: Der Torwart entscheidet, nicht die Feldspieler.",
 "freistoss"),
SZ("sz134","standard","Anstoß-Variante","Anstoß lang!",["E","D","C","B"],
 "Beim Anstoß direkt in die Tiefe spielen.",
 ["Kurz zurück legen.","Sofort langer Ball auf die Seite.","Zwei Spieler starten in die Tiefe."],
 "Direkt nach dem Anpfiff ist der Gegner selten sortiert.",
 "E-Jugend: Einmal pro Spiel überraschend.",
 "steilpass"),
SZ("sz135","standard","Abstoß-Variante","Abstoß auf die Seite!",["E","D","C","B"],
 "Der Abstoß geht bewusst auf eine Seite, wo Überzahl herrscht.",
 ["Vorher absprechen, welche Seite.","Alle rücken auf diese Seite.","Zweiten Ball erobern."],
 "Wer weiß, wohin der Ball fliegt, gewinnt den zweiten Ball.",
 "E-Jugend: Ein Zeichen reicht als Absprache.",
 "twaufbau"),
SZ("sz136","standard","Einwurf in der Angriffszone","Einwurf gefährlich!",["D","C","B"],
 "Der Einwurf vorne wird wie ein Standard genutzt.",
 ["Ein Spieler startet zum Tor.","Einwurf hoch in den Strafraum oder flach in den Lauf.","Alle rücken nach."],
 "Ein Einwurf im letzten Drittel ist eine echte Torchance.",
 "D-Jugend: Vorher zwei Varianten festlegen.",
 "einwurf"),
SZ("sz137","standard","Elfmeter-Nachschuss","Rein in den Strafraum!",["E","D","C","B"],
 "Beim Elfmeter laufen die Mitspieler an den Sechzehner.",
 ["Beim Anlauf schon in Bewegung sein.","Nach dem Schuss sofort in den Strafraum.","Abpraller verwerten."],
 "Der Nachschuss ist erlaubt – und kommt öfter als man denkt.",
 "E-Jugend: Immer zwei Spieler mitlaufen lassen.",
 "eins"),
SZ("sz138","standard","Freistoß schnell ausführen","Schnell!",["D","C","B"],
 "Nicht auf den Pfiff warten, sondern sofort spielen.",
 ["Ball liegt, Gegner ist unsortiert.","Sofort flach nach vorne.","Mitspieler müssen wach sein."],
 "Die schnellste Ausführung ist die beste Variante.",
 "D-Jugend: Nur wenn der Schiedsrichter nicht pfeifen muss.",
 "steilpass"),
SZ("sz139","standard","Ecke verteidigen mit Kontervorbereitung","Einer bleibt vorn!",["D","C","B"],
 "Beim Verteidigen einer Ecke bleibt ein schneller Spieler vorn.",
 ["Alle verteidigen im Strafraum.","Ein schneller Spieler bleibt an der Mittellinie.","Nach der Klärung sofort auf ihn spielen."],
 "Der Gegner hat bei seiner Ecke alle vorn – hinten ist es leer.",
 "D-Jugend: Genau daraus entstehen die schönsten Konter.",
 "konter"),
SZ("sz140","standard","Indirekter Freistoß im Strafraum","Kurz antippen!",["C","B"],
 "Der Ball wird angetippt, der zweite schießt.",
 ["Erster Spieler tippt den Ball an.","Zweiter zieht direkt ab.","Nicht zögern, die Mauer kommt sofort."],
 "Direkt darf nicht getroffen werden – also braucht es zwei.",
 "C-Jugend: Selten, aber gut zu wissen.",
 "freistoss"),
];

// =================== 9) TORWART ===================
const SZ_TORWART = [
SZ("sz141","torwart","Grundstellung","Bereit stehen!",["F","E","D","C","B"],
 "Vor jedem Schuss in die richtige Grundstellung.",
 ["Füße schulterbreit, leicht auf den Fußballen.","Hände vor dem Körper, Ellbogen frei.","Kurz stehen bleiben, wenn der Schuss kommt."],
 "Wer im Laufen ist, kann sich nicht abdrücken.",
 "F-Jugend: „Wie ein Frosch, der springen will.“",
 "twaktion"),
SZ("sz142","torwart","Stellungsspiel","Geh raus!",["E","D","C","B"],
 "Ein paar Schritte aus dem Tor verkleinern den Winkel enorm.",
 ["Der Schütze kommt.","Zwei, drei Schritte entgegen.","Groß machen, ruhig stehen bleiben."],
 "Je näher der Torwart, desto kleiner das Tor für den Schützen.",
 "E-Jugend: Nicht hinwerfen, sondern groß bleiben.",
 "twaktion"),
SZ("sz143","torwart","Flanken abfangen","Ich hab ihn!",["D","C","B"],
 "Bei hohen Bällen entschlossen herauskommen und laut rufen.",
 ["Früh entscheiden: rausgehen oder bleiben.","Laut und deutlich rufen.","Mit beiden Händen zum höchsten Punkt."],
 "Eine gefangene Flanke ist der beste Konterstart.",
 "D-Jugend: Lieber klar bleiben als halb rausgehen.",
 "twaktion"),
SZ("sz144","torwart","Abwurf auf den Flügel","Wurf nach außen!",["E","D","C","B"],
 "Nach dem Fangen sofort auf den freien Flügel werfen.",
 ["Ball sicher gefangen.","Sofort hochschauen.","Flach und schnell auf den freien Außenspieler."],
 "Der schnellste Konter startet aus den Händen des Torwarts.",
 "E-Jugend: Rollen ist genauer als werfen.",
 "twaktion"),
SZ("sz145","torwart","Mit dem Fuß mitspielen","Spiel mit!",["E","D","C","B"],
 "Der Torwart ist der elfte Feldspieler beim Aufbau.",
 ["Immer anspielbar hinter der Abwehr stehen.","Ruhig annehmen, hochschauen.","Zur freien Seite spielen."],
 "Mit dem Torwart hat man immer einen Spieler mehr.",
 "E-Jugend: Erst sicher annehmen, dann spielen.",
 "twaufbau"),
SZ("sz146","torwart","1 gegen 1 verteidigen","Groß machen!",["E","D","C","B"],
 "Beim Alleingang groß werden und den Schuss abwarten.",
 ["Entgegenkommen, aber nicht hinwerfen.","Arme und Beine breit.","Erst reagieren, wenn der Ball den Fuß verlässt."],
 "Wer sich zu früh hinwirft, wird umspielt.",
 "E-Jugend: „Werd zur Wand.“",
 "twaktion"),
SZ("sz147","torwart","Abwehrkette dirigieren","Ansagen!",["E","D","C","B"],
 "Der Torwart sagt der Abwehr, was er sieht.",
 ["„Rechts frei!“, „Hinter dir!“, „Alle raus!“","Kurz und laut.","Immer weiter reden, auch wenn der Ball weit weg ist."],
 "Der Torwart hat als einziger das ganze Feld vor Augen.",
 "E-Jugend: Drei feste Kommandos reichen.",
 "kette"),
SZ("sz148","torwart","Rückpass verarbeiten","Ruhig annehmen!",["E","D","C","B"],
 "Rückpässe sicher mit dem Fuß verarbeiten.",
 ["Früh zum Ball bewegen.","Mit dem starken Fuß annehmen, weg vom Angreifer.","Zur freien Seite weiterspielen."],
 "Der Rückpass darf nicht in die Hand – also muss der Fuß sicher sein.",
 "E-Jugend: Jede Woche fünf Minuten üben.",
 "twaufbau"),
SZ("sz149","torwart","Ecken verteidigen","Meine Ecke!",["D","C","B"],
 "Der Torwart bestimmt bei Ecken die Ordnung.",
 ["Position auf der Torlinie, leicht zur Mitte.","Zwei Spieler an die Pfosten stellen.","Klar rufen: rausgehen oder bleiben."],
 "Der Torwart hat den Überblick – die Abwehr richtet sich nach ihm.",
 "D-Jugend: Vorher besprechen, nicht während der Ecke.",
 "eckepfosten"),
SZ("sz150","torwart","Schnelles Umschalten nach Parade","Sofort weiter!",["D","C","B"],
 "Nach der Parade sofort den Konter starten.",
 ["Ball sichern.","Direkt aufstehen und schauen.","Schneller Abwurf auf den startenden Flügel."],
 "Nach einem gegnerischen Abschluss sind alle Gegner weit vorne.",
 "D-Jugend: Ein guter Abwurf ist ein Konterpass.",
 "konter"),
];

// Trainer suchen mit ihren eigenen Woertern: "ueberlaufen" statt "Ueberlappen",
// "Wand" statt "Doppelpass". Diese Woerter zaehlen bei der Suche mit.
export const SZ_SYNONYME = {
  sz001:"überlaufen overlap außen vorbei hinterlaufen laufen lassen",
  sz002:"wand wandspiel give and go one two abklatschen prellen",
  sz003:"wand klatschen ablegen direkt zurück",
  sz004:"tiefenpass durchstecken lochpass hinter die kette schnittstelle",
  sz005:"überkreuz kreuzlauf ballübergabe mitnehmen",
  sz006:"seitenwechsel rüberspielen langer ball quer",
  sz007:"wandspieler prallen lassen rücken zum tor pivot",
  sz008:"dritter mann kombination laufweg",
  sz009:"schräglauf diagonallauf einlaufen lücke",
  sz010:"drehen umdrehen aufdrehen andrehen",
  sz011:"überzahl zwei gegen eins konter ausspielen",
  sz012:"breit stehen auseinander feld groß machen",
  sz013:"tiefe geben durchstarten hinter die abwehr",
  sz014:"freilaufen lösen anbieten wegdrehen",
  sz015:"positionswechsel tauschen rotation",
  sz016:"direktspiel eine berührung prallen",
  sz017:"abschirmen ball behaupten körper",
  sz018:"andribbeln binden gegner ziehen",
  sz019:"schnittstelle lücke zwischen verteidigern",
  sz020:"überlaufen überlappen overlap außenverteidiger vorbei",
  sz021:"unterlaufen innen durch underlap",
  sz022:"kopf hoch orientieren umschauen",
  sz023:"tempowechsel antritt beschleunigen",
  sz024:"erste berührung mitnehmen ballannahme",
  sz025:"kurz kurz lang locken",
  sz026:"zurück neu aufbauen umkehren",
  sz027:"eins gegen eins dribbeln finte trauen",
  sz028:"wand über die spitze prallen lassen",
  sz029:"toter winkel rücken decken lösen",
  sz030:"dreieck anspielstationen staffelung",
  sz031:"pass und lauf nachrücken weiterlaufen",
  sz032:"kurzer pfosten langer pfosten flanke",
  sz041:"grundlinie flanke hereingabe",
  sz043:"nach innen ziehen einrücken abschluss",
  sz044:"überlaufen außen hinterlaufen flügel",
  sz056:"torschuss abschluss schießen",
  sz059:"alleine vorm tor eins gegen torwart",
  sz086:"anlaufen lenken pressing außen",
  sz090:"gegenpressing sofort zurück nachsetzen",
  sz102:"abseitsfalle rausrücken kette",
  sz116:"umschalten schnell nach vorne konter",
  sz126:"ecke kurz variante standard",
  sz130:"freistoß flanke standard",
  sz141:"torwart grundstellung bereit",
};
export const SPIELZUEGE = [
  ...SZ_ANGRIFF, ...SZ_AUSSEN, ...SZ_ABSCHLUSS, ...SZ_AUFBAU,
  ...SZ_PRESSING, ...SZ_DEFENSIV, ...SZ_UMSCHALT, ...SZ_STANDARD, ...SZ_TORWART,
];
